### ISSUE TITLE
Announcement attachments not sent

### ISSUE THREAD

**Issue by jderriks** [chamilo/chamilo-lms#1396]
Chamilo 1.10.8: When you add an attachment to an announcement, this attachment is not sent by mail.
It is only visible in the on-line announcement. In Chamilo 1.9 it still worked as expected.

**Comment by jloguercio** [comment]
This bug was already fixed in 1.11.x

**Comment by jloguercio** [comment]
Here : https://github.com/chamilo/chamilo-lms/pull/1122 and here : https://github.com/chamilo/chamilo-lms/pull/1123

**Comment by jloguercio** [comment]
tested in 1.11.chamilo.org

**Comment by jderriks** [comment]
doesn;t work in last pull from 1.10.x branch sept-8-2016

**Comment by ywarnier** [comment]
That would be because we are only developing one branch at a time, and the current development branch is 1.11. Being a minor issue in 1.10, we decided not to loose time on this one.

**Comment by jderriks** [comment]
Is it safe to checkout 1.11.x for a 2476 users production environment or are there database changes involved?
The two commits mentioned  above didn't seem to solve it and some of the teachers here don't think it is a minor issue. Documents and announcements are tools nr. 1 and 2 in usage.

**Comment by ywarnier** [comment]
It is not yet safe to do so without proper technical support. We just did it for a 20,000 students portal, but we solved a series of issues in the process and are still finetuning it. As soon as the first Release Candidate is released (which should be next week), it will be considered safe to checkout 1.11.x. However, there *are* database changes involved (otherwise it would have been a 1.10.10), so the normal upgrade procedure (documented in the installation guide) should be followed + (if you checkout from Git) the proper composer update workflow described in the README.md (I think it's updated).

**Comment by jderriks** [comment]
A 20.000 students portal?! On september 1st our Chamilo system couldn't handle 500 users logging in within a 1 hour period. Two load-balanced Redhat VM's had 100% cpu load during that time and some users were disconnected from the webserver. Never seen these issues witch Chamilo before. 20000 users is not a problem until 500 of them try to login at the same time... I hope it's not doctrine causing this.

**Comment by ywarnier** [comment]
As you might see in the commits in 1.11, we've added many changes to the database (added indexes and changed a few queries), so it might boost your portal.

Slowliness is most *certainly* due to the introduction of Doctrine overall, but the impact should be reduced by using PHP 5.6 or 7 with opcache enabled and properly configured (there are also a few optimizations in place if you have ACPu installed and configured).

I haven't analyzed it in detail yet but right now there are 150 users simultaneously connected on a 8-CPUs server with Apache and MySQL on the same server, and the load average is at 0.64, so obviously there are differences between your setup and ours. Having 500 users use the social network will have a negative impact if all database indexes are not added from the latest commits.

We don't recommend RedHat because it's difficult to get the most out of PHP on this distribution, but it's still better than Windows :-)

**Comment by ywarnier** [comment]
Works in 1.11
