### ISSUE TITLE
Users tool: changing student to teacher not possible.

### ISSUE THREAD

**Issue by jderriks** [chamilo/chamilo-lms#1397]
In versions before 1.10 a teacher could promote a collegue (who subscribed to a course as a student) to the teacher status by a single click in the course user list. Now there is only the "set as coach" option. The workaround is to first unsubscribe the user from the course and then manually subscribe the user as a teacher. Is this the only way to promote a user to teacher in a course?

**Comment by ywarnier** [comment]
I don't remember such feature in previous versions. Do you have a previous version from which you can take a screenshot so I see what you mean?

**Comment by jderriks** [comment]
![screen shot 2016-09-15 at 21 32 56](https://cloud.githubusercontent.com/assets/1659604/18564528/33d9db22-7b8c-11e6-8365-4e77aceae3ec.png)

Chamilo 1.9.x: User Tool, edit, check the teacher box... ready!
Chamilo 1.10.x: User Tool, select students tab, unsubscribe teacher-to-be, goto teacher tab, subscribe teacher.

**Comment by ywarnier** [comment]
The option changed name in 1.10/1.11, but it's the same as before (or better said: we didn't add any other option). The change was due to the fact that the "teacher" text box was actually misleading: it wouldn't actually set someone as teacher but rather as "teacher assistant", who would have access to students tracking but not to the creation of new content.
This results (and resulted before), in the database, in a change to an additional field (I think) in the course_rel_user table, but *not* in a change of status from 5 (student) to 1 (teacher).
