### ISSUE TITLE
404 Page not Found (Any Created Course)

### ISSUE THREAD

**Issue by AFreeman94** [chamilo/chamilo-lms#1463]
### Expected behavior / Resultado esperado / Résultat attendu

Course Homepage Load

### Actual behavior / Resultado real / Résultat réel

However I get

Not Found

The requested URL /courses/TEST/index.php was not found on this server.

Apache/2.2.22 (Debian) Server at learning.durhamcpr.com Port 80

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Any course you try and make on the server it doesnt work.

Permissions on app/courses --> 0777 and in Portal / Configuration they are set to default 0777 and 0666

PLEASE HELP

**Comment by AFreeman94** [comment]
Below is my virtual server configuration 

`	DocumentRoot "/var/www/learning"
	ServerName learning.durhamcpr.com
	
	<LocationMatch "/.git*">
		order deny,allow
		deny from all
	</LocationMatch>

	<Directory ~/.>
		AllowOverride None
		Options -Indexes
	</Directory>
	
	<Directory /var/www/learning/>
		AllowOverride All
		Order allow,deny
		Allow from all
		
		RewriteEngine On
		RewriteCond %{QUERY_STRING} ^id=(.*)$
		RewriteRule ^([^/.]+)/?$ user.php?$1 [L]
		RewriteRule ^certificates/$ certificates/index.php?id=%1 [L]
		RewriteRule ^courses/([^/]+)/$ app/course_home/course_home.php?cDir=$1 [QSA,L]
		RewriteRule ^courses/([^/]+)/index.php$ main/course_home/course_home.php?cDir=$1 [QSA,L]
		RewriteRule ^courses/([^/]+)/document/(.*)$ main/document/download.php?doc_url=/$2&cDir=$1 [QSA,L]
		RewriteRule ^courses/([^/]+)/work/(.*)$ main/work/download.php?file=work/$2&cDir=$1 [QSA,L]
		RewriteRule ^courses/([^/]+)/upload/(.*)$ main/courses/$1/upload/$2 [QSA,L]
		RewriteRule ^courses/([^/]+)/course-pic85x85.png$ main/courses/$1/course-pic85x85.png [QSA,L]
		RewriteRule ^courses/([^/]+)/course-pic.png$ app/courses/$1/course-pic.png [QSA,L]
		RewriteRule ^session/(\d{1,})/about/?$ main/session/about.php?session_id=$1 [L]
		RewriteRule ^badge/(\d{1,})/user/(\d{1,}) main/badge/issued.php?skill=$1&user=$2 [L]
	</Directory>
	
	# RewriteCond %{QUERY_STRING} ^id=(.*)$
	
	# http://my.chamilo.net/certificates/?id=123 to http://my.chamilo.net/certificates/index.php?id=123
	RewriteRule ^certificates/$ certificates/index.php?id=%1 [L]`

**Comment by ywarnier** [comment]
If you put all the rewrite rules inside the Apache config, you do *not* need to set AllowOverride All, because then it will interpret the rules from the Apache config and *then* from the .htaccess.

Your configuration seems good. If your Apache's rewrite module is enabled ("a2enmod rewrite" on Ubuntu) and this Apache config is effectively taken into account, it should work nicely...

**Comment by AFreeman94** [comment]
thank you :)

**Comment by clement1994** [comment]
Bonjour , désoler , j'ai le même problème sur la version 1.11.4
je les installé sous ubuntu server 14.04 (sa me faisait pareil) donc j'ai installé sous ubuntu server 12.05 mais toujours pareil
mon répertoire apache2 ne contient pasde .htaccess

besoin de votre aide
MERCI

![erreur chamilo](https://user-images.githubusercontent.com/31939434/30403127-c52a4b32-98cf-11e7-92a6-677ab717c0d4.PNG)



NB:je suis pas expert dans ce domaine

**Comment by ywarnier** [comment]
Bonjour @clement1994,
Le .htaccess doit se trouver dans le répertoire /chamilo/ (donc qqchose/chamilo/.htaccess) et est livré avec Chamilo, donc normalement une installation normale de Chamilo 1.11.* met le fichier au bon endroit.

Ce qui est par contre plus compliqué c'est qu'il faut que Apache accepte de gérer ces fichiers .htaccess. C'est une configuration spécifique dans la partie `<VirtualHost>` de la configuration d'Apache, et ça change un peu selon qu'on est avant ou sur une version 2.4 d'Apache (et donc avant c'est `AllowOverride All` qui doit s'y retrouver, et après c'est `Require All Granted`. Ensuite il faut redémarrer Apache pour prendre ce changement de config en compte.

C'est évidemment plus simple, si on n'est pas expert, d'utiliser des solutions toutes faites comme Softaculous, Installatron, ou Chamilo Light, donc les prix et les niveaux de services varient. Sur sa propre machine, si l'on utilise Windows (et donc probablement WAMP ou XAMP), il suffit généralement de trouver un menu (clic droit sur l'icône de la barre de notifications?) qui permet de changer la config d'Apache.

Enfin, tout ça est décrit plus ou moins en long et en large dans le guide d'installation (qui est disponible en français), l'avez vous lu?

**Comment by clement1994** [comment]
Oui ,effectivement .

Le 14 sept. 2017 02:01, "Yannick Warnier" <notifications@github.com> a
écrit :

Bonjour @clement1994 <https://github.com/clement1994>,
Le .htaccess doit se trouver dans le répertoire /chamilo/ (donc
qqchose/chamilo/.htaccess) et est livré avec Chamilo, donc normalement une
installation normale de Chamilo 1.11.* met le fichier au bon endroit.

Ce qui est par contre plus compliqué c'est qu'il faut que Apache accepte de
gérer ces fichiers .htaccess. C'est une configuration spécifique dans la
partie <VirtualHost> de la configuration d'Apache, et ça change un peu
selon qu'on est avant ou sur une version 2.4 d'Apache (et donc avant
c'est AllowOverride
All qui doit s'y retrouver, et après c'est Require All Granted. Ensuite il
faut redémarrer Apache pour prendre ce changement de config en compte.

C'est évidemment plus simple, si on n'est pas expert, d'utiliser des
solutions toutes faites comme Softaculous, Installatron, ou Chamilo Light,
donc les prix et les niveaux de services varient. Sur sa propre machine, si
l'on utilise Windows (et donc probablement WAMP ou XAMP), il suffit
généralement de trouver un menu (clic droit sur l'icône de la barre de
notifications?) qui permet de changer la config d'Apache.

Enfin, tout ça est décrit plus ou moins en long et en large dans le guide
d'installation (qui est disponible en français), l'avez vous lu?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/chamilo/chamilo-lms/issues/1463#issuecomment-329347276>,
or mute the thread

**Comment by clement1994** [comment]
Je trouve mon fichier . Htaccess er je vérifie avec ce que vous avez
envoyé.

Merci de votre reponse.

**Comment by lmanyonho** [comment]
I solved this error by modifying `/etc/apache2/sites-available/000-default.conf` to contain.

```
<Directory "/var/www/xxxxx"> where xxxxx is your chamilo installation folder name
AllowOverride all
Order allow,deny
Allow from all
</Directory>
```

near `</VirtualHost>` then `service apache2 restart`

**Comment by ywarnier** [comment]
@lmanyonho Did you also have a
```
<Directory />
```
section in your VirtualHost, as described in the installation guide? https://11.chamilo.org/documentation/installation_guide.html#1._Pre-requisites (Apache's redirects)

**Comment by lmanyonho** [comment]
@ywarnier no I did not, I had to add it manually

**Comment by ywarnier** [comment]
My question is rather whether you need the two different `<Directory>` blocks (one for `/` and one for `/var/www/chamilo`), or if only one is enough.

**Comment by lmanyonho** [comment]
@ywarnier oh my bad, you need 2 because each directory can be having its own set of rules

**Comment by ywarnier** [comment]
I'll update the installation guide, then. Thanks.

**Comment by lmanyonho** [comment]
You are welcome, this software is amazing!

**Comment by ywarnier** [comment]
Thanks, make sure you spread the word :-)

**Comment by lmanyonho** [comment]
I have a question relating to my Chamilo intsallation on PHP 7.0 and I
don't know if I should create a new thread for it but it's pretty simple I
guess

Leon Manyonho
Cyberoam Certified Network And Security Professional (CCNSP) p:
+263733384364
w: +263713384364
E: lmanyonho@ht7dev.com
http://www.ht7dev.com

**Comment by ywarnier** [comment]
Yes, in a new thread please

**Comment by clement1994** [comment]
Bonjour bonjour a tous , je viens sollicité votre aide .

une aide pour modifier mon espace chamilo avec un autre css , mais je ne
sais pas comment m'y rendre.
Aussi pour l'installation de Bigbluebutton pour intégrer la Visio
conférence

NB: J'UTILISE CHAMILO LMS COMME CMS POUR MON MÉMOIRE DE LICENCE PRO , JE
DOIS METTRE EN PLACE UNE PLATEFORME DE COURS EN LIGNE

2017-09-18 20:23 GMT+00:00 Yannick Warnier <notifications@github.com>:

**Comment by clement1994** [comment]
MERCI


Le 13 novembre 2017 à 18:54, clem Guiguimde <clemguiguimde@gmail.com> a
écrit :

**Comment by andergmartins** [comment]
I recently had a similar issue. After installing and configuring apache, .htaccess, etc... everything were working great. But after restore some backup files the images of courses and /courses stopped working.
After debugging I realized the problem was related to permissions. So I added www-data as owner for all the files in the chamilo folder, including the files I restored. That fixed it for me.
