### ISSUE TITLE
Google translate on Forum and Github

### ISSUE THREAD

**Issue by jderriks** [chamilo/chamilo-lms#1572]
original English version below. Google translated it like this:

### Comportamiento esperado / Resultado esperado / Résultat attendu
Los problemas en github o posts en [chamilo.org/forum](https://chamilo.org/forum/) en español o francés deberían activar una opción de "traducir esta página" en el navegador.

El comportamiento real esperado es que todo el mundo usa el inglés en Internet, pero alguna torre en Babel ha puesto fin a eso hace mucho tiempo :-)

### Comportamiento real / Resultado real / Résultat réel
Tengo que cortar + pegar texto en google traducir o volver a tomar clases de español en duolingo.com

### Pasos para reproducir / Pasos para reproducir / Étapes pour reproduire
1. ir a highschool y saltar español en favor de la química y la biología :-)
2. intentar leer mensajes de github o foro en francés o español (porque otros saltaron inglés en highschool?)
3. Github y phpBB no activan Chrome para traducir nada.

========================================

### Expected behavior / Resultado esperado / Résultat attendu
Issues on github or posts on [chamilo.org/forum](https://chamilo.org/forum/) in Spanish or French should trigger a "translate this page" option in the browser.

The real expected behaviour is that everyone uses English on the Internet but some tower in Babel has put at end to that a long time ago :-) 

### Actual behavior / Resultado real / Résultat réel
I have to cut + paste text into google translate or retake Spanish lessons on duolingo.com 

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
1. go to highschool and skip Spanish in favor of Chemistry and Biology :-)
2. try to read github or forum posts in French or Spanish (because others skipped English in highschool?)
3. Github and phpBB don't trigger Chrome to translate anything.

Feliz navidad y próspero 2017!

**Comment by ywarnier** [comment]
:-)

At @chamilo we try to be as inclusive as possible. There are about [470M native Spanish speakers](https://en.wikipedia.org/wiki/Spanish_language) around the world and only about [400M native English speakers](https://en.wikipedia.org/wiki/English_language), and [600-700M English as a foreign language speakers](https://en.wikipedia.org/wiki/English_language) so we cannot really force the millions of Spanish-speaking reporters to use English, as we would loose the contributions of many of them.

As most of the @beeznest team speaks Spanish as a first or second language, we feel like we can support it. More than 50% speaks French too. We don't, however, have that 50% neither in Dutch (I know, you didn't ask for that but others did) nor in Chinese nor in any other language, which limits the possibilities, but if we could, we would do it.

Although we will loose a bit of synchronization between issues due to the non-standardization of the language, we feel that this is one of the great advantages of @chamilo as a software project in comparison to other Open Source LMSes.

I felt your issue couldn't be left unanswered, and I should certainly translate it in Spanish, but I think I can better invest my time now on solving issues ;-)

**Comment by ywarnier** [comment]
By the way: asking Github for a translate button would be a good idea. You can do that here: https://github.com/contact
