### ISSUE TITLE
Language translation error

### ISSUE THREAD

**Issue by AliaMori** [chamilo/chamilo-lms#1667]
### Current behavior / Resultado actual / Résultat actuel
When translating (in any sub-language), the language variable called "registration" always overides the language variable "AllowRegistrationTitle".   As a result, you always get the same information twice on the self-signup page.  Image attached.
![languagevariable](https://cloud.githubusercontent.com/assets/22804098/22859109/95dc2884-f10c-11e6-96d3-2e2de62c941d.png)

This error occurs both on 1.10.8 and on the unstable.chamilo.org  1.11

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.10.2  and 1.11 ( unstable.chamilo.org )

**Comment by ywarnier** [comment]
Hello, could you send us a screenshot of both Registration and AllowRegistrationTitle variables in the sub-language translation tool?

**Comment by AliaMori** [comment]
Yes, here is. Thank you.
![screengrap](https://cloud.githubusercontent.com/assets/22804098/22868768/783ac254-f1d4-11e6-8a2a-7b218e90380c.png)

**And the result is this:**

![screengrab2](https://cloud.githubusercontent.com/assets/22804098/22868785/942d10a2-f1d4-11e6-9201-ba7621c2cabc.png)

**Comment by AngelFQC** [comment]
In `main/auth/inscription.php`file, the page title can be `$TermsAndConditions` if the `allow_terms_conditions` setting is enabled, or can be `$Registration`, but no `$AllowRegistrationTitle`.

The `$AllowRegistrationTitle` variable is used to define the `allow_registration` setting in `main/admin/settings.php?search_field=allow_registration&category=search_setting` page.

The double title you see is because one is part of breadcrumb and the other one is the page title.
