### ISSUE TITLE
images, disapear from the maps in the course filemanager and canot by used

### ISSUE THREAD

**Issue by learningcentrum** [chamilo/chamilo-lms#1740]
### Current behavior / Resultado actual / Résultat actuel
![filemanager chaminlo](https://cloud.githubusercontent.com/assets/26379170/23851052/426c6122-07e2-11e7-8c4e-a5eff206b315.jpg)
 I can not place images from the course map in to the course, If I use the uploader, the images are not placebale
I can place images from the docent maps in to the course

### Expected behavior / Resultado esperado / Résultat attendu
![file manager](https://cloud.githubusercontent.com/assets/26379170/23851064/52ea9622-07e2-11e7-807a-8df0848bdc20.jpg)

**Comment by jmontoyaa** [comment]
It looks like there's a problem in the course folder permissions.

**Comment by learningcentrum** [comment]
The folder / file permissions are the same
 file 0664 / map 775

**Comment by learningcentrum** [comment]
the screen print
![rechten-users](https://cloud.githubusercontent.com/assets/26379170/24143663/ba4e9f0e-0e2a-11e7-86c2-24dce413332c.jpg)
![rechten-courses](https://cloud.githubusercontent.com/assets/26379170/24143662/ba4e1caa-0e2a-11e7-92a7-ac046736f683.jpg)

**Comment by learningcentrum** [comment]
a have 2 installations, one the working and a test
the working with more docent and users have the problem, not in the beginning, but on the way we are making courses ect.
the test installation have no problem
is the problem security config data in a file ore in the database
I can do a little programing, but I am not a programmer

**Comment by learningcentrum** [comment]
http://lms.learningcentrum.nl
http;//test.learningcentrum.nl

**Comment by learningcentrum** [comment]
I haven make a new lms, put the courses on, ok (http://clms.learningcentrum.nl/index.php)
then the users ok
then contact the user to the course, the images diaspear again
![filemanager-2](https://cloud.githubusercontent.com/assets/26379170/24995396/f636ee16-202e-11e7-850b-e98e33d74fd5.jpg)
![filemager-1](https://cloud.githubusercontent.com/assets/26379170/24995395/f634e242-202e-11e7-90c6-6527fad2df27.jpg)
![filemanager chaminlo](https://cloud.githubusercontent.com/assets/26379170/24995397/f63cabd0-202e-11e7-8ea7-05c1fb763a38.jpg)

**Comment by ywarnier** [comment]
This is an issue we cannot reproduce. It is likely to be very dependent on the configuration of your server. If you require professional support to fix that, please contact providers@chamilo.org, but our community effort is unlikely to be able to check this on free time.

**Comment by learningcentrum** [comment]
Thanks Ywarnier, we try to find it, We wil put chamilo on a other server :)

**Comment by codeking2003** [comment]
Hello, Mayby I fount the problem, I use Filzilla, this is a other user (me als platformmanager) and chamilo
how can I use my chamilo user acc. als filezilla user

**Comment by ywarnier** [comment]
Hi @codeking2003,

Chamilo will, by default, use the web server's defined user.
If you have your own server, you can find the default user for the web server (if Apache) as a value given to APACHE_RUN_USER in the /etc/apache2/ (or /etc/httpd/) folder.
```
cd /etc/apache2/
grep -r APACHE_RUN_USER
```
This user is generally not authorized to do much else than just running the web server processes, so I'm not sure you can give it a password or even connect in FTP/SFTP with it (you mentioned FileZilla, so I guess you're using FTP or SFTP).

I don't recommend to upload files through FTP/SFTP, because although the file browser might find them, most files uploaded in Chamilo also have a register in the database, which they will not have if you upload them through (S)FTP.

If, for some reason, uploading them that way is the only solution for you, then make sure the files and folders are all readable and writeable by the www-data user. I won't enter into how to do this This is Linux servers admin (light) stuff, but if you do that, your thumbnails should be visible.

**Comment by learningcentrum** [comment]
Thanks, I will look and test it

greetings
Martin (codeking is my son :) )

**Comment by learningcentrum** [comment]
Hallo Yannick Warnier
I have strong rights problem
I had Chamilo on Sentora webserverpanel with php 5,4, Ubunto 14,
 I chance server and panel, new server on Vesta cp withs php 7 on Ubuntu 16
on Sentora I have the problems with the images, now on Vesta I have also
problems with te images, now I can see them in the file-manager, but not in
the browser, the don't show them
the images in the user map are show, not in course map

http://lms.learningcentrum.nl/main/inc/ajax/course_home.ajax.php?code=VERKOOPTRAINING&a=show_course_information
je must see 2 images 1 from the user image map and 1 from te course map 

I do'n get it what happening, all the rights in de map app 775
are in the database security fields ? or hidden rights ?

In some course I cannot chance the intro tex, I can edit it, but it will not
save it

greetings
Martin Doornbos


Op 09/09/2017 om 15:20 uur schreef Yannick Warnier <notifications@github.com>:
Hi @codeking2003,
Chamilo will, by default, use the web server's defined user.
If you have your own server, you can find the default user for the web server
(if Apache) as a value given to APACHE_RUN_USER in the /etc/apache2/ (or
/etc/httpd/) folder.
cd /etc/apache2/
grep -r APACHE_RUN_USER

This user is generally not authorized to do much else than just running the
web server processes, so I'm not sure you can give it a password or even
connect in FTP/SFTP with it (you mentioned FileZilla, so I guess you're using
FTP or SFTP).
I don't recommend to upload files through FTP/SFTP, because although the file
browser might find them, most files uploaded in Chamilo also have a register
in the database, which they will not have if you upload them through (S)FTP.
If, for some reason, uploading them that way is the only solution for you,
then make sure the files and folders are all readable and writeable by the
www-data user. I won't enter into how to do this This is Linux servers admin
(light) stuff, but if you do that, your thumbnails should be visible.

**Comment by ywarnier** [comment]
Hi @learningcentrum,
Sadly, we cannot look into permissions issues (nor other server-side issues, which are usually due to use manipulation rather than Chamilo issues) for our community as a community. This seriously reduces the time we can spend on improving Chamilo.
The community looks into Chamilo issues, not to how users deal with their own installation of Chamilo. We did that in the past and it almost destroyed the fragile balance of our volunteer contributors.
There are official providers who provide this kind of services and (with the resulting budget) can contribute back to Chamilo, feeding the virtuous cycle of improving this piece of free software.

**Comment by codeking2003** [comment]
Hallo Yannick Warnier
we denken dat de problemen met de plaatjes e.d komt door gebruikers rechten
komt
we zijn nu alle aanpassingen aan het doorvoeren voor dat we het opnieuw
installeren
we hebben buycouses vertaald, hierbij de vertaling, mag door anderen gebruikt
worden

we gaan later proberen een ideal module te maken, (ik ben niet zo goede
programmeur)

groeten
Martin & Marco Doornbos


Op 12/09/2017 om 14:59 uur schreef Yannick Warnier <notifications@github.com>:
Hi @learningcentrum,
Sadly, we cannot look into permissions issues (nor other server-side issues,
which are usually due to use manipulation rather than Chamilo issues) for our
community as a community. This seriously reduces the time we can spend on
improving Chamilo.
The community looks into Chamilo issues, not to how users deal with their own
installation of Chamilo. We did that in the past and it almost destroyed the
fragile balance of our volunteer contributors.
There are official providers who provide this kind of services and (with the
resulting budget) can contribute back to Chamilo, feeding the virtuous cycle
of improving this piece of free software.

**Comment by learningcentrum** [comment]
Hallo Yannick Warnier
we denken dat de problemen met de plaatjes e.d komt door gebruikers rechten komt
we zijn nu alle aanpassingen aan het doorvoeren voor dat we het opnieuw installeren
we hebben buycouses vertaald, hierbij de vertaling, mag door anderen gebruikt worden
 
we gaan later proberen een ideal module te maken, (ik ben niet zo goede programmeur)
 
groeten
Martin & Marco Doornbos

**Comment by ywarnier** [comment]
@learningcentrum Goed, laat me kunnen hoe gaat het.

**Comment by jderriks** [comment]
Hi Yannick, how many active Chamilo sites are registered in the Netherlands and is it going up?

**Comment by learningcentrum** [comment]
We solve the problem, it its a rights problem if you use a fle manger as fillezilla, the make de map to the filezilla user. We have make al our changes before installing, we translate all the 8000 codes on the English Lang file. its working now

**Comment by learningcentrum** [comment]
How can I make a map for all the docenten

**Comment by ywarnier** [comment]
@jderriks it is difficult to know because the only information we track that might help us know that is the IP of the server and the default language of the portal. Many servers being hosted in the USA or Asia independent of the location of the users, that usually doesn't help. The main language being Dutch doesn't usually help much either, as we could get stuff from South Africa and the Netherland Antilles, stuff like that (we don't have a variation of Dutch for Boer).
At the moment I count 63 portals with a ".nl" extension (which is not a good point either), more than 50% of them having less than 10 users or so.
Based on the fact that I have no real way of pointing out where Chamilo portals are really used (I would need to get the IP address of the *users* to do that, which would be against our values), I have no way of giving a reliable growth indicator either. Sorry.

**Comment by learningcentrum** [comment]
Maybe we must start a Dutch user group, my adses post@learningcentrum.nl http://lms.learningcentrum.nl/main/admin/index.php

**Comment by ywarnier** [comment]
We have not been able to reproduce this issue with proper permissions settings. I'm assuming this has been solved outside of the Chamilo code, and as such this issue can be considered closed. Please don't hesitate to re-open if you have more data or a clear procedure to reproduce on a fresh system.
