### ISSUE TITLE
Course catalog doesn't render correctly (2.0)

### ISSUE THREAD

**Issue by sjcqs** [chamilo/chamilo-lms#1886]
### Current behavior / Resultado actual / Résultat actuel
![image](https://cloud.githubusercontent.com/assets/19304198/25477928/7e67b0fc-2b3f-11e7-876a-614f0a317d77.png)

### Expected behavior / Resultado esperado / Résultat attendu
Images should be session_default.png (doesn't exists, maybe svg/session.svg ? ).
Teacher name are white on white and not positionned correctly.
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Create courses and click on courses catalog.
### Chamilo Version / Versión de Chamilo / Version de Chamilo
2.0

**Comment by aragonc** [comment]
Seen in version 1.11.x and everything is going well

![cata](https://cloud.githubusercontent.com/assets/2940509/25491286/22e56544-2b35-11e7-9737-d491394b4ce5.png)

**Comment by SatyanJ** [comment]
@aragonc It was for 2.0, should have put it in title. 
I guess, I wasn't smart to put 2.0 issues the day after 1.11.2 release which brought some more urgent issues.

**Comment by aragonc** [comment]
Version 2.0 is in development and for its output is still very far, by the time the stable Chamilo is 1.11.x

**Comment by ywarnier** [comment]
It's actually OK. After the release of 1.11.2 we were pretty focused on working on 2.0, but we had to refocus on 1.11.4 because of a series of customer requests that couldn't wait for 6-9 months it would have taken us for 2.0. Sadly, we're not big enough to have two different teams working on these 2 projects separately (which is good in a certain way as we don't go too far between the two)

**Comment by SatyanJ** [comment]
This bug is still present is 2.0. A PR is coming.
