### ISSUE TITLE
Backup/Copy Course do not bring Scorm Packages

### ISSUE THREAD

**Issue by suppiger** [chamilo/chamilo-lms#1913]
Hello guys, when I try to copy a course using the "Backup Tool" and paste it into another, the scorm packages get lost and i can't use it; I'm using it in portuguese but the message it returns is like "The file is missing".

I want to know how can I fix it. 

My version is actually 1.10.2

**Comment by ywarnier** [comment]
Hi @suppiger, our community is a little too small to maintain many versions at the same time. If you want a fix for 1.10.2, you should contact the official Chamilo providers: https://chamilo.org/providers.
Otherwise please update to the latest stable (1.11.2) or wait for the new stable in a few weeks (1.11.4) and let us know if this still fails.
It should be noted, however, that SCORM content in general is a bit more complex (all files of a SCORM package are not managed by the database, so the course copy cannot see them) and the safest procedure would be to re-import the content manually after the course copy for the rest of the content.
