### ISSUE TITLE
Problem with sound

### ISSUE THREAD

**Issue by AurelieGuy** [chamilo/chamilo-lms#1960]
Hi everyone!

### Current behavior / Resultado actual / Résultat actuel

When anyone open the course and follow it on Chrome, the sound is out of synchronization. 
On the first page, the sound readed is the sound of page 1. When you click on page 2 (or the arrow), still the sound of page 1 which is readed with page 2 on the screen. You have to click again to have the good sound.

It's okay on firefox and on edge.

### Expected behavior / Resultado esperado / Résultat attendu

Right sound in the right place on Chrome.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Create or import a course and follow it on chrome.

### Chamilo Version / Versión de Chamilo / Version de Chamilo

Last one : 1.11.2.

Thank you a lot for helping me.

**Comment by ywarnier** [comment]
Hi @AurelieGuy, you seem to be talking about an issue on your own portal. There are too many variables for us to help you there. You might want to contact one (or several) official providers here: https://chamilo.org/providers to look at your specific problem.

Chamilo doesn't "manage" sound itself. We use external libraries to offer sound readers that work very well in all cases we have tested. Sound delay might be due to a very high-quality sound which takes a long time to download, or to a very low bandwidth. In any case, this is out of the score of Chamilo code. You should only report here issues that could affect the Chamilo software and its community at large. Thanks.
