### ISSUE TITLE
Trainer view when previewing pages

### ISSUE THREAD

**Issue by ConsultPW** [chamilo/chamilo-lms#2002]
### Current behavior / Resultado actual / Résultat actuel
When previewing a page, the button to switch back to trainer view is missing.

### Expected behavior / Resultado esperado / Résultat attendu
Button should appear to allow switching back to trainer view

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Create a learning path and add a page.
Preview the page and return to trainer view does not appear.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

Apologies if this is an obvious fix - spent a couple of days checking all features so may have brain freeze!

**Comment by ywarnier** [comment]
@ConsultPW we removed the switch back in the preview page in the learning path because it introduced a loophole whereby the edition of a base-course learning path from a session context was made possible, with no obvious way to avoid it.
To get back to teacher view, get back to the learning paths list and use the "switch to teacher view" button.
