### ISSUE TITLE
Experimenting upgrade from 1.9.8 to 1.11.4 : Loosing old campus name and information

### ISSUE THREAD

**Issue by vfremaux** [chamilo/chamilo-lms#2019]
### Current behavior / Resultado actual / Résultat actuel
Used the following process : 
- Deploy new code base for 1.11.4 aside old codebase
- Run the installer from main/install/index.php
- Follow steps and ask for upgrading from an old instance
- Changed the "old code" directory on request to point 1.9.8
- Follow upgrade steps 

As a result : 
- upgrade forces "default primary install" information to be input
- upgrade changes site information with defaults and looses old information

### Expected behavior / Resultado esperado / Résultat attendu
Upgrade with no data loss

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
see above

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by ywarnier** [comment]
Hi @vfremaux, thanks for reporting. We will try to have a look at that as soon as a window of opportunity opens to setup the whole context to try it out (not really soon as far as I can see, though). This 1.9 installation is based on a normal Chamilo install, or on the vchamilo plugin?

**Comment by ywarnier** [comment]
Yes to the previous comment, and use the latest stable minor version of each major version: 1.9.8 -> 1.10.8 -> 1.11.8, otherwise you might not benefit from some fixes caught in previous versions.
The case reported above is with the use of the vChamilo plugin, which is quite a complex, structure-changing plugin. Not much to do with a classical 1.9.8. Please also read the installation guide fully to avoid any surprise (https://11.chamilo.org/documentation/installation_guide.html, https://10.chamilo.org/documentation/installation_guide.html). In particular, if this is a very large portal, make sure you watch the web server's error log for any error message.

**Comment by AndrewHobson** [comment]
I have a question : Say your installation is in version 1.10.0. Does it make any sense to upgrade it to the latest minor release 1.10.8 prior to migrating to a "new stage" version 1.11.8 ? Or is it a waste of time ? If your goal is to simply go to the latest version.

**Comment by opensourcecompany** [comment]
Since the database schema can be updated with doctrine, it should allow a direct upgrade process. But as Yannick has already explained: backup, backup, backup... if something goes wrong, fix the error, start the upgrade process again.

**Comment by ywarnier** [comment]
Hi @AndrewHobson: the upgrade "process" only ever does something when moving from major version to major version, so there's no impact at all in *not* upgrading to 1.10.8 in the middle. What counts is the major to major: 1.10.0 to 1.11.0. The rest is only files getting overwritten. You can learn more about this here: https://github.com/chamilo/chamilo-lms/wiki/Release-cycle (if you want to know)
