### ISSUE TITLE
Import backup: assignements

### ISSUE THREAD

**Issue by p4pr8n** [chamilo/chamilo-lms#2115]
### Current behavior / Resultado actual / Résultat actuel
In 1.11.4 version Assignements are not imported.
Assignements are visible in selection. Import seems to be ok but assignements are not present in the course.
Same result with a full or a selected backup and/or restore.
It works in 1.11.2.

Thanks

**Comment by p4pr8n** [comment]
For this issue as proposed in https://github.com/chamilo/chamilo-lms/issues/2165 I've tried a fresh import on 11.chamilo.org and assignements where present. Where could I find the patch ?
Thanks

**Comment by opoherrera09** [comment]
I am experiencing the same issue on 1.11.4. I can copy the course and/or create a full backup, but the Assignments are not being duplicated.
Even if you select the learning objects (Assignments in this case), Chamilo will allow you to choose the Assignments but will crash when you press Validate.
Any suggestions?

**Comment by ywarnier** [comment]
Hi @p4pr8n, 1.11.6 will be out soon and includes the patch. I don't know exactly what did fix it, which is why I'm not pointing you directly to the patch. It might have been a series of patches, and we've already given 6 months of hard work on 1.11.6, so stay tuned. I believe we should be able to publish next week!
