### ISSUE TITLE
version check down

### ISSUE THREAD

**Issue by lonesomewalker** [chamilo/chamilo-lms#2131]
Actually from the backend:

Chamilo HTTP/1.1 404 Not Found Server: nginx/1.6.2 Date: Thu, 07 Sep 2017 08:31:53 GMT Content-Type: text/html Content-Length: 168 Connection: keep-alive
404 Not Found
nginx/1.6.2

Can we find a better solution for this?
For example there could be 3 or more servers which can get contacted, so if one gets down, we have still 2 more?

**Comment by jmontoyaa** [comment]
Maybe this will fix this issue:

https://github.com/chamilo/chamilo-lms/commit/f4e4da2cbf6bbfcc0c538310874d633cc642dac3

**Comment by ywarnier** [comment]
No answer since almost 3 months. Closing.
The Chamilo Association does not have the resources at the moment invest on setting up and maintaining a cluster to answer that call. Hopefully that will change in the future. In the meantime, I believe the issue at hand here was more due to an issue in the code than in the server availability. The server getting the version calls is the same as the one serving campus.chamilo.org, so if one is down, the other one should be.
Around September, we changed from PHP5 to PHP7 on the server, which might have triggered that issue.
