### ISSUE TITLE
Recommend MySQL 5.6+

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#2140]
In the documentation here:

https://11.chamilo.org/documentation/installation_guide.html#1._Pre-requisites

It says that MySQL version should be 5.1 or more but this version is not longer maintain.

**Comment by lonesomewalker** [comment]
5.5 is also EOL since July 2016.
5.6 has Security fixes till 31 Dec 2018.

**Comment by jmontoyaa** [comment]
Thanks @lonesomewalker  I just updated the title.

**Comment by ywarnier** [comment]
OK to recommend 5.6 (I would rather/also recommend MariaDB 10 than MySQL 5.6 given the recent events with Solaris), but minimum *requirement* should still remain at MySQL 5.1, unless you don't manage to fix your Doctrine issue for Aix... :-p

**Comment by jmontoyaa** [comment]
@ywarnier https://docs.chamilo.org/en/ will have technical (install/upgrade/etc) documentation?

**Comment by jmontoyaa** [comment]
This task is related to #2139

**Comment by ywarnier** [comment]
@jmontoyaa https://docs.chamilo.org/ has some installation documentation (which complements the installation_guide.html) and a developer guide (at the very end), which contains information about the structure, but none of these replaces the installation guide and the dependencies indicated there.
It is necessary to have the installation_guide shipped with the code because users might need to install it unplugged.
