### ISSUE TITLE
Unable to go to next Question in test

### ISSUE THREAD

**Issue by lmanyonho** [chamilo/chamilo-lms#2150]
### Chamilo Version / Versión de Chamilo / Version de Chamilo

I have installed Chamilo in a freshly installed Ubuntu 16.04 server and the only Chamilo dependent that is missing is xapian otherwise the rest were met. No when I create a new multiple choice question test I cannot proceed to next question, it hangs on clicking the submit question button.

**Comment by ywarnier** [comment]
Xapian is not in a working state at the moment, but it doesn't have anything to do, unless you enabled the "fulltext indexing" options in the platform settings... did you?
In any case, when you have an issue like that, it is helpful to look at the error logs of Apache and provide us with the error messages, otherwise we can do almost nothing to help.

**Comment by ywarnier** [comment]
And we need the version of Chamilo you are using - please refer to the DOCUMENTATION in the "contributing" link when you click on "New issue". Please respect our time spent helping you out and provide us with the necessary information in the suggested issue format, otherwise we will have no choice but to ignore your reports.

**Comment by leninkster** [comment]
I also have the same problem.  New install of Chamilo 1.11.06 on Centos 6.9 using PHP 5.6 and MySQL 5.6.37.

I have a test inside of a course.  Randomised 10 questions out of 739.  First question is answered and then the wait icon just spins.

![chamilo-test-hangs](https://user-images.githubusercontent.com/9325780/30977268-0b108eec-a445-11e7-968a-6ae8a2794cac.jpg)
