### ISSUE TITLE
Scorm does not load properly

### ISSUE THREAD

**Issue by xam1234** [chamilo/chamilo-lms#2158]
### Current behavior / Resultado actual / Résultat actuel
We have created a test scorm (versions 2004 and 1.2) that have 5 pages.
Only 3/5 pages are loading, page 4 does have a mp4 movie and on page 5 is a picture.
### Expected behavior / Resultado esperado / Résultat attendu
All pages should load
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Create a course
import SCORM "test_scorm_1.2.zip"
start scorm->go to page 4 and 5
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.10.6 / 1.11.x ( 25.09.2017 ) (11.chamilo.org)
Scorm works without a problem on old Dokeos 1.8.6.1 and Dokeos 2.0
[test_scorm_1.2.zip](https://github.com/chamilo/chamilo-lms/files/1328593/test_scorm_1.2.zip)

**Comment by marshel** [comment]
@xam1234 - I did download and then uploaded on my production 1.11.4. And confirm your results.

But it seems to me that is a SCORM error since is a javascript based function and probably made by hand. 
I'm not an expert on SCORM data, but I use Articulate/Captivate and never got something like this.

On some updates I'd had to make behind the scenes uploading on FTP, I needed to change some manifests, and I Realised that progress and its record on DB is affected, even if just one line or one ID is wrong.

**Comment by xam1234** [comment]
Scorm was made by Xerte.
Everything is working fine on old Dokeos platforms, so thats strange for me.

Any chance for a good free tool to create SCORMs for Chamilo ?

**Comment by ywarnier** [comment]
All free tools to create SCORM for Chamilo should work with SCORM 1.2. We will review your bug report soon. Thanks for sharing the scorm with the issue.
We have received several reports over the last few months that the learning paths (SCORM viewer) were quite slow. Maybe the video and audio are just lagging and that's why the SCORM doesn't work?
As a portal administrator, in your learning paths list, you can enable a debug option that then shows all the SCORM messages in your browser's JavaScript console. Maybe you are able to try that and get a little further in your observations (until we have some time to review it ourselves)?

**Comment by xam1234** [comment]
@ywarnier - Your right, SCORMs accuatly works slower than in the old Dokeos platforms that I have (1.8.6.1 , 2.0).
Video is not lagging, the pages are just not loadnig, you can see tha when you change page above 3, the number is still 3/5.
Another thing is that when you change the view mode to: fullscreen, it works.
In Impress mode it shows few API errors, but it also works.

**Comment by ywarnier** [comment]
@xam1234 Could you try to add an index on c_lp.id and c_lp_item.id and report if there is a substantial change in speed?

**Comment by xam1234** [comment]
@ywarnier Sorry, I don't have enough skills to work on this.
Still, the main problem is that the scorm is not working correct in the embedded mode.

**Comment by ywarnier** [comment]
The speed issues should be much improved on a fresh 1.11.6 version now.
The embedded mode might still be an issue, but this type of issues should really go through a support contract with one of our providers, because it is really a pain in the ... to work on (nobody wants to do SCORM compatibility work on their free time). I'm closing this task as the affected use cases seem to be relatively few.
