### ISSUE TITLE
Course category in quiz is not hidden

### ISSUE THREAD

**Issue by xam1234** [chamilo/chamilo-lms#2160]
### Current behavior / Resultado actual / Résultat actuel
When you hide course category in quiz it is still visible when you start it.
### Expected behavior / Resultado esperado / Résultat attendu
Course category should be hidden when you disable it in quiz properties.
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Create test quiz
Set Display questions category to: No
Create 3 categories
Create random 3 questions and add them to 3 diffrent categories
Start quiz
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.10.6 / 1.11.x.26.09.2017 (11.chamilo.org)

**Comment by ywarnier** [comment]
This is not *really* a bug, in the sense you are only seeing this because you are *not* a student.

https://github.com/chamilo/chamilo-lms/blob/ae3178880359b8fc2aa50c4067a853f6390e8023/main/exercise/TestCategory.php#L635

The !$is_student there is what should be complemented with an api_is_student_view_active() to make sure that, even in student view, you are *not*seeing the category if the option was selected.

I tried it with 
```
            ($in_display_category_name == 1 || (!$is_student && api_is_student_view_active()))
```
and it seems it works, but it has to be checked because the condition is a bit complex.

**Comment by xam1234** [comment]
It works ok for me.

**Comment by AngelFQC** [comment]
I sent a commit only to improve the code redability for this part od code

**Comment by jmontoyaa** [comment]
Please don't forget to add it to master too.

**Comment by NicoDucou** [comment]
Tested on last github version and all is correct now. It is included in master aswell so I close this issue.
