### ISSUE TITLE
- New profile pictures of users turn randomly after upload.

### ISSUE THREAD

**Issue by Morepizza1** [chamilo/chamilo-lms#2168]
Situation:
upgrade from chamilo 1.9.10.4 to chamilo 1.11.4 / upgrade from php 5.6 to 7.1
### Current behavior / Resultado actual / Résultat actuel
- New profile pictures of users turn randomly after upload.
### Expected behavior / Resultado esperado / Résultat attendu
no turning of picture
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by jderriks** [comment]
Google "profile picture turned sideways":

The problem here is that the camera puts the picture in one direction,  but the rotation setting of the picture is a different direction.
There is a setting in most camera apps to adjust this.
The easiest way to fix this now is to upload it to Google photos, Google will fix by aligning the meta data. Now save a local copy.
Another way is to load the picture into an editing program, or an online editing site.

**Comment by ywarnier** [comment]
Thanks for helping out @jderriks! I wouldn't have guessed that we were talking about a non-Chamilo issue.

**Comment by jderriks** [comment]
Well... you can always turn any non-Chamilo-issue into a Chamilo feature request of course.

Chamilo could read the exif meta-data in the uploaded picture to rotate it for the user during storage or when shown on the screen. This is described in this link:
https://www.go4expert.com/articles/reading-exif-data-images-php-t29367/
So it is not a bug, it is a non-existing feature.

**Comment by ywarnier** [comment]
Yes, sure, but I'm kind of not into accepting feature requests that I don't think will ever be implemented. But fair enough, if @Morepizza1 believes this is worth it and that he might be likely to produce a pull request with the code needed, I'm happy to re-open.
