### ISSUE TITLE
E-mail alert templates seem to be broken

### ISSUE THREAD

**Issue by lonesomewalker** [chamilo/chamilo-lms#2178]
### Current behavior / Resultado actual / Résultat actuel
When activating E-mail alerts templates, they are not sent as expected.

### Expected behavior / Resultado esperado / Résultat attendu
Setting up custom email templates, in example for registration confirmation.
System populates the template with given system variables.
System uses email settings from config to send them by smtp/mail/whatever.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Login at 11.chamilo.org.
Administration -> "Portal" Event message management

First you get :
Notice: Undefined variable: action_links in /var/www/11.chamilo.org/www/main/admin/event_controller.php on line 65
Notice: Undefined variable: tool_name in /var/www/11.chamilo.org/www/main/admin/event_controller.php on line 72
Notice: Undefined variable: message in /var/www/11.chamilo.org/www/main/admin/event_controller.php on line 73

Then you can see there are missing translations.
Also the email templates are not used.

Running this in an actual 1.11.4 Chamilo installation, also not working.

**Comment by lonesomewalker** [comment]
Error log says:
stderr: PHP message: EventsDispatcher warning : user_registration_event_send_mail_filter_func does not exist., referer: /main/admin/user_add.php

**Comment by ywarnier** [comment]
I don't think this feature is working. The last time we did something notable there was in 2012: https://github.com/chamilo/chamilo-lms/commits/1.11.x/main/admin/event_controller.php

This report is valid, although I think you're the only one to have tried to use it in 5 years time. I believe we inherited that from the team at cblue. Not sure there is anything planned as there are other efforts in parallel to personalize e-mails.

Instead of using this feature (which we should probably remove completely for 2.0), you could define a copy template (cp main/template/default main/template/lonesomewalker; edit configuration.php to change default_template to 'lonesomewalker'), move your portal in dev mode for the testing period to avoid caching, then edit the mails in the `mail/` subfolder.
From 1.11.6, you'll just need the file itself (not a copy of all other files).
Please note that using templates involves additional maintenance work when upgrading versions.

**Comment by ywarnier** [comment]
Yeah, after reviewing this, I can confirm that this is not maintained anymore. We hoped for the original developers to maintain it, but they didn't.

Scheduled for removal (requires database change, which can only be applied between major versions, so not before 2.0).

**Comment by jmontoyaa** [comment]
Agree, I added "deprecated"
