### ISSUE TITLE
Oral question does not record

### ISSUE THREAD

**Issue by annickvdp** [chamilo/chamilo-lms#2223]
### Current behavior / Resultado actual / Résultat actuel
The recording does not work in IE, Edge and Firefox (it works in Chrome), it shows an empty recording in Firefox, an error in Edge and no recording button in IE
### Expected behavior / Resultado esperado / Résultat attendu
to be able to record 
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
record audio for an oral question
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4 (https://11.chamilo.org/)

**Comment by ywarnier** [comment]
I think @AngelFQC just worked on this last week. @annickvdp Maybe you could try again on 11.chamilo.org and let us know if that's still an issue?

**Comment by annickvdp** [comment]
It works in Firefox and Edge, but not in IE (record button does not appear). 
@AngelFQC, can you let me know what you changed, so I can implement in our own installation? Thanks!

**Comment by ywarnier** [comment]
That is because WebRTC is not supported in IE https://caniuse.com/#search=webrtc
We cannot do anything about that except return to the iron age and use Flash. We don't want to do that. Please have your users change to an Open Source browser that cares :-)
This part we won't fix, so I'm closing the issue. Feel free to open one *only* for IE, so I can give a specific official answer in the name of the Chamilo project and we can use it for later reference (if you have a need for that).

**Comment by annickvdp** [comment]
Thanks, no need for a fix in IE ;-)
