### ISSUE TITLE
Error when saving plugins page

### ISSUE THREAD

**Issue by Alphabc** [chamilo/chamilo-lms#2262]
Hi,

After having unchecked "jcapture" plugin (that doesn't work on Chrome nor on Firefox, and that cannot be configured), I find this error, as if the system tried to install already checked plugins...
![image](https://user-images.githubusercontent.com/24738945/34281300-0d317b80-e6be-11e7-8931-0d9a1cd5fbaf.png)

Thus being unabled to unactivate jcapture

Last version of chamilo, with multiple access url enabled

Thx

**Comment by ywarnier** [comment]
It feels like this is based on a Git version, not the latest *stable* version. Is that the case?

**Comment by jmontoyaa** [comment]
This was already fixed in 1.11.x.

**Comment by Alphabc** [comment]
Hi,
Installation done through this 1st line ;)
wget https://github.com/chamilo/chamilo-lms/releases/download/v1.11.4/chamilo-lms-1.11.4.tar.gz

Thx for your prompts replies...

**Comment by ywarnier** [comment]
Hi @Alphabc, yes, sorry, it seems that this issue has already been fixed in what is going to be released in a few days as 1.11.6. Please note that the error that appears (sfu_post already exists) suggests that the installation of the "Student Follow-up System" (SFS) went well a first time but the uninstall didn't work properly, which, as @jmontoyaa says, was an issue that has been fixed. If you don't mind about the SFS, you could drop all sfu_* tables in your database and load the plugins page again (avoiding the installation of the SFS plugin again).
