### ISSUE TITLE
Course search by session is not working

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#2306]
In the admin course list https://11.chamilo.org/main/admin/course_list.php? 
In the field in between "Search courses" and "Advanced search" where it says "Please select an option" When entering the beginning of the name of a session (for example typing nico), the complete name of the session appears (nicodusession) and I can select it. But once selected nothing happens.

I also tried once selected to lunch a search with the "Search courses" but it is not using the session name filter neither. So I don't know what this session search field should do but at the moment it is doing nothing.

![chamilo 1 11 x 10 01 2018 13 34 gmt 2 validation portal course list](https://user-images.githubusercontent.com/6579268/34774495-8b76c5d0-f5dd-11e7-8a7e-0324ba12899b.png)

**Comment by ywarnier** [comment]
Seems to be related to this

https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/admin/course_list.php#L481

**Comment by ywarnier** [comment]
OK, so the issue here seems to be that the use of the select2 lib changes the id of the element, and that line 481 sets an event onChange for the element with id session_name, but that ID doesn't exist anymore, and it seems like even if you replace it with the generated id (select2-course_filter_session_name-container) it doesn't find its value.
I don't know how that lib is supposed to work, so I'll leave it to you @jmontoyaa

**Comment by ywarnier** [comment]
The same issue probably happens in the sessions list, to search by course

**Comment by NicoDucou** [comment]
It is all good to me for this task, it works fine now, so I close it.
