### ISSUE TITLE
Use gettext to handle translations 

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#2323]
Use gettext in chamilo:
Steps:
1. Use translation symfony component when calling "get_lang" function
2. Replace all get_lang values with their English value:  #2346 

Origin:

`get_lang('UserMustHaveTheDrhRole') `

Should be replaced to:

`get_lang('Users must have the HR director role') `

3. Delete old translations in  https://crowdin.com/project/chamilo-lms
4. Move translation manager from translate.chamilo.org to https://crowdin.com/

Symfony docs:

http://symfony.com/doc/current/translation.html#translation-configuration

**Comment by jmontoyaa** [comment]
We can also profit of this task to rename "get_lang()" to  "trans()" as in Symfony. @ywarnier ?

**Comment by jmontoyaa** [comment]
We need a platform @ywarnier

**Comment by ywarnier** [comment]
So far, platforms analyzed:
| platform | observations | conclusion |
|---|---|---|
| Pootle | installation process broken for months. Dev in Python. Self-hosted for our case (so not communitarized translations and additional maintenance work) | disqualified |
| Pontoon | Does not seem to be thought for external projects (mostly Mozilla's internal system). Self-hosted in our case (so not communitarized translations and additional maintenance work) | disqualified |
| Crowdin | although proprietary solution, offers the features we need and communitarizes translations. Free for Open Source but *very* expensive otherwise. Borderline case with Chamilo's official providers about commercial products | pending |
| Transifex | Similar to Crowdin, also with a borderline case for non commercialization | pending |
| Lingohub | Free for Open Source plan is limited to 100 users. We already have about 800 on translate.chamilo.org | disqualified |
| Launchpad | Offers gettext support, communitarized translations, is free and used for Open Source projects without limits. Its interface is a bit hard on the users. I'm not sure what is the strings export process like | pending |

**Comment by ywarnier** [comment]
I have generated a new script for the export to gettext, and made an import test on Launchpad: https://translations.launchpad.net/chamilo-lms/+imports
At the moment the files are still under review. If it works, then I think even with the somewhat complex interface we should use this one, simply because it goes much more with the overall ideology of our project.

**Comment by ywarnier** [comment]
In the meantime, @jmontoyaa maybe you can already try with the generated files? Just remove the die() from generate_gettext_files.php and execute, and it will put them in /tmp/gettext

**Comment by ywarnier** [comment]
For some reason I seem to have lost the changes that limited the strings to 120 characters. Let's see if it's possible to deal with them "as is".

**Comment by jmontoyaa** [comment]
This is the gettext result, it works well ...

[gettext.zip](https://github.com/chamilo/chamilo-lms/files/2556420/gettext.zip)

**Comment by jmontoyaa** [comment]
> In the meantime, @jmontoyaa maybe you can already try with the generated files? Just remove the die() from generate_gettext_files.php and execute, and it will put them in /tmp/gettext
> 
> And also... execute the other script in the same directory (see #2346) to convert the whole Chamilo to gettext in a separate branch, maybe...

First I will need to update 2.x with 1.x changes ...

**Comment by ywarnier** [comment]
A little report on progress with the import to Launchpad.
I had to make a few modifications to the gettext converter here: e004777d3a705f42ad7c90c0eb55a7d809fa5900

These are the issues I found along the way:
 - you have to generate a main.pot (or whatever name you want) and an en.po as a minimum. These two files are exactly the same.
 - you have to place those files into a directory of the same name as the .pot file (main/) and .tar.gz that directory under the same name (main.tar.gz)
 - then you can upload the file at https://translations.launchpad.net/chamilo-lms/trunk/+translations-upload, but the file itself cannot be too big otherwise the untar process (not the upload) will fail on a "max time exceeded" error. This means that you might have to reduce the number of files you send each time. For me, sending main.pot + 5 of the largest language files .po made the trick, but this is a boring process
 - once this is done, files will appear in https://translations.launchpad.net/chamilo-lms/trunk/+imports as "Pending review"
 - you do *not* have to wait for someone to review your files (which is what I had initially understood by reading the docs). Instead, you can "approve" the files yourself by clicking on the pencil under the filename
 - once approved, the files will take about 3-5 minutes to get to the "imported" state. Only then will they start appearing correctly in the list of translations here: https://translations.launchpad.net/chamilo-lms

**Comment by ywarnier** [comment]
There are also a series of problems with the parsing because Gettext is stricter than what we have, and there are several badly translated terms, like \n\n becoming \ N \ N :-)
I found this table to be useful: https://en.wikipedia.org/wiki/ISO_639:s

**Comment by ywarnier** [comment]
It's starting to look nice (even though not all files have been parsed yet) at https://translations.launchpad.net/chamilo-lms
![translations](https://user-images.githubusercontent.com/609839/48571664-7b5a6580-e8d5-11e8-9c19-cae9e56627fa.png)

**Comment by ywarnier** [comment]
I get relatively frequent errors on Launchpad. I just refresh and it works, but still...
![launchpad-error](https://user-images.githubusercontent.com/609839/48577045-1d814a00-e8e4-11e8-8488-c0273462c0d6.png)

**Comment by ywarnier** [comment]
This is what Launchpad generates for the translation export, so basically all files are named "main-[lang].po", where lang is either a 2 letters code or a "ab_CD" letters code (like "en_GB", etc)
[launchpad-export.tar.gz](https://github.com/chamilo/chamilo-lms/files/2586871/launchpad-export.tar.gz)

To download, go on the homepage and click the "download" link hidden in the text on the right part (second block from the top): https://translations.launchpad.net/chamilo-lms/trunk

**Comment by ywarnier** [comment]
OK, @jmontoyaa I consider my part done here.
If you can put those files in use as Gettext in the master branch, then we'll just work this way from now on and figure out how to reproduce new terms added to translate.chamilo.org in Launchpad.
Can you check if this import works and if you can use the "main-fr.po" filename format for the files?

**Comment by jmontoyaa** [comment]
Well I click to download the english uk translation ... And I had this message 

"Your request has been received. Expect to receive an email shortly."

:disappointed:

**Comment by jmontoyaa** [comment]
I received this message:

The translation files you requested from Launchpad are ready for
download from the following location:

 http://launchpadlibrarian.net/397806226/main_main-en_GB.po

The naming should be only "main.en_GB.po"

**Comment by ywarnier** [comment]
If you download them all at once, the naming is correct... It will then put them in a directory "main"

**Comment by ywarnier** [comment]
I know the process with the e-mail is a bit boring, but on translate.chamilo.org you had to wait 3 minutes to get the files generated anyway, so I don't see a big difference

**Comment by jmontoyaa** [comment]
https://github.com/chamilo/chamilo-lms/commit/86c51123f980970ddf2090d8d7886ab014040131
https://github.com/chamilo/chamilo-lms/commit/7d00a09e7f705ecab0c4379ed830ea98db0b45ae

**Comment by ywarnier** [comment]
The process of importation + updates + new variables creation needs to be documented

**Comment by ywarnier** [comment]
Also, sub-languages have to be supported (the /translation folder allows for redefinition of terms)

**Comment by jmontoyaa** [comment]
Move translations into /var

**Comment by jmontoyaa** [comment]
I added all translations in po format here:

https://github.com/chamilo/chamilo-lms/tree/master/translations

**Comment by ywarnier** [comment]
Missing: language selector

**Comment by christianbeeznest** [comment]
It is added user or course language using get_lang and gettext (symfony translate) in this PR https://github.com/chamilo/chamilo-lms/pull/4451

**Comment by ywarnier** [comment]
> It is added user or course language using get_lang and gettext (symfony translate) in this PR #4451

@christianbeeznest I'm not sure what this does. I can change the languages of user and course, but the interface language does not change in reaction to that...
I have set the platform to English, my profile to French and a course to Spanish, but it all shows in English

**Comment by christianbeeznest** [comment]
Hi @ywarnier 
When you are inside a tool is using the pages with method get_lang and you can see the course language selected. The page where is using get_lang is working now. Pages with vue are not implemented language selector yet.

**Comment by ywarnier** [comment]
We have decided to use Weblate (https://github.com/WeblateOrg/weblate) at https://translation.chamilo.org. It is not yet completely configured (missing e-mail config and account creation procedure) but this allows us to now have a full workflow as developers:
- add new term to main.pot to Git master branch
- wait for it to be picked up by Weblate
- translate it
- download as zip (until we figure out how to automate that last part)

This issue can now be considered solved.
