### ISSUE TITLE
Issue with LTI plugin

### ISSUE THREAD

**Issue by jacovm** [chamilo/chamilo-lms#2378]
Hi

When trying to add an External Tool (LTI tool) to a course, the tool doesn't save and doesn't display anywhere.

I have enabled the IMS/LTI plugin in the admin section: 
![untitled](https://user-images.githubusercontent.com/24301344/36153212-2f7e2124-10d6-11e8-91b1-101e40ddce96.png)

In Regions I have selected all the options, and clicked "Enable the selected plugins": 
![image](https://user-images.githubusercontent.com/24301344/36153266-67c39424-10d6-11e8-9494-500ea80d1c71.png)

In the course Settings I see the IMS/LTI option 
![untitled](https://user-images.githubusercontent.com/24301344/36153367-af6ffe7a-10d6-11e8-8fe0-bc1ed1be3a44.png)

I enter all the LTI details, name , URL, key, secret. I can only select "none" under Type. Not sure if that is the cause of this issue?
![untitled](https://user-images.githubusercontent.com/24301344/36153121-e7ac2fda-10d5-11e8-9d7f-92f058b4a5f5.png)
But clicking on the + Add External Tool button doesn't seem to do anything?

And when I go back to my course, I don't see anywhere a link to the LTI tool I just tried to add?
![untitled](https://user-images.githubusercontent.com/24301344/36153509-2e5c7862-10d7-11e8-9d4d-db11271bf5b6.png)

I'm using a freshly installed version 1.11.4 which I downloaded from here https://chamilo.org/chamilo-lms/ and which seemed to already have the IMS/LTI in the plugin section.

Any idea what the issue may be?

Thanks

Jacov

**Comment by NicoDucou** [comment]
Hi @jacovm 
This plugin has been under development since 1.11.4 so you should try with version 1.11.6 that has been released on 18 of january.

I just did a test on the test portal 11.chamilo.org and I got a new tool integrated in the course as you can see here https://11.chamilo.org/courses/NICODU/index.php?id_session=0 with the new tool called "Mon test".

So try to update to 1.11.6 or install 1.11.6 and test again or test it on the test portal to have an example of your problem on this test platform.

Best regards

--
Nicolas

**Comment by jacovm** [comment]
Nicolas, 

Thank you for your reply. 

We upgraded our Chamilo and installed 1.11.6 so we can test.

We were able to setup the LTI tool, however it doesn't seem to launch properly. 
Looking into this, it seems Chamilo is sending over the LTI parameters via the URL's query string, not via POST (as expected according to the LTI guidelines).

Do you have any idea who we can reach out to regarding the Chamilo LTI to see what's required in order to fix this?

Thank you

Jacov

**Comment by ywarnier** [comment]
Hi @jacovm, for now this is a beta implementation by BeezNest, my company and the official editor of Chamilo (see https://chamilo.org/providers). We are not supporting it yet as a community project (so not yet documented) because it hasn't been tested enough. You can enter a commercial relationship with BeezNest for express support on that. You can also wait for the documentation to be published, but it has not been assigned a community roadmap item yet, so it is there "as is" and as much as we could test it on some specific LTI components (we did test it with the Turnitin anti-plagiarism service and it seemed to work, although no professional implementation has been done in a production environment yet).
If you do proceed on your own, we'd be pleased to have you contribute some improvements or documentation.

**Comment by jacovm** [comment]
Hi Yannick

Thank you for your reply.

Could we perhaps have a call and see what's needed to fix this? I would be happy to chat and see what's needed in order to get the Chamilo LTI fully functional and out of beta.

We also tested it with the Zoom LTI https://support.zoom.us/hc/en-us/sections/200305523-LTI-LMS-Systems and Piazza LTI https://piazza.com/product/lti, where we ran into (probably) the same issue as well. It doesn't seem to be an isolated issue with our LTI tool, Nevertheless, I'm happy to see if participating in the effort to fix this would bring a quicker resolution which can benefit the Chamilo community.

If you're available for a chat, could you please send me an email to jacov(at)cirqlive.com?

Thank you

Jacov

**Comment by AngelFQC** [comment]
Hi
I added a Piazza test in this course https://11.chamilo.org/plugin/ims_lti/start.php?id=9&cidReq=TESTLTI&id_session=0&gidReq=0&gradebook=0&origin=

**Comment by jacovm** [comment]
Thank you Angel

I'll look into this on our demo Chamilo site and will keep you posted.

Jacov

**Comment by meuhland** [comment]
I have modified the behavior to use a post instead of  the query string.
Anybody interested in me posting a PR this might solve the issue raised by @jacovm

**Comment by ywarnier** [comment]
@meuhland we are always interested in receiving and analyzing PRs to see where we can improve.

**Comment by meuhland** [comment]
Awesome @ywarnier I will probably be rolling that into TicFP because we had experienced this issue while testing LTI support, any plans you or @NicoDucou  can share with me (privately?) regarding a roadmap on this?

**Comment by ywarnier** [comment]
There is no roadmap for LTI. Everyone wants it but nobody wants to fund it, or so it seems. The current state of the package is BeezNest's investment and we are expecting users to have specific requirements that will help us develop the integration further. But as far as roadmaps go, this is not a priority for us.
Mostly, the issue we have with LTI and why it isn't part of our priorities is that is it misused as a tool to provide a connection to closed source, hidden/abused data services which offer new features to users but confuse them in thinking those services also match the Free Software philosophy. Most of them don't.

**Comment by NicoDucou** [comment]
As indicated by @jacovm here https://github.com/chamilo/chamilo-lms/issues/2592#issuecomment-510015078 the problem was fixed so I close this task
