### ISSUE TITLE
When will the 2.x version be released

### ISSUE THREAD

**Issue by hponiang** [chamilo/chamilo-lms#2464]
When will the 2.x version be released, is there a major improvement in the function of the 2.x version that is mainly the use of SF4?

**Comment by ywarnier** [comment]
Hi @hponiang, we expect version 2 to have a beta release around June, and a stable release around September or October 2018. There are a series of back-end changes that will happen in Chamilo on the way to 2.0. Some of them are Symfony4-related, others are only Chamilo internal stuff. Our integration of Symfony is progressive (because we don't have the resources to re-write the whole thing in a reasonable time frame).
Version 2.0 should come with a reasonable set of new features for end-users, but the focus for the time being is on the restructuring of a few elements that will allow full scalability in cloud environments as well as a much higher flexibility in the usage of tools in Chamilo (i.e. having the possibility to have global tools instead of just course tools, and the same for documents).
You can track the progress of 2.0 here: https://github.com/chamilo/chamilo-lms/milestone/2 and here https://github.com/chamilo/chamilo-lms/projects/3

**Comment by hponiang** [comment]
Thank you for your instant reply, I tried to use the latest code to implement, found that there are a few entity classes, this version can be used as an experiment? I am a Chinese company and would like to use this as an internal training platform for the company. Did someone do similar things? We are more demanding self-directed learning. We do not emphasize the process and results.

**Comment by ywarnier** [comment]
Hi @hponiang you can use the 1.11.x branch directly. It is still under development, just slowing down to make way *progressively* to 2.0 (master branch). We recently released 1.11.6 and will probably release a 1.11.8 before June. It is already using a number of entities but with Symfony 2.8.

**Comment by hponiang** [comment]
Chinese people's habits are very different from foreign ones. We want to do a secondary development. If 2.x is available, we want to use it based on 2.x.

**Comment by ywarnier** [comment]
OK, no problem. It is probably going to be ready to install in ~60 days from now (but not very stable at first). But we'd be pleased to have a system that also works for chinese people.
