### ISSUE TITLE
Can't import course from chamilo 1.10.6 to 1.11.6 

### ISSUE THREAD

**Issue by xam1234** [chamilo/chamilo-lms#2497]
### Current behavior / Resultado actual / Résultat actuel
Course import to 1.11.x(19/04/2018) gives error
![abc](https://user-images.githubusercontent.com/32258255/38982898-56781a08-43c3-11e8-9b3a-35eee88a957e.png)
### Expected behavior / Resultado esperado / Résultat attendu
Course import from 1.10.6 should work
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Import example file to chamilo 1.11.x
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.6 - 1.11.x(19/04/2018)
[examplecourse.zip](https://github.com/chamilo/chamilo-lms/files/1927440/examplecourse.zip)

**Comment by ywarnier** [comment]
The fix above should take care of this issue. Please test and let us know.

**Comment by xam1234** [comment]
Scorm is added to the list and files from it are added to the scorm documents but not to the learning path, see image below.
![12](https://user-images.githubusercontent.com/32258255/39114359-edac7702-46de-11e8-8ef3-a8acfef226cd.png)

**Comment by NicoDucou** [comment]
It's your xourse export that is incorrect.
I just imported your example on 11.chamilo.org and I got the same problem, there is nothing in the learningpath : https://11.chamilo.org/main/lp/lp_controller.php?cidReq=2497&id_session=0&gidReq=0&gradebook=0&origin=&action=add_item&type=step&lp_id=292&isStudentView=false

But then I imported on 10.chamilo.org (to check on a 1.10 version of Chamilo) and I get the same problem, there was nothing in the learningpath, so I added the vidéo and now it is in the learningpath : https://10.chamilo.org/main/newscorm/lp_controller.php?cidReq=2497&id_session=0&gidReq=0&gradebook=0&origin=&action=add_item&type=step&lp_id=171&isStudentView=false

Then I exported this course
[1_2497_20180423-054003.zip](https://github.com/chamilo/chamilo-lms/files/1937780/1_2497_20180423-054003.zip)

Now I went back to 11.chamilo.org and created a new course and imported this new export from 1.10 and I get the video correctly : https://11.chamilo.org/main/lp/lp_controller.php?cidReq=2497NICO&id_session=0&gidReq=0&gradebook=0&origin=&action=add_item&type=step&lp_id=293&isStudentView=false

So the problem is on the way you did the export or your chamilo 1.10 version that is not updated and has an error because from the test I just done it worked fine.
So check on your export that you selected full course export for example, this could be a reason for not having everything exported.

**Comment by xam1234** [comment]
@NicoDucou Your RIGHT it work fine when I did import a new course backup.
Thanks 
Case Closed:)
