### ISSUE TITLE
Extremely slow page switching in LP

### ISSUE THREAD

**Issue by ric373** [chamilo/chamilo-lms#2499]
### Current behavior / Resultado actual / Résultat actuel
Extreme slow page changing in LP on mutliple visits.

### Expected behavior / Resultado esperado / Résultat attendu
Quick changing of pages.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Create a LP with 20+ pages with content (html page and exercises). Go through them a couple of times over and over. Eventually the LP will start hanging upon changing pages. 

- Click a page
- Wait 2-3 seconds
- Page starts loading
- Wait 5-6 seconds
- Page starts fading in

See report https://chamilolms.helixworks.eu/helix_learning/chamilo_report.jpg

Sometimes this process takes even longer (up to 20 seconds per page!). 

I've dug around in the code a bit and it seems the most of it is caused by the progress bar on top of the menu during xhr requests.

lp_ajax_save_item.php, lp_ajax_switch_item and lp_ajax_initalize.php all end up running the function "get_status" in learnpathItem.class.php. And most of them also run this function in a loop (for every page in the LP).

- lp_ajax_save_item.php (function: save_item) -> learnpath.class.php (function: get_complete_items_count) -> learnpathItem.class.php (function: status_is) -> learnpathItem.class.php (function: get_status)
- lp_ajax_save_item.php (function: save_item) -> learnpath.class.php (function: save_last) -> learnpath.class.php (function: get_progress_bar_text) -> learnpath.class.php (function: get_complete_items_count) -> learnpathItem.class.php (function: status_is) -> learnpathItem.class.php (function: get_status)
- lp_ajax_switch_item.php (function: switch_item_details) -> learnpath.class.php (function: get_complete_items_count) -> learnpathItem.class.php (function: status_is) -> learnpathItem.class.php (function: get_status)
- lp_ajax_initialize.php (function: initialize_item) -> learnpath.class.php (function: get_complete_items_count) -> learnpathItem.class.php (function: status_is) -> learnpathItem.class.php (function: get_status)

That's a lot of duplicate functionality for a page switch. Causing a large amount of queries to be executed. 

It gets worse the more often the same LP is viewed. A new LP works fine, but returning seems to keep adding more andd more progress records to the database causing the LP to load very slowly.

I have noticed that executing

SELECT * FROM `c_lp_item_view` LEFT JOIN c_lp_view ON c_lp_view.id = c_lp_item_view.lp_view_id LEFT JOIN user ON c_lp_view.user_id = user.id WHERE c_lp_view.lp_id=1 AND user.id=1 
(Change the lp id and user id as necessary)

on one of our Chamilo LMS' database, currently returns over 6200 records for a LP with 54 items (for a single user!). Every record is identical except for the c_lp_item_view.id. There also seems to be a bug with the start time as it seems to just record the year as it is 2018 in every record.

This table is exactly the one the scripts above keep calling for every page reload.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4, 1.11.6

**Comment by ywarnier** [comment]
Hi @ric373, you might want to check our optimization page regularly: https://11.chamilo.org/documentation/optimization.html#3.Indexes-caching
and also keep track of our developments. In 1.11.6 (and later) we have introduced improvements to these queries. One of the main issues is that some of them keep querying an "id" field where an "iid" field is already available. This may seem insignificant, but the iid is the new field that will, in the end, totally replace the id + c_id combination in all tables. As such, id and c_id are to be considered as "remnants", and we have moved the indexes from the c_id+id combination to just iid. The result of this is that when having a SQL query in the code that queries directly the "id" field instead of the "iid" (when one is available), it might in fact be executing a query without any available index, and as such be scanning the whole table.
Easy fix: add an index on the "id" field in the corresponding table (here c_lp_item_view and c_lp_view.
Better fix (which should already be inside 1.11.x branch and about to be released in 1.11.8): change the query to use "iid". The reason why this is not done in 1.11.6 is that we have had issues (only for a little fraction of our users) with the migration scripts for 1.11, so some of these iid fields have not been updated adequately and we wanted to maintain the previous relationship just in case. However (and this is a communication mistake that happened more than a year ago inside the development team), the indexes were all moved to iid by the migration scripts.

Hope this helps.

In any way, I wouldn't really maintain it as a bug as it's already been attended and should already be fixed in the development version. A good way to avoid these issues and get better fixes quickly is either to contribute more to the development and keep a closer eye on what we do, or to have permanent support contract with one of the official providers of Chamilo.
