### ISSUE TITLE
RGPG / GDPR compliance

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#2503]
To make Chamilo ready for GDPR (https://www.eugdpr.org/) and ease organization to comply with GDPR there should be an extension to Chamilo.

For the user to accept the use of it's personal data in Chamilo organization should enable and configure the "terms and conditions" functionality from the administration configuration parameters.
 
Then there should be:
 
- a place for each user to be able to see all the data that chamilo store about itself.
- a possibility to export all those data
- a possibility to remove own account

To do this there should be a new link on the social network page (main/social/home.php) in the profil bloc below "edit profile" add a link called "Personal data" that open the personnal data page.

## Personal data page

This page shows the data of the current user (each user can only see its own data).
It will have different blocs to organize the information and at the top 2 buttons : 
* Export data (that will enable to export all the datas from the page to a csv file including the date of the day)
* Remove account (that will open a window with message "If you remove your account all your data will be lost, you will loose your acquired skills, certificates, results, grades and all access to the plateform. Are you sur you want to proceed ?" and if validated then it removes the user). 

### 1) Identity
It shows a long page of data with this introduction (replace DATE by the date of the day): 
Here is the list of all your personal data as of today (DATE): 

Field | Personal data
------ | -------------
field1 | value1
field2 | value2
... | ...

**Which field would be in this table ?**
All the fields that are presented on main/admin/user_edit.php?user_id=X (where X is the user_id of the current user). This should get us all the info we have in the user table and in the user extra fields.
There will also be an IP field with all the IPs that correspond to that user that are stored in 
track_e_access, track_e_course_access, track_e_login and track_e_online.
There shoulb be a field Class to show all the classes the user is subscribed to.
If it's a multiURL plateforme and that the user have access to more than 1 URL then add a URL field and indicate all the URLs he has access to.

### 2) Social Network
This will show all the information related to this user that is related to the Social network.

- The list of social groups that the user is in and for each the messages that the user sent.
- The list of user he is friend with and for each one the messages that were sent by the current user

### 3) Courses and Sessions

* The list of sessions (name/title) the user is subscribed to or related to (coach for example)
  * The list of courses (name/title) in this session the user is subscribed to (or related to (coach for example)
    * The list of documents the user uploaded to this course
    * The list of exercises and result the user add in this course
    * The list of forum the user has created or participated in and the messages he sent
    * The list of learning path and the statistics for every item
    * The list of attendances the user is referenced in (table `c_attendance_sheet`) and the result of its attendance indicating if he was present or not (table `c_attendance_result`)
    * The list of event created by the user
    * The list of file sent or received through dropbox (`c_dropbox_file`, `c_dropbox_person`) with the feedbacks (`c_dropbox_feedback`, `c_dropbox_post`) sent by the user
    * The list of groups the user is part of with its role and all the documents, exercises, forums, chats, assignments, events and wikis of this group
    * The list of message sent by the user in the course chat
    * The list of assignment created or submitted by the user with its marks and comments if there are.
    * The list of survey the user participated in with for each on the list of the user's answers
    * The list of the current user's contribution to the wiki
    * The list of notes in the notebook
    * The list of posts in the the course Blog
    * The user's course category ordering (from `user_course_category` table)
* Add a "no session" entry
  * The list of courses (name/title) with no session the user is subscribed to or related to (coach for example)

### 4) Skills and certificates
* The list of the skills acquired by the user
* The list of feedback sent by the user on skills acquired by other users
* The list of certificate generated for the user

### 5) Personal Agenda
* The list of all the event created by the user for its personal agenda. 

### 6) Tickets
* The list of tickets created by the user or that the user participated in
** The list of post by the user in each ticket

### 7) Statistics
* The list of information that is related to the user and that are stored in the `track_e_*` tables and `user_rel_course_vote`

### 8) API
* The list of API registered in `user_api_key`

**Comment by jderriks** [comment]
The possibility to remove own account option is not always required if an organisation has conflicting legal obligations to keep student data (like quiz results or assignments) for a certain period. You can say that when a student uploads something a copy is given to the school just as if it were an email. The plugin should be configurable to handle different cases. GDPR deadline is May 25th of 2018...

**Comment by ywarnier** [comment]
Hi @jderriks,
We will definitely miss the deadline (not by much, but we won't be able to do a proper Chamilo release by then).
The option is already there to let users unsubscribe, so the institution can choose (whether or not to let them do that).

**Comment by jderriks** [comment]
Unsubscribing from a course is something different than "remove own account with all associated logging data". Chamilo does not have this feature (for users) and GDPR is not that specific. I think an email to the admin who deletes the account within x days is also a valid procedure. Is everything realy deleted when an admin removes a user? Then replace "delete" with "download" for the feature requested by this issue :-)

**Comment by ywarnier** [comment]
> Unsubscribing from a course is something different than "remove own account with all associated logging data"
That's why these are 2 different features in Chamilo.

**Comment by ywarnier** [comment]
We've added an anonymization feature to the upcoming version (see #2598). This blanks the IP address and all personal data we know of, but leaves the anonymized account there for statistical purposes.

**Comment by jmontoyaa** [comment]
I think we should create a tool in the course to get this data (per course).
Later we can make a loop of this function for all the courses/session to get all content ...
This screen it's going to be really big, better we should handle it with ajax requests ...

**Comment by ywarnier** [comment]
Why a tool in the course? This is user-related data, so I'm not sure doing this as a tool would help (there is no use case where the user would want to have his/her data only from one course).
Maybe having a mother class/interface for all course tools that defines a method to return all of *this tool's* data for a given user, but then each tool should be a class that inherits that mother class, and this is not the case yet, so let's postpone that to a later time when we need it more.

**Comment by ywarnier** [comment]
I was trying to find a way to say something to avoid exporting that, but it's really important we give more information because we *are* keeping the data and GDPR essentially gives the right to the users to obtain that data. As such, I don't feel at ease just forgetting about part of the data. We need all the info mentioned by Nicolas, even if we have to postpone the release for a few days until we get there.

I was writing an addition to the introduction saying the following:
"
Because of the amount of data we keep over you, some of the fine-grained data might not appear (yet) in this auto-generated report as we believe it would be irrelevant to the personal character of this data. For example, we might only report your subscription to the courses, but we might refrain from showing the specific data of your exercise attempts, the number of posts you have made in the corresponding forum spaces, etc. Your right is to ask for this extra data to us directly.
"
... but as I am writing it I find myself like a jerk trying to go around the law because it requires a bit more effort. I think this is wrong.

Let's make this right!

Julio, try to progress as much as possible on this. I will add some data too and ask Angel to participate this Thursday. I think in one day we should be able to really add 90% of the list above. It's certainly not exciting, but it's something we have a chance to show the example here and lead the way, so let's do that!

**Comment by jmontoyaa** [comment]
> Why a tool in the course? This is user-related data, so I'm not sure doing this as a tool would help (there is no use case where the user would want to have his/her data only from one course).
Maybe having a mother class/interface for all course tools that defines a method to return all of this tool's data for a given user, but then each tool should be a class that inherits that mother class, and this is not the case yet, so let's postpone that to a later time when we need it more.

No, I meant a function in PHP.

**Comment by jmontoyaa** [comment]
This is a long process. It will require **a lot** of time to invest. The user_id is everywhere and we have to build new queries. 

It's necessary to organize this by course? Right now I'm showing for example all documents that user created, not necessarily organized per course.

**Comment by NicoDucou** [comment]
> It's  necessary to organize this by course? Right now I'm showing for example  all documents that user created, not necessarily organized per course.

It would be easier for the user to anderstand, but I would say that in a first version it should be acceptable to have the list o document directly not organized by course.

**Comment by ywarnier** [comment]
> It's necessary to organize this by course? Right now I'm showing for example all documents that user created, not necessarily organized per course.

I already changed that and organized it by course yesterday. Not that difficult. Just saying...
But yes, for now it is enough to show all the data we know we have. The structure of the data is less important than having the whole data.

**Comment by ywarnier** [comment]
Good job on adding the big batch of data! Exploring now.

**Comment by ywarnier** [comment]
Here is a list of what is there and what is missing. You can all edit the table in this comment directly (otherwise we'll never make it).

| data | done? |
| user table data | yes |
| user extra fields | yes |
| social: list of friends | yes |
| social: list of groups/classes | no |
| social: list of messages sent | yes |
| social: list of messages sent | no |
| list of courses subscribed to | yes |
| list of courses-sessions subscribed to | yes |
| list of documents the user uploaded to this course | yes |
| list of exercises and result the user add in this course | yes |
| list of forum the user has created or participated in | ? |
| list of forum messages he sent | ? |
| list of learning path and the statistics for every item | no |
| list of attendances the user is referenced in | no |
| the result of its attendance indicating if he was present or not | no |
| list of events created by the user | yes |
| list of file sent or received through dropbox | yes |
| list of dropbox feedbacks sent by the user | yes |
| list of course groups the user is part of with its role and all the documents, exercises, forums, chats, assignments, events and wikis of this group | ? |
| list of messages sent by the user in the course chat | ? |
| list of assignment created or submitted by the user with its marks and comments if there are | yes |
| list of survey the user participated in with for each on the list of the user's answers | yes |
| list of the current user's contribution to the wiki | yes |
| list of notes in the notebook | ? |
| list of posts in the the course Blog | ? |
| user's course category ordering (from user_course_category table) | ? |
| list of the skills acquired by the user | ? |
| list of feedback sent by the user on skills acquired by other users | ? |
| list of certificate generated for the user | ? |
| list of all the event created by the user for its personal agenda. | ? |
| list of tickets created by the user or that the user participated in | ? |
| list of post by the user in each ticket | ? |
| list of information that is related to the user and that are stored in the track_e_* tables and user_rel_course_vote | ? |
| list of API registered in user_api_key | ? |

**Comment by jmontoyaa** [comment]
The problem with the chat course is that it's saved in a HTML file and it has the following "format":

```
                <div class="message-teacher">
                    <div class="content-message">
                        <div class="chat-message-block-name">John Doe</div>
                        <div class="chat-message-block-content"><p>Hola</p>
</div>
                        <div class="message-date">09/08/18 20:20:19</div>
                    </div>
                    <div class="icon-message"></div>
                    <img class="chat-image" src="http://localhost/chamilo_111/main/img/icons/64/unknown.png">
                </div>
            
                <div class="message-teacher">
                    <div class="content-message">
                        <div class="chat-message-block-name">John Doe</div>
                        <div class="chat-message-block-content"><p> Hola</p>
</div>
                        <div class="message-date">09/08/18 20:20:21</div>
                    </div>
                    <div class="icon-message"></div>
                    <img class="chat-image" src="http://localhost/chamilo_111/main/img/icons/64/unknown.png">
                </div>          

```

So the only approach will be to parse all those files .... and get the html blocks of the user ...
But there's a problem, with the user's name, in this case it's "John Doe", so if there are users with similar first name and last name they could have the same text ...
Ideas?

**Comment by ywarnier** [comment]
> So the only approach will be to parse all those files .... and get the html blocks of the user ...
> But there's a problem, with the user's name, in this case it's "John Doe", so if there are users with similar first name and last name they could have the same text ...
> Ideas? 

Those are files?
We could just put a link to the file, as we do with other documents. No problem.
If these are not files, then I think we should just give the info we have (course and date), nothing more.

**Comment by jmontoyaa** [comment]
>Those are files?
>If so we can just put a link to the file, as we do with other documents. No problem.
>If these are not files, then I think we should just give the info we have (course and date), nothing more.

Yes, saved in the file:
`
courses/XXX/document/chat_files/messages-2018-08-09.log.html`

But in the link there will be the conversation of everybody, but it doesnt matter because he also have access to it?

**Comment by ywarnier** [comment]
Indeed... Although somehow we will have to scratch our heads and find a way to explain to the user that his chat conversations could be downloaded by others, but that's a problem for another day.

**Comment by jmontoyaa** [comment]
Other question ... "normally" the user doesn't have access to that file in the course, so he can't download it. So I guess for this case we have to read the file and show it? I mean with file_get_contents() of the HTML file?

**Comment by ywarnier** [comment]
Mmmm... that's a good question. I think in this case we should make an exception because then it means it contains things we don't want him to see at least during his courses. Could you then only reference the date and add this language variable: "ContentNotAccessibleRequestFromDataPrivacyOfficer" ?
I will add this variable to translate.chamilo.org so we explain the person who to contact to get that info.

**Comment by ywarnier** [comment]
This makes me think that we might not want to tell them their score to some exams...

**Comment by ywarnier** [comment]
Yup, thinking about it carefully, we need to hide the results of those exams which are marked as "don't show score" and put the same language variable.

**Comment by jmontoyaa** [comment]
Both issues are fixed now.

**Comment by ywarnier** [comment]
:+1:

**Comment by ywarnier** [comment]
There's a bit of a bug to fix: when I go to the terms page and *only* change extra fields then save, it tells me "Terms and conditions could not be saved" or something like that and it erases all my changes. There seems to be a check on whether the contents of the main section of the terms and conditions have changed, and if nothing has changed there, the update is just ignored. That was fine before, but it is not fine anymore :smile:

**Comment by ywarnier** [comment]
Please change it so that if any of the extra field *or* the main terms change, it is considered a "saveable" change (this seems a bit complex to do because the LegalManager::add() method only returns an ID if there was a change).
I am changing now the fact that the HTML/Link and "Explain your changes" boxes are at the end and moving them at the bottom, just before the save button

**Comment by ywarnier** [comment]
That last commit should have been attached to #2554, sorry
All good here. Closing.
