### ISSUE TITLE
Email template

### ISSUE THREAD

**Issue by MonteiroJ** [chamilo/chamilo-lms#2507]
Hi,
First of all, I'm sorry to post here but chamilo's forum is impossible to register because of the captcha. Use an old one.

Here is my problem.
I would like to modify the email template, I know that there are some static string for it. But i'm looking for modyfing at least header and footer.
So is there a way to "configure" this easily ? 
How do you build a message ? 
Is there a switch on action which defines which template to use ?

Also if you have link about it, I'll take it.

Moreover, I'm up to make a tutorial on it if it works

Thank you in advance !

**Comment by ywarnier** [comment]
Hi @MonteiroJ 

If you use Chamilo 1.11.6 (you don't say) then you can find headers and footers of e-mails in main/template/default/mail/

The templating system *in 1.11.6* is a bit unpractical/broken and we have already improved it in the development version of what is going to be released (probably in June) as 1.11.8. It is unpractical in the sense that you need to overwrite the whole template just to apply a few changes, which means copying the whole main/template/default/ directory under a main/template/custom/ directory (where "custom" is whatever you like), and then changing the configuration.php file to use that new template.

If you just hack into the default template, then it will get overwritten the next time you update your Chamilo portal.

You could also try the "main/template/overrides" directory to just override one file (and that doesn't require a complete copy of all the template files), but I think it was also kind of broken in 1.11.6.

Anyway, for a quick fix you can change main/template/default/mail/footer.tpl for example, that should apply to most e-mails.
The templating of e-mails is kind of new, so I'm not sure it covers *all* e-mails Chamilo sends, but that should already get you started with a coverage of ~80%, I'm sure.

Also, you mentioned hardcoded strings. Indeed, text in e-mails is always translated, so it uses language terms which are usually quite hard to find. You can try and find them in your language in main/lang/{language}/trad4all.inc.php, but if you change them there, again, they will get overwritten at the next upgrade. Instead of doing this, define a sublanguage and redefine those strings (and only those) in the sublanguage. The sublanguage is described (as is the templating system) in the English documentation here: https://docs.chamilo.org.
Sublanguages are in the admin guide, while templating stuff are in the developers guide.

I hope it helps and that you can go and make a tutorial about it. We are in dire need of more tutorials!

**Comment by ywarnier** [comment]
Don't forget to close this issue if everything is solved with that answer.
Regarding the website and the old CAPTCHA, we should be updating the forum within a month or so. We'll fix that then. We still have new users registering though. Thanks for letting us know.

**Comment by MonteiroJ** [comment]
Thanks a lot !

**Comment by MonteiroJ** [comment]
Thanks a lot, I work on it !
