### ISSUE TITLE
AzureActiveDirectory

### ISSUE THREAD

**Issue by jtonyj** [chamilo/chamilo-lms#2516]
### Current behavior / Resultado actual / Résultat actuel

I recieve an error: Fatal error: Class 'AzureActiveDirectory' not found in /home/smuame/public_html/boulden/plugin/azure_active_directory/plugin.php on line 7

This was after an unsuccessful version update.  I performed a backup prior to and a restore after the failure.   However I still cannot see ALL of my plugins.  Along with recieving the error, stated.

### Expected behavior / Resultado esperado / Résultat attendu

To show all of my available plugins without an error.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Login to site as Admin -go to plugins

### Chamilo Version / Versión de Chamilo / Version de Chamilo

1.10.0

**Comment by ywarnier** [comment]
Hi @jtonyj 
It looks like you're having a hard time. Let me try to help, but keep in mind that there is a lot we cannot know when you're talking about failed upgrade process and errors on your server, and that whenever restoring a previous version, you have to drop (completely) the failed-upgrade-database instead of restoring the backup database "on top" of the failed one. Restoring "on top" will sometimes leave tables that shouldn't be there, and it will make subsequent upgrade attempts fail (even if the initial issue is fixed).
The same is true here for folders: if you tried to upgrade to 1.11 and then got back to 1.10, if some file in plugin/azure_active_directory/ is there from 1.11 and shouldn't be there in 1.10, then it might break your autoloader and give you the type of error you are seeing.

Also note that 1.10 is not supported anymore, except for critical security issues, as specified in https://github.com/chamilo/chamilo-lms/wiki/Supported-versions.

To ensure that your autoload is up to date, you should:
 - make sure you don't have files from the 1.11 version in your 1.10 tree
 - run "composer update" from the root directory and let it regenerate the autoload files (or just overwrite vendor/autoload.php but that's much less secure)

I'm not really sure this can fix the issue, but let's give it a try.

**Comment by ywarnier** [comment]
No answer for a month. Considering it fixed... don't hesitate to re-open if the issue isn't solved and you can provide more info
