### ISSUE TITLE
GUI - some minor issues to improve Chamilo experience

### ISSUE THREAD

**Issue by ivlevi** [chamilo/chamilo-lms#2559]
### Current behavior / Resultado actual / Résultat actuel
GUI - some items hard to edit or unable to edit. Ex: order of courses in course catalogue; apearance of "Course list in Home Page; content of side column in home page
### Expected behavior / Resultado esperado / Résultat attendu
Should be editable. For instance: left column in home page should be editable (Main navigation widget). Course list in Home page should be optional - or atleast editabe to look like in the Course catalogue page. Order ib Course catalogue should be editable (maybe drag and drop? Or atleast somehing like Order number?
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
See above
### Chamilo Version / Versión de Chamilo / Version de Chamilo

1.11.6

**Comment by ywarnier** [comment]
The order of courses on the "My courses" page is very volatile, as it changes between one student and another. Students and teachers can reorder their courses themselves from the "Sort courses" options in the left menu but that only affects them.

Using sessions provides more order, and there is a way to order sessions through the 'session_list_order' and 'my_courses_session_order' options (see main/install/configuration.dist.php).

Regarding the order in the courses catalogue, we assume that there will be many courses from many teachers in any existing platform and that ordering them would be unfair (giving priority to some courses over others), but courses can be searched.

The blocks at the bottom of the left menu can be edited through the "Edit portal homepage" option in the administration panel.

I'm postponing (but not closing) this issue indefinitely because
1) there are already several options to cover part of the items
2) we have a lot of other issues that need more urgent attention

**Comment by iustiny** [comment]
Sory, don't want to be trouble...

If Anyone else or if there is anyplace else I can find help just point me there.

As for Editing Portal Homepage - this is all I have (as admin)
![image](https://user-images.githubusercontent.com/20640562/41318427-f528ffac-6ea0-11e8-930e-19cc8c6e5374.png)
And the hompeage looks like this:
![image](https://user-images.githubusercontent.com/20640562/41318470-153becaa-6ea1-11e8-8ab7-deac9431e3ee.png)
No idea where those things come frome (Skills for instance, or navigation menu) or where I can go to make them go aay. I DID read carefuly the manual, went trough ALL settings I could find - to no avail
Same thing with CMS pages: I made one to see where it apears. But there is no place I can delete'it! The only way that woked out is to make an empty CMS page, save'it and the damn thing disapeared!

I am sory you're so busy - somehow I thought there are more of you doing this help job....
So, get rid of me! Point me to someone or some place where I can get help.

Thank you very much for your patience and help so far!

**Comment by iustiny** [comment]
About Skills - in admin page I didn't find that function. I found three places where skills have the option to enable or not and put on NO. Same for Competencies and for Certificate. No avail - the Skill tab is still there, on the left menu.

About the menu tha apears on the left - now THAT is a good piece of information that should be found in the manual. So I can't make the menu unavailable to users. If I disable'it from top bar it will apear on the left. Have I understand corectly?

I'll try the twiking from that tpl you said. I personaly don't have PHP knowledge (obviously) but I'll ask a friend. Hopefuly we'll get to the bottom of this.

One more thing: If I sellect "Special course" box, the course disapears from Course catalogue and does not apear in homepage. Any twik for that?

Thank you!

**Comment by ywarnier** [comment]
This issue has been open for 2 years now. Hopefully, your friend could help you out with the templates and you could get your left column adapted to your needs.
