### ISSUE TITLE
Reappeared - persistant admin role

### ISSUE THREAD

**Issue by Coursenligne** [chamilo/chamilo-lms#2613]
When i register a new user as "Teacher", with admin rights, if I then set the admin rights to "No", then the teacher keeps having the admin rights...

When setting to "No", the admin part should not appear anymore, and the teacher should only have "normal teacher" rights

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Create a new user as teacher and check "Yes" for administration - save
Log off and back in
edit the created "admin teacher" and select "No" for admin rights
save
Whatever you do, the admin right is persistant (back to yes).

### Chamilo Version / Versión de Chamilo / Version de Chamilo

chamilo 1.11.6
![role1](https://user-images.githubusercontent.com/32436850/43455351-cdbb1064-94bf-11e8-9788-f2e7c7a3fe02.PNG)

![role2](https://user-images.githubusercontent.com/32436850/43455352-cdd03688-94bf-11e8-8ce1-6814cc14733c.PNG)

![role3](https://user-images.githubusercontent.com/32436850/43455353-cdf2f196-94bf-11e8-8394-1124b401b8ee.PNG)

![role4](https://user-images.githubusercontent.com/32436850/43455354-ce0eec70-94bf-11e8-8e9d-b470866ea14f.PNG)
Star indicates admin right is back

**Comment by NicoDucou** [comment]
I just checked it on 11.chamilo.org and it did the same.
I tested with user testadmin

The thing is that you can not remove admin rights to yourself because you would not be able to access the page of the action you are doing. You have to remove admin rights with an other admin.

**Comment by ywarnier** [comment]
I tried removing access rights from another user on a local installation: no problem at all.
As Nicolas mentioned, you cannot remove the admin permissions from yourself. This is in place to avoid a fair amount of reports (in the forum) of people not being able to access their portal anymore, a few years back. Since then we've had much less of these issues. People make mistake. The system should try to avoid letting them do the most obvious ones.
