### ISSUE TITLE
Replace "admin blocks" from files in var/home to internal pages

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#2642]
### Current behavior / Resultado actual / Résultat actuel
HTML pages are saved in "var/home"

### Expected behavior / Resultado esperado / Résultat attendu

Pages should be saved in the new "page__page" table using the Sonata page bundle.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

An example of the content creation already exists for the "welcome" page here:

public/internal_page/edit/welcome

### Chamilo Version / Versión de Chamilo / Version de Chamilo

2.x

**Comment by ywarnier** [comment]
@jmontoyaa the administration of pages through the Sonata admin really didn't impress me in the case of our French customer. Can we change that to integrate it more transparently into de Chamilo workflow (remove all options we don't need, make easy interfaces to manage that, etc)? Otherwise I think we should rather look for another bundle than Sonata because I fear our users will get confused (nobody wants to read a whole manual about users, regions, publication states and privileges, just to be able to publish one little block of text)

**Comment by jmontoyaa** [comment]
I think I was not clear... the page:

"public/internal_page/edit/welcome"

it's already in the Chamilo UI not in the Sonata admin dashboard. In the background I'm using Sonata objects (Entities Site/Page/Blocks) to create the page. You can also go to the Sonata admin dashboard and edit it there.

![selection_001](https://user-images.githubusercontent.com/158935/44507092-94be8d80-a6a9-11e8-86f0-e1b63d142131.png)

![selection_002](https://user-images.githubusercontent.com/158935/44507096-98521480-a6a9-11e8-9165-345ca2d006c2.png)

**Comment by ywarnier** [comment]
Don't forget that multiple_access_urls should be a setting only accessible to sysadmins with access to configuration.php (too much power for normal admins).

**Comment by ywarnier** [comment]
I know, that has nothing to do with it :-)

**Comment by ywarnier** [comment]
Add to changelog that these will not be migrated during 1.11 -> 2.0 upgrade. It has to be done manually.
