### ISSUE TITLE
Time spent on course, Misunderstanding or Issue ? 

### ISSUE THREAD

**Issue by DrMickArtisan** [chamilo/chamilo-lms#2653]
### Current behavior / Resultado actual / Résultat actuel
Im' trying   to check the time spent by a student on a course. 
So i look at the reporting section on a course, select a student and check details.
But as seen on the 
![bugtempspasse](https://user-images.githubusercontent.com/11190698/44908642-7e08de00-ad1c-11e8-9399-34a95bbabf0f.jpg)
screen capture, there is a mismatch between the value "Time spent on course"  (25:24:03) (red circle) and the sum of the total time spent on each part of the course (41:15:08) (green rectangle). 
And by checking the access times for this student, I obtain the same first value (25:24:03).
Is there something I missed in the documentation ? 
### Expected behavior / Resultado esperado / Résultat attendu
Time spent on course value must be the same as the total time spent on each course .. unless there is something I misunderstood in the definitions ?
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.6

**Comment by ywarnier** [comment]
There's been a lot of work between 1.11.6 and 1.11.8 to fix this. The issue in 1.11.0->1.11.6 mostly comes from the way time is counted inside the learning paths (in particular with SCORM content if that's what you are using).
I would suggest you update to 1.11.8 because fixing this has involved a lot of code changes, so updating code individually would be very complex.

**Comment by ywarnier** [comment]
Namely, the two issues were:
- total time spent in the course is only valid if the user disconnected properly
- time counted in learning paths can sometimes be counted twice or be counted at a different speed because it is counted and registered by javascript
All these issues have been treated one by one up to where we could reproduce and verify them in 1.11.8, so unless something appears that we didn't catch before, everything should be much more precise now

**Comment by DrMickArtisan** [comment]
It seems to work perfectly with 1.11.8 version, thanks !

**Comment by ywarnier** [comment]
That's great news. Thanks for coming back to us. Old values might get cleaned up if they match our conditions for clean-up. If I remember well, but I don't remember the precise details), any 5+ minutes activity without an end marker is reduced to 5 minutes or something like that. If that's really critical for your operations, consider contacting BeezNest to deal with that through a support contract.

**Comment by Rqfc** [comment]
Hola,
Yo tengo instalada la versión 1.11.10 y me sigue saliendo el mismo error, es decir no me registra bien los tiempos de las lecciones en algunos casos me aparece que el usuario ha pasado 100 horas o 30 horas, cuando a lo mejor el tiempo que ha estado en el curso son 4 horas.
¿Habéis encontrado alguna solución a este problema?
Gracias.
