### ISSUE TITLE
Why was the breadcrumb removed from the learnPath view.tpl?

### ISSUE THREAD

**Issue by meuhland** [chamilo/chamilo-lms#2685]
I've tracked the removal to this specific commit https://github.com/chamilo/chamilo-lms/commit/7e7b16f9977292b9ede04e93537aabea9c216b68#diff-d9587829137350394d63bd6ca5e6fdec by @aragonc in a commit titled fixed mobile view but the removal is across the board.

Any reasons why this was done?

**Comment by meuhland** [comment]
https://github.com/chamilo/chamilo-lms/commit/3d645f971d9da92b5b0f2ad0b58be14da45e9237#diff-3a0a4242bc0053fbe476cb121dc0f532  seems to be also involved in it... I'm sure there was a reason to remove it I'm just curious as to why so I can relate to my users that are looking for it and flagging it as a regression between 1.11 and 1.11.8

**Comment by ywarnier** [comment]
Hi, we decided to remove the breadcrumb because it was confusing in many senses regarding the switch to student view vs teacher view. We received a number of observations of that from users that we met in training and community events (which is the main channel through which we process improvements to Chamilo). This is enough for us to want to take a step and fix the reported issue. Considering the very low current level of participation of our community, we don't put that up for vote (that would only slow us down). This is not to say that voting could not be added in the future.
Of course, if that is really an issue, you can always decide to put it back on your own portal.

I'm closing this issue to avoid it showing in our worries list, but we can continue discussing it if you deem it necessary.
