### ISSUE TITLE
no-reply issue

### ISSUE THREAD

**Issue by p4pr8n** [chamilo/chamilo-lms#2699]
In Chamilo 1.11.8 when a no-reply address is defined all mails in announcements tool are send with the no-reply sender.
If the no-reply address is empty all the mails are send with the admin mail.

**Comment by NicoDucou** [comment]
Is this a comment, or do you think there should be another way of working...
Your issue is not clear, please follow the new issue model indications to help efficiency : 

### Current behavior / Resultado actual / Résultat actuel

### Expected behavior / Resultado esperado / Résultat attendu

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

### Chamilo Version / Versión de Chamilo / Version de Chamilo

**Comment by p4pr8n** [comment]
Current behavior / Resultado actual / Résultat actuel
When a teacher creates an announcement with option  **Send this announcement by email to selected groups/users** all the mails are sent from no-reply address.

Expected behavior / Resultado esperado / Résultat attendu
Send the mails with the the teacher's email address.

Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Define a no-replay address in parameters.

Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.8

**Comment by NicoDucou** [comment]
Ok you would like to have a new global parameter to be able to configure the announcement e-mail sender.
This would be a new feature that will work like the existing parameter "Survey e-mail sender (no-reply)" that enable to choose between : "Coach e-mail address" or "No-reply e-mail address"

I not this issue as a feature request so that it can be evaluated for next version or implemented by someone who wants to help.

**Comment by p4pr8n** [comment]
Sorry if I make a mistake but we have been using Chamilo for several years and the no-reply did not work like that before. Reply to the email allowed to send the email to the real sender. I still have emails from 2016 that work properly. For me it's a regression.

**Comment by p4pr8n** [comment]
Taking an old mail that was working as expected. I see clearly that it was send from no-reply but with a Reply-To header containing the "teacher" email.
Seeing the date it was Chamilo in version 1.11.6.

To: xxxxx@zzzzz
Subject: sdsqd
X-PHP-Originating-Script: 0:class.phpmailer.php
Date: Tue, 29 May 2018 18:35:58 +0200
From: xxxxxxx <no-reply@zzzzz>
Reply-To: XXXXX YYYYY <xxxxxx@zzzzzzzz>
Message-ID: <c87b93a6992d82ce8b3991ef4d2ff3bb@zzzzzz>
X-Mailer: PHPMailer 5.1 (phpmailer.sourceforge.net)

**Comment by ywarnier** [comment]
I agree (a bit late) with @p4pr8n 
Normally if there is a no-reply address, the e-mail should be sent "from" the no-reply address, with a "reply-to" header (depending on the case, not always) of the teacher of the course.

**Comment by ywarnier** [comment]
Looks like these pointers should help in the process of finding why this behaviour changed:

https://github.com/chamilo/chamilo-lms/blob/77d9c819d0f69b94a811cde81c95be6ca09e85c9/main/inc/lib/AnnouncementEmail.php#L326

https://github.com/chamilo/chamilo-lms/blob/1970f0ca3735ccb37102a56aa7e630dcf9d0149e/main/inc/lib/notification.lib.php#L111

**Comment by ywarnier** [comment]
I've had some thought about this and I think it is alright: if we use a "no-reply@" address, this means we don't want a reply.
Adding a "Reply-to" address is a bit weird in this case, because we asked the e-mail to be sent with no opportunity to reply (hence the "no-reply@" address).
So we would need an additional option in the configuration to allow for an additional "Reply-to" header *even if* we have set a "no-reply" address.
```
// Add a reply-to header whenever possible (usually to the first teacher of the course) even when a
// no-reply address is set.
//$_configuration['mail_no_reply_allow_reply_to'] = false;
```
And then we would have to check in api_mail_html() for this variable.

**Comment by AngelFQC** [comment]
I configured only the `no-reply` address in 11.chamilo.org and sent an announcement to one user. And this is the result:

![imagen](https://user-images.githubusercontent.com/1697880/53990471-5bee7f00-40f6-11e9-8d4b-51254b9a10c8.png)

The email was sent with the reply-to header set to the teacher address.

The configuration option suggester by Yannick should be opposite, `mail_no_reply_avoid_reply_to` to don't sent the reply-to header when no-reply address is configured.

**Comment by ywarnier** [comment]
In this commit, @AngelFQC has also (on my request) extracted the complexity of determining what the From and Reply-To headers should be in general, based on the information provided and the active configuration parameters, into a new function api_set_noreply_and_from_address_to_mailer(). This should make api_send_mail() easier to deal with, also (it was becoming a very big function).

**Comment by p4pr8n** [comment]
I am sorry to come back with this issue but we have a fresh installation in version 1.11.10.
When a teacher sends an announcement it is the no-reply (or admin when no-reply is not configured) which takes the priority for outgoing mails. Even stranger when you make a reply to the mail directly from the Chamilo's interface, the reply is going correctly to the teacher.

Thanks

**Comment by p4pr8n** [comment]
Not so fool. There is still an issue:


api.lib.php on line 9400

`$mailer->AddReplyTo($replyToAddress['email'],` `$replyToAddress['name']);`
must be changed to:
`$mailer->AddReplyTo($replyToAddress['mail'],` `$replyToAddress['name']);`

and It is necessary to define SMTP_UNIQUE_REPLY_TO = 1

**Comment by tanchon** [comment]
Thanks p4pr8n ! 

I had the same problem with my 1.11.10 Chamilo => when i wanted to make a reply, it wasn't to the teacher (but to the admin mail).

i made the changes in api.lib.php and i define the SMTP_UNIQUE_REPLY_TO = 1 and it works ! (i don't use no-reply adress). Now, when i want to reply, it is to the teacher !
