### ISSUE TITLE
Suggest to update the reporting template on Github

### ISSUE THREAD

**Issue by opensourcecompany** [chamilo/chamilo-lms#2705]
### Current behavior / Resultado actual / Résultat actuel
people are not aware of the doccumentation of:
https://docs.chamilo.org/

People should know that sometimes there are no bugs but not properly done configurations :-)

**Comment by ywarnier** [comment]
Linked as "Official documentation" from https://chamilo.org/en/download/
People just don't want to read the manual. That's why the "RTFM" expression exists in the first place.
Do you have any suggestion as to why to make them aware that the documentation exists? I can see that maybe we should add a link to the "chamilo.org" block on the admin page, but apart from that I don't really see what else we can do: if you don't want to read the documentation, we cannot force you to do so.

**Comment by ywarnier** [comment]
Added links in CONTRIBUTING.md and the issue template
