### ISSUE TITLE
No save recorded button in Chamilo 1.11.8

### ISSUE THREAD

**Issue by Elearner2018** [chamilo/chamilo-lms#2720]
### Current behavior / Resultado actual / Résultat actuel
No "Save recorded audio" button. Students can't save their recordings and send them to the teacher.

### Expected behavior / Resultado esperado / Résultat attendu
There is a "Save recorded audio" button in Oral exercises.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Create an oral exercise. Access the exercise as a student (or a teacher) and press "Start recording". When you are done press "Stop recording". After this step, there is no "Save recorded audio" button which saves the audio (as in Chamilo 1.11.6) and it can be sent to the teacher for correction.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
Chamilo 1.11.8

**Comment by NicoDucou** [comment]
Now the audio is automatically sent to the server, that's why there is no "Save recorded audio" button. If the user record a second time it will be saved on top of the first one so no problem.

@Elearner2018 , I let you close this issue if this answers is enough for you.

**Comment by Elearner2018** [comment]
Ok. It is true that it is possible to listen your speech by pressing play in the audio bar immediately after recording and then record again and listen to this new recorded audio. However, when the student presesses the orange button _Check the _answers__ below to send the exercise to the teacher for correction, the problems start. When the teacher tries to check the exercise, there is no audio bar where the teacher could normally press play and listen the student's recorded audio and then give her feedback. So, it seems that this recorded audio is not saved.

In contrast, in Chamilo 1.11.6 when the teacher checks these audio exercises there is always this audio bar where she can press play and listen what the student answered and then give feedback. In Chamilo 1.11.8 this audio bar is missing when the student has sent the exercise to the teacher for correction resulting it look like it won't save the audio. 

In Chamilo 1.11.8's oral exercises there is still the same text as in Chamilo 1.11.6 that says "When you start recording, you can pause whenever you want. If you are not satisfied, register again. This will overwrite the previous version. Satisfied? **To transmit the recording click on "Save recorded audio**".  This save recorded button is missing and I wonder it that is the reason why the teacher can't see the audio bar for listening the student's answer before giving feedback.

**Comment by NicoDucou** [comment]
I can not reproduce the problem on the development plateform.
I just did a test with user amann/amann here : https://11.chamilo.org/main/exercise/overview.php?exerciseId=1306&cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=&
And once I just finished recording I just had a message indicating the file has been recorded.

![chamilo 1 11 x 19 11 2018 11 34 gmt 2 validation portal nicodu](https://user-images.githubusercontent.com/6579268/48703447-0ac48900-ebf4-11e8-98f4-818fada36868.png)

As the teacher (admin/admin) I can listen to the student recording here : 
https://11.chamilo.org/main/exercise/exercise_show.php?cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=&action=qualify&id=917

Could you reproduce your problem on 11.chamilo.org or tell me how to reproduce it because for me all is working well.

The only thing that is wrong is the message in which there should not be the last part. I just updated the translation for english, french and spanish.

**Comment by ywarnier** [comment]
Any feedback from @Elearner2018 ?

**Comment by Elearner2018** [comment]
Not yet, I have still many tests going on still without success. Obviously, I can't produce the problem in the platform suggested. The problem is in the Chamilo 1.11.8 installaion that I am using. 

Chamilo won't give the message given in green background as above and it seems to be the problem as it saves the file then. Chamilo 1.11.8 is a fresh installation taken from www.chamilo.org (it was checked earlier that the .zip file was exactly the same as in Github) meaning that the version 1.11.6 was not updated to this 1.11.8 version. All examples so far where it seems to be working are the ones that have been updated. I'm quite interested to know it the feature works in fresh installations. 

I really, really, would like to start using the newest version and need desperately someone's help.

**Comment by Elearner2018** [comment]
Tried the following without success. Took the scripts from Chamilo 1.11.6 to the following places in Chamilo 1.11.8. No effect.
/main/template/default/document/record_audio.tpl
/main/template/default/document/recycle.tpl

**Comment by NicoDucou** [comment]
@Elearner2018 it would be better to check with the latest version of Chamilo because there have been correction since the last release of 1.11.8

Here is a commit about your issue that has been sent after the release of 1.11.8 : 
https://github.com/chamilo/chamilo-lms/commit/3b8f9ebca99b07e37207cb367670a43fcab6fdf9#diff-520b994d6428db6c737293def624e880

May be applying this commit will solve your problem.

**Comment by Elearner2018** [comment]
Brilliant! It worked. The audio recorder now works as it should. Big thanks. You saved my day!

**Comment by Elearner2018** [comment]
I'm really sorry to get back to this again but now a new issue came up related to the recorder. The script is changed according to the instructions and students can now record their speech & it is sent to the teacher for correction. But,
When a teacher checks a student's oral exercise, the only option Chamilo 1.11.8 offers is a written feedback whereas in Chamilo 1.11.6 the teacher has a choice between written or oral feedback for the student. This option comes up when the teacher opens the feedback box but now in Chamilo 1.11.8 the audio recorder is not given at this stage for the teacher.
I now wonder if there is also something else that has to be added to the script so that this feature comes up for the teacher?

**Comment by NicoDucou** [comment]
The teacher's audio comment is dependent on a configuration setting. To enable it you have to add the following setting in app/config/configuration.php : 
`$_configuration["allow_teacher_comment_audio"] = true;`

**Comment by Elearner2018** [comment]
Brilliant, works!
