### ISSUE TITLE
Suggestion: Copyright protections

### ISSUE THREAD

**Issue by spacecabbie** [chamilo/chamilo-lms#2752]
**Is your feature request related to a problem? Please describe.**
Suggestion: Copyright protections make it not possible to download or copy paste displayed contend unless its disabled for that section

**Describe the solution you'd like**
Every module/content would have a switch to set it to protected mode.

**Comment by ywarnier** [comment]
Hi @spacecabbie 
The goal of the Chamilo Association (and so also the Chamilo project in general) is to "Improve the availability of quality education all around the world". Copyright and DRMs are a no-no for us, because they don't help *at all* towards our goal.
If you feel copyright protection is necessary on your content, then we recommend you just add some watermark inside your content or you use another LMS. This is just not going to happen in Chamilo. Pretty much against our phisolophy and ambitions, sorry :wink:

**Comment by spacecabbie** [comment]
Why sorry its a good Philosophy witch i completely understand.

I am how ever using it for a situation where there is simply allot of
content stealing i have implemented my own protections.

Thanks as always for your quick response.
