### ISSUE TITLE
Fix default certificate in gradebook

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2758]
**Describe**
The gradebook is now showing a very ugly default certificate.

![default-certificate](https://user-images.githubusercontent.com/609839/50186913-5b5dfd80-02ea-11e9-9e5d-b2d39ae0d45d.png)

I sincerely believe we can do a bit better :-)

**To Reproduce**
1. Go to any course (I tried one in French)
2. Go to the gradebook tool
3. Click the certificate icon on the right
4. Click the magnifier icon

**Server
 - OS: Irrelevant
 - Version of Chamilo:  1.11.x of 2018-12-18
 - Version of PHP: 7.2

**Comment by AngelFQC** [comment]
I think this issue is a false positive :sweat_smile: 

Maybe you arre trying with a course created with the data filler feature for admins (Administration > Data Filler > Fill courses). Like `FRENCH101`

Try creating a new course from Administration > Create a course > Fill the form. Then go to the new course > Gradebook tool > Certificates

This is the default certificate for new courses 
![imagen](https://user-images.githubusercontent.com/1697880/50310271-7efe8080-046f-11e9-9fcb-84adb422fb95.png)

https://11.chamilo.org/main/document/document.php?curdirpath=/certificates&cidReq=TESTINGDEFAULTCERTIFICATE&id_session=0&gidReq=0&gradebook=1&origin=&origin=gradebook&selectcat=279

**Comment by ywarnier** [comment]
@aragonc sí, se puede cambiar de diseño pero a diferencia del plugin de certificados customizados, los de Chamilo base deben funcionar bien en HTML *y* en PDF.

@AngelFQC alguna idea de lo que los malogra con el script de creación (fill_data.php)? La ruta de los CSS que no estaría bien creada desde el script?

**Comment by AngelFQC** [comment]
Ese certificado se genera al crear un curso con contenido de ejemplo. Y se copia esde `main/default_course_document/certificates/default.html`

**Comment by AngelFQC** [comment]
El otro certificado, está registrado en la base de datos como una plantilla de documentos y se crea como predeterminado cuando se ingresa por primera vez a la herramienta de certificados en el gradebook (siempre y cuando no hay otro certificado).

Con los cursos con contenido de ejemplo, se crea el certificado desde `main/default_course_documen/certificates`, por lo que al entrar por primera vez, el certificado correcto, no se crea.

Envié este commit e1938aa4c3964f68c8cc623c07ba01480f88fe56 para borrar el archivo y que no se use como contenido de ejemplo.

**Comment by ywarnier** [comment]
:+1:
