### ISSUE TITLE
Random usernames

### ISSUE THREAD

**Issue by Elearner2018** [chamilo/chamilo-lms#2810]
Random usernames should be working in Chamilo 1.11.8 according to this:
https://chamilo.org/en/2018/09/19/10-new-features-of-chamilo-1-11-8/
_Until now, importing users without a username through CSV in your LMS would automatically generate a username based on the first name, last name and a sequence number. This was relatively foreseeable and could lead to security issues. **Now the username is generated randomly for each user, independent of his/her name.** If you don't like that, just give a username to the user in the CSV file._

1. Create a CSV file, leave out username and password
2. Import User List and Send an email to the user
3. Check email

A username is automatically created independent of the user's name. But, it's not. The username that is created is still made of the user's surname and the first name's first letter.

- Browser: Firefox
- Server: Linux Ubuntu 18.04
- Version of Chamilo: 1.11.8
- Version of PHP: 7.2

**Comment by NicoDucou** [comment]
Hi @Elearner2018 
You have to activate this configuration for Chamilo to generate random username otherwise the usual mecanism is still the default.
To activate this functionnality you need to edit the file app/config/configuration.php and add this setting : 
```
// Generate random login when importing users
$_configuration['generate_random_login'] = true;

```
Let us know if this works for you so that we can close this issue.

Best regards

**Comment by Elearner2018** [comment]
One change takes place. Now the username is made of the first letter of the first name and surname (there is no full surname anymore).

**Comment by ywarnier** [comment]
@Elearner2018 is right. There is a bug in that feature (in my view): we *only* set a random username if the username is set, which is the opposite of what we say should happen (+ it doesn't make a lot of sense because if we set a valid username and that feature is enabled, the final username will not have anything to do with the username we gave).

https://github.com/chamilo/chamilo-lms/blob/e6763480f728a95284e4be8a2b6251b43c5b82fe/main/admin/user_import.php#L338-L343

I've updated the code to only generate a random username when the username is empty in the CSV (the column is not there or it is there but there's nothing in the field).

@Elearner2018 do you have the ability to update through Git or manually (it's only a one-word change), or do you want to test it on one of our test platforms?
