### ISSUE TITLE
File deletion

### ISSUE THREAD

**Issue by Elearner2018** [chamilo/chamilo-lms#2811]
When a student's exercise attempts are deleted in the platform as an administrator, it is not deleted from Chamilo's files in the server. Why is this a problem? It enlarges the course size when you can not permanently delete audio files or exercise attempts. The same thing happens when you delete a user in the platform as an administrator. The user is deleted in the platform but its user folder still exists in Chamilo's files in the server.

Import an audio file to the learning path and delete it. Have a look at Chamilo's files in the server and you'll see the item's name with the text deleted but the file still exists. Delete a user in the platform as an administrator and have a look at Chamilo's files in the server. The deleted user's user folder still exists.

What you delete e.g. audio files or a user's exercise attempts in the platform the files should also be deleted in Chamilo's files in the server (otherwise the course size gets bigger and bigger). User folder should be deleted in the Chamilo's files when it is deleted in the platform.

 - OS: Linux Ubuntu 18.04
 - Browser: Firefox
 - Version of Chamilo: 1.11.8
 - Version of PHP: 7.2

**Comment by NicoDucou** [comment]
Hi @Elearner2018 
For the files that are with the deleted extension added to the name, it is a security feature that is enabled by default in Chamilo in case someone deletes the something by error. Which can happen !!!
If you want to disabled this feature, it is called  "Deleted files cannot be restored" in the configuration settings.

There is also a command with chash for the administrador of the server to delete all the files marked with the deleted tag in the name.

For the user files indeed this folder is not deleted but I'm not sure if we want to have it deleted when deleting the user because some files could be used in other part of Chamilo and not only by the user.
So maybe this could be changed in next a future version of Chamilo.

**Comment by Elearner2018** [comment]
Hi, Thank you for this thorough explanation. We'll try them out.

**Comment by Elearner2018** [comment]
Hi, Thank you for this thorough explanation. We'll try them out.
