### ISSUE TITLE
Audio file format

### ISSUE THREAD

**Issue by Elearner2018** [chamilo/chamilo-lms#2812]
At the moment Chamilo 1.11.8 recording device makes ogg format with Mozilla Firefox but uncompressed audio format wav with Edge and Chrome when a student leaves his audio reply to an oral exercise form.  

Is it possible for Chamilo 's recording device to make ogg format despite the browser? 
A feature request: Audio recorder makes ogg format when a user uses Firefox, Edge or Chrome. This way the course size would stay reasonable.

**Comment by ywarnier** [comment]
This is actually difficult to do without increasing the requirements at the server level (because we need something on the server to be able to convert the audio formats). This is something me do (if I remember well) for some of our business customers, but not for Chamilo itself because it would overcomplicate the installation procedure.
I'm not sure when we would be able to attend this issue report, so I'm adding it to the "undefined" milestone, meaning we don't abandon it. I just don't consider it a priority in the grand scheme of things

**Comment by Elearner2018** [comment]
Ok, good to know and thank you for considering this option.

**Comment by andreboivin** [comment]
Aurais-tu la procédure que tu as utilisée pour tes clients sous la main?

**Comment by andreboivin** [comment]
en installant ffmpeg, j'ai essayer avec la commande:
ffmpeg -i testwav.wav -c:a libvorbis -qscale:a 3 testwav.ogg
la conversion s'effectue. est-ce possible de l'insérer dans record_audio.js ?
