### ISSUE TITLE
SCORM Ispring Content Update

### ISSUE THREAD

**Issue by 480419140** [chamilo/chamilo-lms#2843]
I use the current version of Chamilo, and for about 20 days, I'm having trouble updating the training through the update of the scorm package. I make the submission first time and it works perfectly, however, when I make some changes in the training and create a new scorm to perform the update, it informs that the content has been updated, but was not and does not return any error.

SCORM packages are being generated in ISPRING software and PHP 7.

In a php 5 installation, this scorm package update works perfectly but returns the message below as alert:

**Warning: Use of undefined constant SECTION_COURSES - assumed 'SECTION_COURSES' (this will throw an Error in a future version of PHP) in C:\xampp\htdocs\lms\main\lp\lp_update_scorm.php on line 11**

Is this the cause of the update problem using PHP 7 aversion?

**To Reproduce**
1. Go to new course
2. Click on learnpath
3. Upload new learnpath in format SCORM 1.2 
4. Open Course
5- Update course including additional information, and new generate package SCORM 1.2 e upload upgrade course 
6 - Open course, and not upgrade

**Expected behavior**
Open course actualized

Implementation information
   Version PHP 7.0.33-0ubuntu0.16.04.2
 - Version of Chamilo: 1.11.8
 - Server Web : Apache/2.4.18 (Ubuntu)
--
Could you verify this behavior?

**Comment by ywarnier** [comment]
Hi,

Yes, this might be the cause of the failure in PHP 7 as it clearly says "this will throw an Error in a future version of PHP". Do you have access to your web server's error logs? These should contain some additional information (at least the warning).
If you can change your PHP configuration, maybe try to set it to a level where WARNING messages are ignored...

Let's analyse this: first it is very weird because the constant SECTION_COURSES is actually defined in main/inc/lib/api.lib.php which is pretty much loaded *everywhere* in Chamilo (it is one of the most important libraries). This suggests that, for some reason, you might be trying to access the lp_update_scorm.php file directly and not through the normal path. If not, then something else must be wrong in your configuration of Chamilo or maybe this feature was not well compiled when we packaged 1.11.8 (this might also be a valid explanation).

Second, you actually don't need that constant for anything in this script (it is mainly used for the layout of the page), so you could simply replace that "line 11" of lp_update_scorm.php by:
```
$this_section = 'mycourses';
```

This should at least avoid the warning in PHP 5 and maybe fix the issue in PHP 7. If it does, be sure to let us know so we can investigate this further. Thanks for reporting.

**Comment by 480419140** [comment]
Good Morning @ywarnier 

Regarding the installation of PHP 5, the error is not occurring. However, in the installation where you have php 7, I'm still not able to perform training updates through the "Upgrade" option. I looked at the behavior, and it seems that the upgrade option is not redirecting the correct paths of the scorm package, because when performing the update no error is returned, but I analyze the training folder on the FTP server, and the content is not actually updated.

I am sending below the test platform access data and I am also sending two packets with different content contents, simulating the upgrade from one content to the other and will realize that it is not being updated.

If I can analyze the behavior with a more technical look, I'm getting the attention.

URL: [http://50.19.59.231/sucuri](http://50.19.59.231/sucuri)
Login: teste
Pass: teste

Course: Test Upgrade Chamilo

SCORM 1

https://drive.google.com/open?id=1cIAPij8RRF9CU_BuBTLZKOQgkJ965pXb

SCORM 2

https://drive.google.com/open?id=1oubLraTIWFcXqvR3XlDAN9ZXEb6gf4PV

Sincerely.

**Comment by Haboubi92** [comment]
the problem has nothing to do with the scorm package (created with ispring)
here is the content before update
![b1](https://user-images.githubusercontent.com/48198054/54481757-f6af3200-4849-11e9-9227-e8cbee766e60.PNG)

and after updating
![b2](https://user-images.githubusercontent.com/48198054/54481763-0cbcf280-484a-11e9-80f7-6f6fb8021a2e.PNG)

I don't have any technical background but I guess that you couldn't update because some users have already answered some questions inside your scorm and the system didn't update the content to prevent changes in results

**Comment by 480419140** [comment]
Good Morning @Haboubi92 ,

In the test performed, you can also update the content, but only the first time.

If you try to upload the previous update again, returning to the initial situation, you will see that the content will not be changed.

I do not know if what has informed about some users already have answered some questions is the problem, because in the current situation that happened here the scorm files, are simple slides, without any user interaction.

try updating the same scorm, returning to the initial situation, and see if you will succeed.

@ywarnier ,I contacted Ispring, and was informed that the error may be on the lms side.

I'm waiting.

**Comment by Haboubi92** [comment]
@480419140 
it appears that I can only update the SCORM package once
after the first update I couldn't update it with older file or a new file
I tried this on Chamilo 1.11.8 and 1.11.4

**Comment by 480419140** [comment]
That's right, after the first attempt it's no longer possible to update the content, the strangest thing is that it does not return any errors.

Let's wait for a feedback from the community.

Thanks for the support.

**Comment by 480419140** [comment]
I tried to test on https://11.chamilo.org and returned the error below

Notice: Undefined index: use_max_score in /furanet/sites/11.chamilo.org/web/htdocs/main/lp/lp_upload.php on line 86

Warning: Cannot modify header information - headers already sent by (output started at /furanet/sites/11.chamilo.org/web/htdocs/main/lp/lp_upload.php:86) in /furanet/sites/11.chamilo.org/web/htdocs/main/upload/upload.scorm.php on line 41

**Comment by 480419140** [comment]
New error in debugger update

Refused to execute script from 'https://..../main/glossary/glossary.js.php?cidReq=CDCPTGR&id_session=30&gidReq=0&gradebook=0&origin=' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by ywarnier** [comment]
Does the ispring content contain a ".htaccess" file?

**Comment by 480419140** [comment]
he ispring-generated scorm has no .htacess file, should it exist? I downgraded the Ispring installation to a 12/2018 version when I was sure it was working, but the error continues.

**Comment by ywarnier** [comment]
No, it should not, but for some reason the web server detects glossary.js.php as a "text/html". This glossary change might be recent and the issue you are seing in the debugger might be due to that, but this shouldn't affect the fact that your content is updated or not.

The SCORM updating (replacement) feature is new in 1.11.8 and it might still fail for some cases. Please make sure that the updated content is identical (the names of the individual files are the same), otherwise Chamilo will refuse to replace it.

**Comment by 480419140** [comment]
Yes, the files are the same. And updating tells you that it has been updated successfully.

I noticed in a local version and older, that when updating this update, it seems that it overrides the original path to a "Upload" folder, and adds the new files. I do not know if that's it, but it's the only difference I found.

Does anything in the .tgz package generated and made available? Can you enhance a new compression to test it?

**Comment by 480419140** [comment]
@ywarnier 

I connected a local lms which has the same version as the production version, but running php 5 to the production database, and I was able to update the content normally. so I think the problem is relating version 7 of php, where some update may be interfering with the operation. For if I have two identical systems and banks, and I connect both in parallel and succeed, the only configuration that distinguishes the two is the PHP version. Could you evaluate based on this information?

**Comment by BooneHenry** [comment]
For my five pence.

I'm not a coder or Java script writer or web designer, so my comments might be worthless. But i do need help with the Content Security Policy and the content policy report lines, which gave me similar problems.

I also bought Ispringer 9.3 (in last 3 weeks) to start content creation for scorm and my software uploads are to a Chamilo 1.11.8 (new implementation).

Yes I found the SCORM uploads did not work - So 1st thing I suggest is from your PC drive, in the ispringer version zip file created, upzip the file and then find the index.html page in the unzipped file and see if your local browser can read the file and play through the screens. 

Then contact the Ispringer Support team and send them the Ispringer Export file from Powerpoint and ask them to load the file to cloud.scorm.com (i spoke to Michael who was very helpful) and see it it runs in cloud.scorm.com - i.e. the SCORM file works
 
If it does not run it could be because you did not set the Marks under SCORM xxxx (at least tick read all pages (the first ratio button) and marks 100). Otherwise the Chrome browser does not read the learning path file when uploaded to Chamilo  (I get an unsupported browser return messages when I upload Ispringer HTML5 files to Chamilo, but they read in Cloud.scorm.com OK - So something in Chamilo is limiting the HTML5 SCORM file from being read in Chamilo, if no marks are allocated. The Ispringer team acknowledge a problem with quiz marks. Not this problem.

I recommend you publish in Ispringer with the play media files on mobile, as it corrected the above error of Chamilo learning paths not reading SCORM files.

Then, if you turn on (remove the //) the HTTP settings in the configuration.php  file as recommended in the install security guide for HTTP cross-origination. For some reason the SCORM files are not uploading and running in Chamilo and when I set the HEADER to access control allow and the HTTP content Security Policy it does work . 

(I did not have the lp_ configuration change setting amended when I did this and they were turned off - Yanick - did not try this piece) 

Then What I did find is the following
a) You must set up   Header set Access-Control-Allow-Origin in your .htcaccess file  - because if you do not any link to a you tube video will not appear in the iframes in html5.

I added
Header set Access-Control-Allow-Origin "example.com , www.youtube.com, *.youtu.be, *.vimeo.com, *.slideshare.com "  or you can use "*"    . Please put a comma between each URL if you use this.
And the help team could really help if they could tell me the URL for Gravatars as all my Gravatars have now returned errors and I would like to add them to the statement. 

Then I have  to report an error in the configuration install notes and security guidance for Chamilo.
In the configuration.php line 
453 //$_configuration['security_content_policy'] = 'default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; child-src 'self' *.youtube.com yt.be *.vimeo.com *.slideshare.com;';
454 //$_configuration['security_content_policy_report_only'] = 'default-src \'self\'; script-src *://*.google.com:*';
the 'self', 'unsafe-eval' and 'unsafe-inline' are generating errors in my firefox and chrome browsers when I set them to on. This line is not working in the code.
If you do not set this line on- I got Ispringer SCORM load file errors - so it needs to be on, but is causing a problem with the learning path SCORM upload.

also check you antivirus software as mine was adding some Cross origin code anonymous which also create similar problems to the issue above.

On the php version - I just added 7 to the listed line code and it seems to work. I'm using 7.3

Hope this helps 
Tks

**Comment by migsauceda** [comment]
Hi, 
How I download de version that is runing in 11.chamilo.com?
-----------------------
Hola, ¿cómo descargo la versión que se ejecuta en 11.chamilo.com?

**Comment by ywarnier** [comment]
@migsauceda 
1) esperas unos días para la publicación de la versión 1.11.12 (debería ser antes del fin de Julio)
2) instalas la rama 1.11.x de Chamilo desde Github. Requiere conocimientos técnicos más avanzados y la lectura del README.md en esta rama

**Comment by ywarnier** [comment]
@480419140 Are you expecting some additional info from me?

**Comment by migsauceda** [comment]
Gracias, anoche instalé la rama release 1.11.10-releases.
¿La versión 1.11.12 es igual a la 1.11.x?
Agradezco mucho la respuesta, no se imaginan, incluso modifiqué ckeditor para dejar $style en blanco y así no se generaran los link para que los profesores puedan sin mucho problema incrustar imágenes, estaba desesperado.

Si 1.11.x y 1.11.12 son iguales mejor instalo la 1.11.x y dedico el fin de semana a personalizar.

**Comment by migsauceda** [comment]
¡Si! una pregunta, para la nueva instalación ¿que recomiendan?
1) ¿solo borro el contenido de la carpeta donde esta Chamilo? mi instalación es un un hosting de paga, no tengo muchas libertades
ó
2) ¿hay algún script para desinstalar?

**Comment by ywarnier** [comment]
> Gracias, anoche instalé la rama release 1.11.10-releases.

La rama 1.11.10-releases no debería ser usada. La voy a eliminar, solo sirve para trabajos pre-publicación (en este caso de la versión 1.11.10 hace más de un año).

> ¿La versión 1.11.12 es igual a la 1.11.x?

La *rama* 1.11.x es la que permite publicar las *versiones* 1.11.0, 1.11.2, 1.11.4, 1.11.6, 1.11.8, 1.11.10 y pronto 1.11.12. Es una rama, no una versión, lo que significa que es un código en estado dinámico (siempre cambia) cuando una versión es como una foto de la rama en un momento X (con preparación de distintas cosas alrededor).

Descargar una rama implica hacer un trabajo de preparación adicional (técnicamente basta con "composer update", si es que sabes como usarlo, pero puede ser más complejo).
Descargar una versión estable usualmente implica elegir un paquete que corresponda a tu versión de PHP, pero luego ya no tienes nada que hacer.

La versión 1.11.12 está en preparación (la versión beta - es decir de pruebas - debería estar lista dentro de 1 o 2 días).

**Comment by ywarnier** [comment]
> ¡Si! una pregunta, para la nueva instalación ¿que recomiendan?
> 
>     1. ¿solo borro el contenido de la carpeta donde esta Chamilo? mi instalación es un un hosting de paga, no tengo muchas libertades
>        ó
> 
>     2. ¿hay algún script para desinstalar?

Si quieres eliminar lo existente, solo debes hacer 3 cosas
- eliminar la base de datos *entera* (drop database chamilo-algo)
- eliminar la carpeta de chamilo *entera*
- volver a descomprimir el zip de Chamilo como la carpeta que acabas de borrar

**Comment by ywarnier** [comment]
@migsauceda gracias por no seguir en esta tarea y abrir una nueva. Una tarea por tema. Aquí el tema era de problemas con SCORM. Nada que ver con la instalación de Chamilo.
También es bueno saber que este espacio no es para preguntas. Las preguntas las puedes hacer en https://forum.chamilo.org/
Aquí es solo para reportar errores, sugerencias de mejoras, o contribuir correctivos o funcionalidades nuevas.
Me acabo de dar cuenta de lo totalmente fuera de contexto que eran tus preguntas, así que me permito darte a conocer estas reglas (disponibiles en el wiki).

**Comment by migsauceda** [comment]
Enterado, estaba desesperado, el foro jamás respondió, incluso me atreví a
modificar parte del código.

Gracias, por sus aportes.
