### ISSUE TITLE
adding smiley faces option in minimized text editor 

### ISSUE THREAD

**Issue by Haboubi92** [chamilo/chamilo-lms#2870]
I suggest adding smiley faces option in the minimized editor, this would suit younger learners who are addicted to use them in other social apps (facebook, whatsup, telegram...etc.)

![image](https://user-images.githubusercontent.com/48198054/55428263-671bba00-5591-11e9-8f74-b85baf5c6b92.png)

**Comment by ywarnier** [comment]
The number of options is highly dependent on the tool in which it appears, so this issue is a bit too simple to apply as is. Each tool has been analyzed and worked on through years of teachers requests. I don't mind adding a few in the extended view (like smileys) but reducing them has to be justified on a case-by-case basis. For example: "In messages, it is never necessary to have the icon of mathematical formula in the minimized view", to which someone will object that they use it because their portal is mostly focused on mathematics... I think this task should focus on the smiley icon.
Thank you for suggesting improvements, but in this case and from my 15 years of work on this... this is just not a good one :smile: sorry

**Comment by Haboubi92** [comment]
@ywarnier thanks for taking time to explain the reason why there are extensive options in editor 😊
I edited the issue to include only the smiley option 😉

**Comment by Haboubi92** [comment]
thanks for taking time to explain the reason why there are extensive options in editor 😊
could you please delete this issue
even the smiley suggestion was no very good idea, because users can insert emoji directly form mobile devices using emojis available on every touch keyboard
![Screenshot_20190402-225702](https://user-images.githubusercontent.com/48198054/55432104-be725800-559a-11e9-8303-04f1c8f2e60d.png)

**Comment by ywarnier** [comment]
Fair enough
