### ISSUE TITLE
Questions not saved in IMS / QTI are not displayed

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#2890]
Hello
When creating an IMS / QTI for an exercise.
You send to another course.
More questions are empty.
greetings

![backup](https://user-images.githubusercontent.com/25286516/56921802-136f9400-6a9d-11e9-8e23-33ce28d0be38.png)
![import qti2](https://user-images.githubusercontent.com/25286516/56921810-19fe0b80-6a9d-11e9-8a73-8b6325c31eb7.png)
![vazio](https://user-images.githubusercontent.com/25286516/56921815-1f5b5600-6a9d-11e9-8b2a-04563f58e797.png)

test in https://11.chamilo.org/.

**Comment by ywarnier** [comment]
This seems to be the last issue for 1.11.x, so we should be able to release on Tuesday or something like that.

**Comment by ywarnier** [comment]
I cannot reproduce this issue on 11.chamilo.org. I tried creating a test in https://11.chamilo.org/main/exercise/exercise.php?cidReq=BZN&id_session=0 , then I exported it as QTI and imported it in   https://11.chamilo.org/main/exercise/exercise.php?cidReq=TC10&id_session=0 and I have the question text.

It's the same question type as in your example.

The only difference I see is that the resulting test does not have the "embeddable" icon (screen and headphones), but this is due to the "one question per page" option which is not maintained in the QTI format (there is no option to communicate that in that format).

**Comment by bassuma** [comment]
OK.
The issue that multiple choice does not occur is this problem.
If you add any questions from:
(Fill blanks or form)
This is where the problem occurs.
I tried to replicate on 11.chamilo.org.
I could not even download.

![2019-05-05 (6)](https://user-images.githubusercontent.com/25286516/57198548-95066c80-6f4a-11e9-94ea-85d7b9a70eaa.png)

![2019-05-05 (7)](https://user-images.githubusercontent.com/25286516/57198551-9899f380-6f4a-11e9-9888-91d633b8a879.png)

![2019-05-05 (8)](https://user-images.githubusercontent.com/25286516/57198554-9df73e00-6f4a-11e9-9968-8547d9e385ec.png)

![2019-05-05 (9)](https://user-images.githubusercontent.com/25286516/57198556-a0f22e80-6f4a-11e9-8123-2d9e20454c41.png)

**Comment by ywarnier** [comment]
OK, the warnings should definitely not appear, but the problem is due to the fact that IMS/QTI doesn't support all those question types, so we cannot really do much about it. Maybe just ignore them. I'll see what we can do to make that a bit better.
I think just ignoring those other types would already be better.

**Comment by bassuma** [comment]
OK.
Got it.
Thank you for clarifying this question.
We can close the ticket then.
greetings

**Comment by AngelFQC** [comment]
> The issue that multiple choice does not occur is this problem.
> If you add any questions from:
> (Fill blanks or form)
> This is where the problem occurs.
> I tried to replicate on 11.chamilo.org.
> I could not even download.

The question types supported in chamilo are: Unique answer, multiple choice and free answer.  https://github.com/chamilo/chamilo-lms/wiki/Importing-ims-qti

But now, the import/export process only consider this questions types.

**Comment by bassuma** [comment]
Hello.
Is working.
test on 11.chamilo.org
greetings
