### ISSUE TITLE
Announcements bug when using the tags.

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#2916]
Hello.
When you use the Announcements tool.
And use the tags.
The student receives the email with a link.
https://11.chamilo.org/courses/4444/index.php?id_session=0&gidReq=0
When accessing and going to Learning path.
Instead of appearing the courses.
The course page appears.
Thank you

![a1](https://user-images.githubusercontent.com/25286516/58502069-29d04480-815c-11e9-8f38-8c0ea3a37f24.png)
![a2](https://user-images.githubusercontent.com/25286516/58502070-29d04480-815c-11e9-9d6e-dbe9b9e5ed6a.png)
![a3](https://user-images.githubusercontent.com/25286516/58502071-29d04480-815c-11e9-9c8f-8c7f5dcfe277.png)
![a4](https://user-images.githubusercontent.com/25286516/58502072-29d04480-815c-11e9-9ced-2b1ea398fca2.png)
![a5](https://user-images.githubusercontent.com/25286516/58502073-2a68db00-815c-11e9-8c84-d6fbf6d697ab.png)

**Comment by NicoDucou** [comment]
Hi @bassuma 

I just logged in as user torosa13@gmail.com and then opened the link you indicated : https://11.chamilo.org/courses/4444/index.php?id_session=0&gidReq=0
Then I click on learning path tool and click on the only existing learning path and it opened without problem.

Can you check again to see if the problem is solved or tell me how to reproduce the problem now.

Best regards

**Comment by bassuma** [comment]
hi @NicoDucou 
There are two ways of re-judging.
Do not enter as admin
And yes as a student.
You have created the ad and submitted the link.
Login to your account:
study
demo
123456
https://11.chamilo.org/courses/4444/index.php?id_session=0&gidReq=0
Follow the steps above

![2019-07-03](https://user-images.githubusercontent.com/25286516/60599785-6a3b6780-9d85-11e9-8b79-1f0ebcbe88fb.png)

**Comment by NicoDucou** [comment]
I logged in as admin
I just created the course 2916 here : https://11.chamilo.org/courses/2916/index.php
Then I subscribe amann to this course : https://11.chamilo.org/main/user/user.php?cidReq=2916&id_session=0&gidReq=0&gradebook=0&origin=&type=5
Then I create a learningpath here : https://11.chamilo.org/main/lp/lp_controller.php?cidReq=2916&id_session=0&gidReq=0&gradebook=0&origin=
Then I create an add in the course : https://11.chamilo.org/main/announcements/announcements.php?cidReq=2916&id_session=0&gidReq=0&gradebook=0&origin=
I include the tag ((course_link)) and I send this ad to user amann

I logout and connect as user amann and got to see my message.
I have the message from the Ad : https://11.chamilo.org/main/messages/view_message.php?id=220
and I click on the link : https://11.chamilo.org/courses/2916/index.php?id_session=0&gidReq=0
And enter in the learning path tool and click on the learning path and it opens perfectly.

So you probably do something different in the process and you are deconnected or the context is loss because you did something else at some point.

Best regards

**Comment by bassuma** [comment]
Oi @NicoDucou.
Best regards
