### ISSUE TITLE
Chamilo 1.11.10

### ISSUE THREAD

**Issue by Netrixdesigns** [chamilo/chamilo-lms#2943]
Good day

I discovered that the ck editor in this edition is not displaying images, when i checked the source(html) the image is enclosed in the tag but it not displaying in the editor.
please what can i do

**Comment by Netrixdesigns** [comment]
Its not possible to insert images in the course description

**Comment by NicoDucou** [comment]
Hi @Netrixdesigns 
I just verified it on 11.chamilo.org and it is possible to display image in the ckeditor and it is possible to import in the course description as you can see here :
![image](https://user-images.githubusercontent.com/6579268/60657384-90c6d480-9e51-11e9-8493-153dd214c92d.png)

So you have to explain better your problem otherwise we will close the issue

**Comment by Netrixdesigns** [comment]
Good day thanks for your response. Let me upload a screen shot from my own end, it hasnt been displaying images from my end .

**Comment by Netrixdesigns** [comment]
To make it more clear and proof my claim kindly visit
http://politrixtech.com.ng/learncity/linear/chamilo.mp4

to see it in action, its a very small video presentation, its just 3mb

**Comment by Netrixdesigns** [comment]
@NicoDucou
Please did you get my message

**Comment by Coursenligne** [comment]
On a test platform I managed changing the path...
Insert the image, which will "display" as a broken link.
Double click on it and in the URL field, add app in the path.
This should look like http://localhost/chamilo/app/documents.... The /app is missing in the path on my side.
1.11.8 didn't have the issue.

**Comment by NicoDucou** [comment]
You should not need the app in the path because in the .htaccess file there is : 

```
# Redirect all courses/ to app/courses/
RewriteRule ^courses/([^/]+)/(.*)$ app/courses/$1/$2 [QSA,L]
```
In my .htaccess from 1.11.x it's on line 46.

@Netrixdesigns
I also see in your video that you are in a sub folder and not directly using a domain name for your Chamilo (the second is recommanded). When using a sub folder you need to configure it in your app/config/configuration.php file : 
```
// Path from your WWW-root to the root of your Chamilo installation,
// example: chamilo (this means chamilo is installed in /var/www/chamilo/
$_configuration['url_append'] = '';
```

I hope this helps

**Comment by Netrixdesigns** [comment]
@NicoDucou 
Thanks, issue resolved, i did install into a subdomain and it worked
