### ISSUE TITLE
Bug in exercises

### ISSUE THREAD

**Issue by lonesomewalker** [chamilo/chamilo-lms#2945]
**Describe**
When adding an exercise and choosing:
Auto-evaluation mode: show score and expected answers
your exercise becomes "mobile" and all typical question types are gone/not available.

**To Reproduce**
https://11.chamilo.org/courses/MOB0001/index.php

**Expected behavior**
The feature with "mobile ready only" is interesting, but expected would be a self-learning exercise.

**Screenshots**
![mobile](https://user-images.githubusercontent.com/856110/60657775-282c2780-9e52-11e9-8da3-b84f4e9988b7.JPG)

**Comment by AngelFQC** [comment]
An embeddable quiz is a quiz with all its questions of type multiple choice or unique answer or unique answer image. And one question per page. Embeddable means that this quiz can be embeddable in a video with ckeditor ([see the course intro](https://11.chamilo.org/courses/MOB0001/index.php))

In "Musterkurs" course the "Example de test" is configured in scenario mode (self-evaluation, immediate feedback). This mode was not should be embeddable. I changing this in 285759b3151a917b9768dbdfdc227c244d77a124

**Comment by ywarnier** [comment]
I wonder where the "mobile ready only" text comes from (?).
In any case, as Angel explained, this has to do with the inclusion of tests inside videos, so there are wrong expectations here.

**Comment by lonesomewalker** [comment]
Sorry, no.
This happened to SEVERAL installations now.
Nobody fumbles around with embedding or stuff like that.
It happens when you simply create a test, adding some questions and then choose: each question a page.
Reproducable.
Will make a video the next days for that.

**Comment by ywarnier** [comment]
@lonesomewalker 

I went to https://11.chamilo.org/main/exercise/overview.php?exerciseId=104&cidReq=MOB0001&id_session=0&gidReq=0&gradebook=0&origin=
Checked the "New test" config. Looks fine. Entered the test (as an admin). Looks fine. Passed the test. Fine. Checked results. Fine.

![newtest-fine](https://user-images.githubusercontent.com/609839/159361550-29e0409f-2cd8-47b3-9f7d-565deaf0050a.png)
![newtest-fine-answer](https://user-images.githubusercontent.com/609839/159361570-af67af10-4676-4e15-bdd4-0fa4aeb116d8.png)
![newtest-fine-3](https://user-images.githubusercontent.com/609839/159361588-5d3ca502-5449-4b8b-8963-300b8854411b.png)

I'm sorry man, I'm really trying here but so far you're reporting an issue we cannot see...

**Comment by ywarnier** [comment]
I think I finally got it: you're in the first test (Exemple de test) which was configured as an adaptive test and some questions were created in there that have to do with adaptive tests.

**Comment by ywarnier** [comment]
Adaptive tests are not designed the same way (at all) than normal tests, but this stems to the *first* option (not any of the ones below). When creating a test, the "Feedback" option shows 4 options.

![adaptative-feedback0](https://user-images.githubusercontent.com/609839/159362549-199783e1-9492-4bd4-819f-607d39a9aee6.png)

The "Adaptative test with immediate feedback" option is a special one (in fact, it has to be enabled in the administration to appear) which only allows you to pick between two types of questions.

![adaptative-questions](https://user-images.githubusercontent.com/609839/159362803-c0cff2aa-29da-46ae-b0a8-ee81efc54e9d.png)

The first type is the "classical" multiple choice option, but the second one is called "Delineation" and is an extension of the hotspot type.

When starting into one of those tests, you cannot change back afterwards. See form frozen:

![adaptative](https://user-images.githubusercontent.com/609839/159362993-79cb145b-747d-4f5a-81fa-38746cb63b01.png)

This is because the second adaptative question type is incompatible with normal tests. It's designed this way since Dokeos, actually (although it was not easy to enable there).

**Comment by ywarnier** [comment]
At least I believe this is what you are experiencing from your description and the 2 tests in the course you used as example.

**Comment by lonesomewalker** [comment]
@ywarnier I did NOT set this test to be adaptive. The system itself did this.
But i am too tired to explain now. Because also the old ticket just got closed.

Maybe somebody in the future is interested more in this.
