### ISSUE TITLE
[SOLVED] Embedded Videos Not Shown

### ISSUE THREAD

**Issue by farhadbarati** [chamilo/chamilo-lms#2973]
hi,
i created a learning path and add videos to this but in student view only shows a link of video and not play video. my chamilo version is 1.11.10.
thanks
![image](https://user-images.githubusercontent.com/47290937/63219903-34194200-c191-11e9-905b-0da5ea9c4edc.png)

**Comment by opensourcecompany** [comment]
Is the video visible in the document manager?

**Comment by ywarnier** [comment]
Is the video from YouTube?
If so, YouTube blocks embedding of some videos, so if we see we cannot show the video, we show a link instead. If this is the issue, then you should bring this topic to Google. We're only trying to provide "something" for the students to see, where Google prevents it to be shown as an embedded video.

**Comment by farhadbarati** [comment]
no, all videos are local and uploaded to learning path directory.

**Comment by ywarnier** [comment]
OK, then back to @opensourcecompany 's question: is the video "visible" (eye icon opened) when you check it in the "documents" tool?

**Comment by farhadbarati** [comment]
learning path is visible & i uploaded videos in "Create a new document".
![image](https://user-images.githubusercontent.com/47290937/63236914-0269af00-c255-11e9-825e-574118dd7ddd.png)

**Comment by farhadbarati** [comment]
![image](https://user-images.githubusercontent.com/47290937/63237021-7c9a3380-c255-11e9-9d63-012f96fd2e83.png)

**Comment by ywarnier** [comment]
OK, I think I know what might have gone wrong. Uploading your video through the learning paths editor offers you two ways of doing so (normally): on the left bar of the file upload window, you have a directory called "My Files" and another one by the name of the course. You have to use the one by the name of the course and put your video in a directory somewhere inside the course. This will put it in the "documents" tool of the course, where you can then, later on, check the visibility.

In the documents tool:
The folder can be invisible so the students with access to the documents tool don't see it there, but the video file itself has to be visible, otherwise Chamilo security's default algorithms consider it is not accessible to students.

It is a bit complicated to explain like this, but hopefully with these hints you can find out how it works.

**Comment by farhadbarati** [comment]
thanks for reply. i did that you said but unfortunately problem not solved.

![image](https://user-images.githubusercontent.com/47290937/63259281-39f74c00-c293-11e9-9ca1-b1915ab7c60a.png)

![image](https://user-images.githubusercontent.com/47290937/63259342-5a270b00-c293-11e9-9789-ade1f352098d.png)

**Comment by ywarnier** [comment]
Is the HTML document (001.html) also visible in the documents tool?

**Comment by farhadbarati** [comment]
i will check it tomorrow and i let you know.
thank you.

**Comment by farhadbarati** [comment]
yes,it is visible.

![image](https://user-images.githubusercontent.com/47290937/63399460-da5d8580-c3e5-11e9-8166-ddd5cc0fe680.png)


![image](https://user-images.githubusercontent.com/47290937/63399431-bf8b1100-c3e5-11e9-8154-2b3fc096c1a6.png)

**Comment by ywarnier** [comment]
@jmontoyaa any idea on this one?
The HTML page doesn't seem to load at all in the learning path...

**Comment by farhadbarati** [comment]
is there any way to solve a problem?

**Comment by opensourcecompany** [comment]
What does the error log of your webserver say when you open this page?

**Comment by jmontoyaa** [comment]
I cannot reproduce the error.
I created a document and I added a mp4 video:

login/pass: admin/admin

https://11.chamilo.org/main/lp/lp_controller.php?cidReq=AIKENJULIO&id_session=0&gidReq=0&gradebook=0&origin=&action=view&lp_id=111&isStudentView=true

**Comment by opensourcecompany** [comment]
Maybe we start with the basics:
- wich operating system?
- which webserver?
- which PHP version?
- all dependencies met?

**Comment by AngelFQC** [comment]
Maybe the portal is on https and the document URL is on http

**Comment by farhadbarati** [comment]
sorry for answering with delay.
all URL is https.
i installed chamilo on Ubuntu 18.04,PHP 7, Apache 2.4.
i also installed chamilo in my lab and this problem doesn't exist on my test environment!

**Comment by ywarnier** [comment]
What is the context difference between your lab and your test environment?

**Comment by farhadbarati** [comment]
there is no major difference,videos format are mp4.

**Comment by farhadbarati** [comment]
Inspect of page with problem:

![Inspect_Problem](https://user-images.githubusercontent.com/47290937/63763541-2aeb4c00-c8da-11e9-83fe-e721dbbbf669.JPG)

this is Inspect of correct page:

![Inspect_Correct](https://user-images.githubusercontent.com/47290937/63763581-40f90c80-c8da-11e9-9731-13aab3c2b3c0.JPG)

**Comment by Coursenligne** [comment]
I may not be accurate on this one, but it sounds like the image issue I have. The situation is slightly the same.
I know this is not completly acceptable, but it's worth trying it..
In Document (the folder icon from the course, you amys see as a teacher), locate (or even create) the suitable directory. From here, upload the resource, and then into the LP, point out the uploaded resource.
It worked my side, even though it is just an overcome and not the expected behavior.
I hope this helps.

**Comment by farhadbarati** [comment]
i solved my problem. the problem is:
Root_web address. before i changed it to "/" & when i change it back to ip address,the problem is solved.
i changed it because i want to system in my lan access by local IP address and outside user access by WAN IP address (NAT). is there any option to that scenario?
thanks for replying.
special thanks to Drear Yannik.

**Comment by ywarnier** [comment]
Not directly, but maybe you can play with this and find something to extend from it: https://beeznest.com/blog/2013/01/15/answering-to-different-addresses-with-chamilo/

**Comment by farhadbarati** [comment]
i changed Root_Web as it said in the link and it works!
thanks a lot Yannick.

**Comment by Roger-Sa-H** [comment]
Hi, farhadbarati.
How did you solve the problem, can you help me?
