### ISSUE TITLE
track_e_downloads cleaning-archiving

### ISSUE THREAD

**Issue by marshel** [chamilo/chamilo-lms#2975]
**Is your feature request related to a problem? Please describe.**
Database table track_e_downlodas gets bigger and bigger with info that is just space hogging, for example, SCORM packages that contains small images and UI elements, animations... got all logged, causing the database inflation in size and possible slowdowns.
In my use case, a 10k users system in 1 month got a 13 million rows.

**Describe the solution you'd like**
A cron to or archive on a file/other table or, truncate the data beyond XX days.

**Additional context**
This table seems only a way to get statistical data about what tools are being used by students and this resources it uses are too expensive for just that. Its use should be analysed for future. Maybe another database or no SQL database would fare better for this kind of task.

**Comment by opensourcecompany** [comment]
+1

**Comment by Coursenligne** [comment]
I do agree :)

**Comment by ywarnier** [comment]
I have added the main/cron/archive_table_records.php script.
It can only be started from the command line (or a cron script that doesn't use HTTP) and is fairly easy to use:
* open the script and finetune $tables, $threshold and $archiveNumber
* save and exit
* execute "php archive_table_records.php"

Warning: this will indeed remove the $archiveNumber number of records from the original table(s) to the new archive table(s) suffixed with the current year number.

For example, if only "track_e_downloads" is present in $tables, the script will:
* check the existence of "track_e_downloads_2020", and otherwise create it
* check if there are more than $threshold records in each table (otherwise it doesn't care and moves on to the next table)
* copy the first $archiveNumber records from the track_e_downloads table into the track_e_downloads_2020 table
* delete the same records from the original track_e_downloads table

There is enough space to improve this script in the future, but for now I believe it fills the need described in this issue.

Please give us feedback in the next 7 days or this issue will be considered closed.

**Comment by ywarnier** [comment]
Don't run it before you configure it, as you might accidentally move 10M records...
