### ISSUE TITLE
Time Control not works correctly

### ISSUE THREAD

**Issue by farhadbarati** [chamilo/chamilo-lms#3012]
hello
i created an exam and i want to limit this exam to 30 minutes and i Enabled time control and set Total duration in minutes of the test 30 but when i start test, exam time remaining start at 59:59instead of 30:00. is there any solution for this problem?

**Comment by farhadbarati** [comment]
i think start time is not 00:00:00. how can i check that?

**Comment by Coursenligne** [comment]
You may want to check the server date/time.
Especially on virtualized solution, where you can have a difference between the virtualized server and the physical server.
This can create such an issue.
If you are not virtualized, you shouldn't occur this.
I then have to make a double check, but I didn't have this.
Could you reproduce on 11.chamilo.org?

**Comment by farhadbarati** [comment]
my problem is the same as this:
https://support.chamilo.org/issues/6886

**Comment by farhadbarati** [comment]
the problem is related to system Timezone.

**Comment by ywarnier** [comment]
Hi @farhadbarati sorry for the delay answering. Yes, we have a big issue with the Indian timezone(s), in it is only an half-hour change. We do not, at this time, support those half-hour. We hope to be able to support it in version 2.0. The issue is that the default PHP library for timezones does not support half-hours. To support them, we need to use another library that has a considerable impact in performances, and we need to use it everywhere

**Comment by farhadbarati** [comment]
Thank You.
