### ISSUE TITLE
End Test button at end of Exam (random questions)

### ISSUE THREAD

**Issue by farhadbarati** [chamilo/chamilo-lms#3013]
when i create Exam with random questions and number of questions are less than all questions, at the end of exam "Next question" button appear instead of "End test" button. how can i solve this problem?

**Comment by NicoDucou** [comment]
I just reproduced the problem here

- in 1.11.x : https://11.chamilo.org/main/exercise/admin.php?exerciseId=150&cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=

- in master : https://2.chamilo.org/main/exercise/overview.php?cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=4

**Comment by farhadbarati** [comment]
is there any solution for this bug?

**Comment by farhadbarati** [comment]
thanks a lot. the bug is resolved.
