### ISSUE TITLE
[question] JS and Scorm on Chrome 80

### ISSUE THREAD

**Issue by marshel** [chamilo/chamilo-lms#3076]
**Describe**
https://rusticisoftware.com/blog/scorm-and-aicc-courses-break-from-chrome-80/

Chrome 80 (releases on feb/2020) changes the unload and beforeunload behavior on javascript which may affect SCORM related progress and results.

Is Chamilo aware and ready for this?

**Comment by ywarnier** [comment]
I tried Chamilo (the 1.11.x branch) with Chrome 80 and a simple SCO SCORM package and could get back inside at the point where I left it (which was not the end of the SCO) after:
- returning to the course homepage, then unlogging and relogging
- loading another URL
- closing the browser window

All cases worked fine, so I suppose we were Chrome 80-ready already...

I remember vaguely removing the "synchronous" messaging (replacing by asynchronous) a few years ago because it was locking the browser. That must have done it.

I'm closing this issue because I believe my test case is enough, but feel free to correct me if you detect anything wrong.
