### ISSUE TITLE
Google maps - change the address with the City only

### ISSUE THREAD

**Issue by mesoshqip** [chamilo/chamilo-lms#3180]
If you add the full address like the picture below:
![address](https://user-images.githubusercontent.com/59404111/79030105-c2ff2280-7b97-11ea-8944-aff4efc22c18.png)

google api will find the right address, but is changing the value in only the City and State. After saving the data of address are lost.
![Address2](https://user-images.githubusercontent.com/59404111/79030158-ffcb1980-7b97-11ea-9617-3216e46bdf53.png)

**Server
 - OS: Linux Ubuntu 18.04
 - Version of Chamilo: . 1.11.10
 - Version of PHP:  7.2

**Comment by ywarnier** [comment]
@NicoDucou do you know if we did something so that it only saves the city?

**Comment by NicoDucou** [comment]
Hi @mesoshqip 

When we implemented the social map (/main/social/map.php) we defined that the geolocalization would be  only at a city level to avoid exact localization of the learners. We also changed the management of the geolocalization field so that it only show to the user the city and country and cut the rest of the element (for exemple coordinates).
The integration of the social map was done by this commit https://github.com/chamilo/chamilo-lms/commit/f875486cd22fc56fa197a93b7d950a443545b063 but I can not find in this commit how we limitated the geolocalization to only the city. But it should be close to this commit. In fact it was done in this commit : 
You can see in the function  getLocalizationJavascript on line 451 of main/inc/lib/extra_field.lib.php that we are registering only the city and the country so if you want to modify this treatment you can look around here.

So this is not a bug, I let you modify it if you need it in a particular case.

Best regards.
