### ISSUE TITLE
Change Chamilo files storage for courses to be on Amazon S3 ?

### ISSUE THREAD

**Issue by tamertest** [chamilo/chamilo-lms#3199]
Is there any guide where and what I can change in Chamilo configurations to let the folders/files of courses, assignments... get stored on Amazon S3 and not on the local server?

**Comment by 22phuber** [comment]
☝️ I'm Interested in the answer of this question as well. 
There is also the possibility to configure elfinder to use AWS S3 as storage, but i don't know how to write the appropriate Driver/Connector. => https://github.com/chamilo/chamilo-lms/issues/3087

**Comment by ywarnier** [comment]
Hi there,

This is planned for Chamilo 2.0 for the end of this year (2020), hopefully.

There is not quick answer to this. There are many places in Chamilo 1.11 where we simply use file_put_contents() or fwrite(), without any particular abstraction layer.
This means that, in order to enable a change of configuration to use the REST web services required by S3 for every read or write, we would need to search for all of them (I would estimate this to be in the hundreds but not the thousands, but there are also calls to check files and directories permissions, etc) and replace them by a call to a common function, and then (finally) we could hack that function to use a web service that points to S3.

I know the end of 2020 still looks far away in the current pandemic context, but sincerely, I would recommend waiting for then, and possibly help us out when we start rolling out a developable version of Chamilo 2.0... (which should be around September).

This is related to this issue (although it doesn't look like it is): #2321

**Comment by ywarnier** [comment]
I should note we recently tried AWS EFS to avoid the S3 issue, and EFS has awful performances (there is a very long thread on EFS performance in the AWS forums). It seems to work for websites with a large proportion of static/unmodifiable files that can easily be cached, but not for a web application where every user has different accesses as Chamilo.

**Comment by ywarnier** [comment]
Implemented in #2321
Closing.
