### ISSUE TITLE
Quiz : "Questions ordered" option using categories doesn't work properly (questions are not ordered)

### ISSUE THREAD

**Issue by tanchon** [chamilo/chamilo-lms#3265]
**Describe**
Hi,

I defined questions grouped by categories (see here an exercise i created for testing : [11.chamilo.org : exercise with categories](https://11.chamilo.org/main/exercise/admin.php?cidReq=COURSTANCHON&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=296)).

When i select "random" mode (in "question selection type"), some options doesn't work as they should :

1- "Ordered cat.alpha with questions ordered"  : Categories appear in alpha order (it's OK). But **questions are not ordered** ! Whatever the options selected in this menu below, it never works : 
![Capture4](https://user-images.githubusercontent.com/24507698/82751653-fc42c900-9db8-11ea-9574-8938655c5c92.JPG)

2- "Random categories with questions ordered" : OK for categories. But **questions are not ordered** (whatever the options selected concerning the categories selected).

3- "Ordered categories alpha with random questions " : everything is ok !

4- "Random categories with random questions" : it seems ok, except with these options (see below)
![Capture5](https://user-images.githubusercontent.com/24507698/82751778-ea155a80-9db9-11ea-9ea2-731144a784bb.JPG)
In this case, questions appear ordered as they are classified by the trainer in his list. Questions are not randomized.

**To Reproduce**
1. Create an exercise 
2. Create categories for questions
3. Create questions in categories
4. Choose "random - using categories" option (in the exercise_admin.php page)
5. Select one of the 2 "questions ordered  options
5. Execute the exercise 
6. Questions are never ordered in their categories.

**Expected behavior**
When a trainer selects "random using categories" and the "questions ordered", questions should be ordered properly.

**Additional context**
I have the problem with my Chamilo 1.11.10 platform. Reproduced here : [11.chamilo.org : exercise with categories](https://11.chamilo.org/main/exercise/admin.php?cidReq=COURSTANCHON&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=296)).

Thanks !

Tanchon

**Comment by carlangas159** [comment]
Hello @tanchon ,

I have noticed the exercise you are commenting on and I notice that they do not have assigned categories,
![image](https://user-images.githubusercontent.com/18097392/88438119-8b765800-cdcd-11ea-8474-4c8f00326d58.png)

I tried to do the test with another exercise that I did [https://11.chamilo.org/main/exercise/admin.php?cidReq=CURSO5CATEGORIAS&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=440](https://11.chamilo.org/main/exercise/admin.php?cidReq=CURSO5CATEGORIAS&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=440) 
![image](https://user-images.githubusercontent.com/18097392/88438458-6b936400-cdce-11ea-8a8c-13cd25ccc9f5.png)

![image](https://user-images.githubusercontent.com/18097392/88438969-83b7b300-cdcf-11ea-9bd7-fdd2fd0eb6eb.png)



I tried each of the ordering methods of the questions and I couldn't replicate the error you report.

The ordering method is done at the time of starting the test, after it has already been started the order of the tests is not modified even if it is changed by the exercise settings. Therefore, it is necessary to finish the test and try again with the same user.

The exercise you are commenting on cannot be ordered by categories because it does not contain any. Could you try to carry out an exercise where we can replicate the error you are commenting on? Or could you try to check the exercise that I put and tell us?

**Comment by tanchon** [comment]
Thanks Cardangas159 for your answer.

I don't know what happens with my categories. 

I've just defined categories, as you can see below  
![Capture - Copie](https://user-images.githubusercontent.com/24507698/88451637-87dbe300-ce58-11ea-851b-9d10a5095f0b.JPG)

I can confirm everything i reported in my first post. Questions are never ordered as they should. To verify that, you have to make the test until the end, because, sometimes, the first questions are correctly ordered, but not that last questions.

Thank you.

**Comment by ywarnier** [comment]
My first reaction is that, if you will select all of them anyway, you should probably not select them by category, unless there's some side effect you want to use (like showing the final results table by category). Just select random and select the option to use all questions.

In any case, I am not able to reproduce the issue in the "copy" of the exercise here: https://11.chamilo.org/main/exercise/exercise.php?cidReq=CURSO5CATEGORIAS&id_session=0&gidReq=0&gradebook=0&origin=&

I've also tried with your quiz at https://11.chamilo.org/main/exercise/admin.php?exerciseId=296&cidReq=COURSTANCHON&id_session=0&gidReq=0&gradebook=0&origin= and changed the config to show the results and the question category (although it was already in the question name).

I'm not sure how you do it, but we need a more precise test case to be able to reproduce it ourselves (and fix it).

**Comment by tanchon** [comment]
Hi,

I made a video with your exercise : https://11.chamilo.org/main/exercise/exercise_admin.php?cidReq=CURSO5CATEGORIAS&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=442

Click here to see the video  : https://youtu.be/7XXFH_8Hqsg

As you can see in the video, i selected "ordered cat. alpha with questions ordered"... I only made the video in this configuration but i can reproduce every issues i mentioned in my first post. May be i didn't understand somesthing with "questions ordered" ?...

In the video, we can see that categories are correctly oredered : (1 => 2 => 3).

But into categories, questions are not ordered : 

Cat.1 : 2 =>3 =>5=>4=>1 (it should be : 1=>2=>3=>4=>5)
Cat.2 : 5=>4=>1=>2=>3  (it should be : 1=>2=>3=>4=>5)
Cat.3 : 1=>4=>2.... (it should be : 1=>2=>3...)

Thanks.

Tanchon.

PS : @Yannick : in some cases, we need to have every questions AND every categories selected, but with questions grouped by categories (because there are logical links between questions). In this case, if (for example) we want that all categories appear randomly with all questions ordered we cannot select random=>use all questions as you suggest (because questions wouldn't be grouped as the teacher want).

**Comment by ywarnier** [comment]
Yes, I see I misunderstood your issue description. We will be checking this soon.

**Comment by ywarnier** [comment]
@AngelFQC could you review this and close if it solves the issue, please?

**Comment by tanchon** [comment]
I made some quick tests with my quiz : : 11.chamilo.org : [exercise with categories](https://11.chamilo.org/main/exercise/admin.php?cidReq=COURSTANCHON&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=296)

It seems to be ok :-)  It's great, because it's a very useful functionality !

Thanks

Tanchon
