### ISSUE TITLE
 Login failed for student user

### ISSUE THREAD

**Issue by mauriciosabbi** [chamilo/chamilo-lms#3292]
**Describe**
When you log in as a student, the page will get lost in the link below:
https://soscorpoead.com.br/src/course_panel.php

and shows the message file not found

after that, you cannot go back to login. just clearing cookies

**To Reproduce**
1. Go to 'www.soscorpoead.com.br'
2. Typing 'login: visitante password: 123456'
3. Click on 'login'

**Expected behavior**
Access to courses within Chamilo is expected

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. chrome(83.0.4103.97 64-bits), firefox( 77.0.1 64-bits)] 

**Server
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Version of Chamilo:  [e.g. 1.11.8 ]
 - Version of PHP: [e.g.  7.3 ]

**Additional context**
This error came up with another one already reported here, see #2714

**Comment by ywarnier** [comment]
Hi @mauriciosabbi 
#2714 doesn't seem related to this.
Your issue seems to be related to a redirection that you might have configured somewhere in Chamilo before, but nothing sends the user to src/course_panel.php by default.
The only "src/course_panel.php" is in the "buy_courses" plugin, the one that allows you to sell courses, so I would suggest you review whatever you configured in this plugin to avoid this.

**Comment by ywarnier** [comment]
I think there used to be an issue like this in the past, and I see you use 1.11.8. This might be related. If you're still testing the plugin, I would uninstall the plugin, but be aware that this will destroy the plugin data in the database (so take a backup and don't do it on a system with sales already registered).
Once 1.11.12 is released, upgrade 😉
