### ISSUE TITLE
Can't assign users to an HR manager

### ISSUE THREAD

**Issue by CrowCakes** [chamilo/chamilo-lms#3304]
### Current behavior / Resultado actual / Résultat actuel
When attempting to add an HR manager to a user, the admin is taken to a page where they have to select an HR manager from a list of active ones. However, there are no HR managers listed, even though there are actives ones on the platform. Clicking on "Send message" will still be allowed, but seemingly nothing happens after.

### Expected behavior / Resultado esperado / Résultat attendu
When attempting to add an HR manager to a user, the admin is taken to a page where they have to select an HR manager from a list of active ones. Admin is able to search for HR admins, then complete the proess by clicking "Send message."

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
On Administration -> User list, select any non-HR manager user. Click Add HR manager to user icon, then attempt to search for an HR manager.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.10

PS:
I'm exploring the HR manager role in search of a trainer auditing tool inside Chamilo. Is there one already?

**Comment by carlangas159** [comment]
hi @CrowCakes 

To assign a HR manager to a user, you must enter the list of users from administration

![image](https://user-images.githubusercontent.com/18097392/88091317-865aa400-cb54-11ea-9317-cae5569eb618.png)


When you find the desired user, you should look for the blue icon with a white i (information)

![image](https://user-images.githubusercontent.com/18097392/88091392-983c4700-cb54-11ea-88c3-59e30c7456d4.png)

Then click on "Add HR Manager to user" (the icon with two people and an asterisk)

![image](https://user-images.githubusercontent.com/18097392/88091561-d6396b00-cb54-11ea-9dba-0a2e03d2a378.png)

This will send you to the selection of HR managers where you can search for and assign the HR managers.

![image](https://user-images.githubusercontent.com/18097392/88091799-2e706d00-cb55-11ea-8e78-cbc047517222.png)

This will adjust the director of human resources to the established user, it would show something similar to this

![image](https://user-images.githubusercontent.com/18097392/88092638-69bf6b80-cb56-11ea-84f2-5cc4e6671c45.png)

You must have the names or code of the HR user to be able to search for it in the drop-down list, since the list performs a search in the database to verify the existence of said user.

**Comment by ywarnier** [comment]
Closing because this seems to be a misunderstanding. Feel free to re-open or comment if this doesn't solve your issue @CrowCakes

**Comment by CrowCakes** [comment]
I've followed the steps until searching for the HR manager to assign. Please see the following screenshots:

This is the code of the HR manager:
![image](https://user-images.githubusercontent.com/21997146/88123077-bbbacc80-cbfc-11ea-9bd1-f13ef5ddbd72.png)

Attempting to assign this HR manager:
![image](https://user-images.githubusercontent.com/21997146/88123139-d8570480-cbfc-11ea-87fb-7499227722de.png)

**Comment by carlangas159** [comment]
Can you search "manager, hr"?  I mean, try to search by names or login username

**Comment by CrowCakes** [comment]
> Can you search "manager, hr"? I mean, try to search by names or login username
It worked. However, the page behaved strangely, as it displayed first "The results could not be loaded" before displaying the name of the HR manager.
![image](https://user-images.githubusercontent.com/21997146/88126783-dc872000-cc04-11ea-82f8-ce82ad663f40.png)



I've also found an alternative solution to this, but it only applies to Learners.

1) From Administration, go to User List
2) Find an HR Manager, then click the Assign user icon
3) Assign as many Learner users as you would like
4) When checking the Learners' profile pages, an HR manager list should appear above their profile window
