### ISSUE TITLE
Course Backup doesn't work properly (full and partial backup)

### ISSUE THREAD

**Issue by tanchon** [chamilo/chamilo-lms#3322]
**Describe**
Hi,

I tried to use the backup features in order to export some exercises from one platform to another. But it fails, even into the same platform :
- it seems to export correctly the course into a zip file
- but when importing the file into another course, it fails : the process returns to the first menu without importing any exercise.

**To Reproduce**
1-Create a partial ou full course backup from a course
2-Trying to import it into another course.
3- It never works :
- it fails when i try to export a full course or some exercises of the course from my 1.11.10 platform to the 11.Chamilo.org platform.
- it fails i try to do that from 11.chamilo.org to 11.chamilo.org as you can see with the video here :
https://youtu.be/ERGxQHJF8pU
As you can see, even when i select only one exercise, it fails.

I tried to use this process in order to make an export of some exercises with fill blanks  (as i mentioned here, it is not possible to do that with qti exports : #3277)

**Expected behavior**
The export process should work properly.

**Screenshots**
https://youtu.be/ERGxQHJF8pU

**Server
I tried to do the backup from my 1.11.10 platform to 11.chamilo.org and from 11.chamilo.org to 11.chamilo.org (with this course : [11.chamilo.org](https://11.chamilo.org/courses/COURSTANCHON/index.php)).

**Additional context**
As Qti exports doesn't support all types of exercises, i don't see any easy way to export all types of exercises from one platform to another.

Thanks.

Tanchon.

**Comment by ywarnier** [comment]
I've tried the case you present in the video. The exercise you are using in the example contains a lot of volume, which is due to you using images in base64 format (dragging-and-dropping images from somewhere else into the editor withouth saving the image as an individual object on disk).
This causes the Chamilo backup file (course_info.dat, in your zip) to be extra-heavy (34MB). This seem to either cause an issue of memory at the time of "decompressing" (actually the term is "unserializing") the file, or the file contains some character that breaks the internal "serialization" format of PHP.
I tried opening the file with PHP's unserialize() (through an unserialize.php script) on my computer with more than 1GB of RAM for PHP and memory was not an issue.
However, an error message appears that suggests the second possibility is correct:
```
PHP Notice:  unserialize(): Error at offset 0 of 43864604 bytes in /tmp/unserialize.php on line 5
```

This suggests the format we use for the backup can have issues with some content format, but the only way to properly fix this would be to somehow change the backup format, which would essentially break compatibility of the backup with all other versions of Chamilo. This is not a change we are likely to do now.

I suggest you simply upload the images in the documents tool in your course, then load those images in your question text from the internal image. This will reduce the size of your course backup, reduce the load on the database and it is very likely to fix your issue of backups.

Thanks for the very detailed report. It really helped us find more information about the "why".

**Comment by tanchon** [comment]
Thank you Yannick for the feedback. I already noticed that base64 images seemed to be the cause of some issues (#3286) or disadvantages (#3273).

I've tried to encourage trainers not to use these images but it is not enough : when they use Firefox, it's almost a pavlovian reflex to do the ctrl+c / ctrl+v which leads to the base64 format. 
And some of them prefer to use it, even if i don't recommend it (it's an easy way to insert images).

That's why i tried to insert a 'blockimagepaste' plugin into ckeditor using informations here : [blockimagepaste](https://stackoverflow.com/questions/6582559/ckeditor-preventing-users-from-pasting-images/23101048#23101048). 

So i paste this folder ([blockimagepaste.zip](https://github.com/chamilo/chamilo-lms/files/4874683/blockimagepaste.zip)) in : /web/main/inc/lib/javascript/ckeditor/plugins
and i add a reference to it into the main.js.tpl file. 
![main js tpl - Copie](https://user-images.githubusercontent.com/24507698/86529740-5f914200-beb3-11ea-94f3-a59f6b0a1cd9.JPG)
But it doesn't work. 

Even if i add the plugin folder here (/web/app/Resources/public/assets/ckeditor/plugins) and here (/web/web/assets/ckeditor/plugins) and adjust the config.js file (adding this line : config.extraPlugins = 'blockimagepaste';) it doesn't work.

Do you know if there is a way to block image paste by ctrl+c / ctrl+v in Chamilo ?

Thanks !

Tanchon

**Comment by ywarnier** [comment]
@lcubas, please check if you can effectively prevent pasting images in CKEditor through the CKEditor configuration options. The last comments from @tanchon should help you out.

**Comment by ywarnier** [comment]
OK, nervermind this one for 1.11.12. Let's solve it but for a later version.

**Comment by ywarnier** [comment]
The commit above solves the issue by adding a plugin to CKeditor preventing copy-paste of images.
We couldn't add it in time in 1.11.12, but you can update from Git (`git pull origin 1.11.x`) and enable it adding this line in app/config/configuration.php:
```$_configuration['ck_editor_block_image_copy_paste'] = true;```

**Comment by tanchon** [comment]
Thanks a lot for this very useful plugin ! (in one of my 1.11.12 platorm, it works perfectly as it ; in another 1.11.12 platform, i had to rename the plugin in order to use it,  because ckeditor refused to open).

Now, everything is ok for me :-)

Tanchon
