### ISSUE TITLE
Visibility of a module/lesson (with prerequisite)

### ISSUE THREAD

**Issue by LolaCapitani** [chamilo/chamilo-lms#3340]
Hi Chamilo development crew!
I'm Lola and I'm new at GitHub. I don't really know how to use it, and I wish I wasn't wrong!

I'd like to propose a new feature. Actually a feature that's there but it's hidden! I would like to put it in the control panel.

In summary, it would be useful that in the lessons path, lessons with prerequisites are visible and disabled.
In the Chamilo forum there was a discussion about it, with the contribution of Eric and Laura.

https://forum.chamilo.org/viewtopic.php?f=52&t=11187

Thanks!

Lola
(=^ ◡ ^=)

**Comment by ywarnier** [comment]
Hi @LolaCapitani 
Features like `$_configuration['show_prerequisite_as_blocked'] = true;` are actually *temporarily* in the configuration.php file. They are there because we do not modify our database between minor versions. As soon as we move to a next major version (which is planned to be 2.0 this year), those settings will move from the configuration file directly to the interface. So there's nothing to be done here. It's already planned (actually it's also already done but version 2.0 is not ready yet), so I'm closing this issue.

**Comment by LolaCapitani** [comment]
Thank you!
