### ISSUE TITLE
Restore admin account

### ISSUE THREAD

**Issue by shabsshab** [chamilo/chamilo-lms#3449]
Issue : admin user got deleted from both Both New insance and master Chamilo portal.

I have enabled Virtualizor in Chamilo and setup mulit access url also.
New insance created successfully and added multi access url
Both New insance and master Chamilo was working correctly.

Steps to reproduce .
Goto : Administration-->Multiple access URL --> Branding -- Add user to this url.
I have moved all users except Admin to right panel and submited

See the snapshot taken from different chamilo portal and the issue was happened in this window:  https://prnt.sc/tyur8n

after  that got message that All users added ( with thier names ) and Admin Deleted.
Now i cannot login with Admin
 
1. Admin account  should not delete at any case
2. How can we restore admin account ?
3. Which is the table name in the DB and i can insert the admin from SQL. and what are the parameters to insert the admin data into table

 - OS: Centos 7
 - Version of Chamilo: 1.11.10
 - Version of PHP: 7.3

**Comment by ywarnier** [comment]
Hi @shabsshab 
This combination of vChamilo *and* multi-URL has never been tested before. I wouldn't recommend using it in production (it goes a bit too far in increasing the complexity of the whole system). There's no improvement in this regard in v1.11.12 anyway, so that wouldn't solve the issue.

1. fair enough, but we will need more research to fix it because it is a complex case that we will not setup in a community-support context (feel free to contact an official provider for a swift fix)
2. Creating a user account from scratch is a bit difficult. Instead, I would suggest you use an existing user account (non-admin) and convert it to admin. You can do that by adding the user.id of that user in the admin.user_id table.field, then making sure the user is also in the access_url_rel_user table with url_id 1. If you don't have a user from which you remember the password, you can check the wiki here, there's a page describing the password creation process for the default bcrypt method
3. already answered in 2.

**Comment by shabsshab** [comment]
Actually admin  user is there in the table and it was removed from access_url_rel_user table with url_id 1
I inserted a new record with admin user id for url_id 1
Now its work.

Thank you

**Comment by ywarnier** [comment]
Good to know! Thanks for reporting your fix for the rest of the community.
