### ISSUE TITLE
Users Active after registration despite setting - After approval 

### ISSUE THREAD

**Issue by kemoche** [chamilo/chamilo-lms#3454]
**Describe**
I had set registration requires approval - Registration ->After approval.
I have noticed that now the users have their account approved upon registration!
Also after the registration, the the below error
------------
This page isn’t working right now
domain..ac.ke can't currently handle this request.
HTTP ERROR 500
------------

**To Reproduce**
1. Go to 'Signup'
2. Fill all the details
3. click register

**Expected behavior**
A redirect to homepage.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Waterfox 20200702, Microsoft Edge Version 84.0.522.59 (Official build) (64-bit)

**Server
  - OS Linux CENTOS 7.8 64 bit
  - Version of Chamilo: 1.11.12 (Updated from 1.11.10)
  - Version of PHP: 7.2

![registration settings](https://user-images.githubusercontent.com/69464866/90479469-66a8a280-e137-11ea-991c-c0936e110033.jpg)
![registration](https://user-images.githubusercontent.com/69464866/90479476-6ad4c000-e137-11ea-8269-f1438bde6ab5.jpg)
**Additional context**

**Comment by ywarnier** [comment]
I don't have this issue. It sounds to me like your Chamilo installation might be broken because you already reported 2 issues in a short time that are not present as far as I can see. Could you put your server in "test mode" (one of the first settings in the first page of settings) and try those actions again, so you get a little more feedback from your system? (try not to enable it for long on a production system because it reveals abusable information).

**Comment by kemoche** [comment]
Resolved - a plugin - clockworksms - was the issue. Disabled and all is well.
Thanks for your time.
