### ISSUE TITLE
Bug with the "sort my courses" link (due to "visibility" of courses)

### ISSUE THREAD

**Issue by tanchon** [chamilo/chamilo-lms#3494]
Hi

**Describe**
When an user wants to sort his courses, it is not possible. He can create his categories but he cannot put his courses into these categories

**To Reproduce**
1. Create some courses
2. Click on 'Sort my courses' on the left of the screen
3. Create categories for courses
4. Try to put courses into categories created by the user : it is not possible (only one course appear , not the others...)

**Expected behavior**
To have the possibilty to affect all courses into categories created by the user in the "Sort my courses" Menu.

**Screenshots**
We can see 3 courses...
![Capture1](https://user-images.githubusercontent.com/24507698/92282353-b4762680-eefd-11ea-915d-9869407a7dd8.JPG)

But when we want to sort courses, only one course appears...
![Capture2](https://user-images.githubusercontent.com/24507698/92282363-b8a24400-eefd-11ea-8c89-7fce88677715.JPG)

**Server
Chamilo 1.11.12 (Linux) - new installation

**Additional context**
In another Chamilo platform, it works perfectly (1.11.10)

**Comment by tanchon** [comment]
Hi,

I can confirm that in Chamilo 1.11.10, it was possible to sort the course list : the "sort my course list" (in userportal) worked well.
But with 1.11.12, there is a problem because when we are in the menu, some courses are missing... The last time i tried, no course was proposed (as the user has more than 20 courses in his course list).

This is very annoying, because there is no logic order with the course list : #1655

So, when the user has a lot of courses in his list... he is lost because it is very difficult to find some courses if teachers didn't give a pertinent name to the course !

Thanks.

Tanchon

**Comment by carlangas159** [comment]
hi @tanchon 

i try to replicate this scenario,

I have created a user and added it to 3 courses, then I went to my courses page to order them.

![image](https://user-images.githubusercontent.com/18097392/93095305-8a90d280-f668-11ea-8300-0b20bd1c1903.png)

I have added a course to each category, so that one can be left uncategorized

![image](https://user-images.githubusercontent.com/18097392/93096460-093a3f80-f66a-11ea-9ec8-0831a929b1ab.png)

I have returned to my courses and I observe that they are distributed in their category, however I notice that I have a course called "Cruso pruebas categorias" which I am NOT registered and leaves first, I have it highlighted

![image](https://user-images.githubusercontent.com/18097392/93096636-41418280-f66a-11ea-80b1-e02e3bf74d35.png)

You will be able to realize that "Borrable" is only at the end of the categories, as it is not associated with the categories

At the moment I cannot replicate your scenario, **is it possible that the 3 courses you refer to are highlight and you are only enrolled in "Pas de catégorie de cours"?**

**Comment by tanchon** [comment]
Hi @carlangas159 ,

With my 1.11.10 Chamilo, everything works as you described (no problem).
With my 1.11.12 Chamilo, on the same server, with the same parameters, it is possible for me to create categories in "sort_my_courses.php"  (and then to move or delete it) but now, no course is proposed in the "sort_my_courses.php" page.

Here, is my course list (7 courses) in my 1.11.12 Chamilo :
![My course list](https://user-images.githubusercontent.com/24507698/93134256-ca8f9e00-f6d8-11ea-8440-6560be8dafb6.JPG)

Here is the sort_my_courses.php page, for the same user (me) : no course appears...
![Sort my courses](https://user-images.githubusercontent.com/24507698/93134393-075b9500-f6d9-11ea-96bd-594d76032abc.JPG)

You can see that now, no course appears in "Pas de catégorie de cours" ("No courses category") ... but at the beginning, 10 days ago, one course was proposed (see my first post : only "cours de test", was proposed among 3 possible courses...).

I tried to create a student account and to enrolled him in some courses : it is the same problem => no course appears when he wants to access to "sort_my_courses"... Every users seem to have this problem.

Except this issue, I precise that my 1.11.12 platform works very well... No problems with courses or users...

Thanks.

Tanchon.

**Comment by tanchon** [comment]
I tried to reproduce this issue on https://11.chamilo.org/index.php, but the "Sort my courses" link doesn't appear.

**Comment by tanchon** [comment]
Hi @carlangas159,

After many hours spent to try to understand what is the cause of the problem, i think i've understood !

The problem comes from the "visibility" of each course : if it is set to "Private access" (or "closed) the problem occurs (it wasn't the case in Chamilo 1.11.10).

In 1.11.12, the only way i found to have the possibility to sort my courses is to set the visibility of the course to "public" or "open" !

I think, that it should be as it was for 1.11.10 : even if the course is defined as "private" or closed, all users enrolled in this course should have the possibility to see it in his "sort_my_course_menu".

Thanks !

Tanchon.

**Comment by aelalfey** [comment]
Hi, @tanchon @carlangas159 

I have the same issue with Private and Closed courses. Under sort my courses there are no courses to choose "All courses are private in my case"

**Comment by tanchon** [comment]
Thanks @aelalfey : that's a confirmation => with 1.11.12, if courses are defined as "private" (a very common setting) or "closed", the "sort my courses" function becomes inoperative (it was ok with the previous version, 1.11.10).

**Comment by carlangas159** [comment]
Hi @tanchon and @aelalfey ,

If there is a difference in the code between chamilo 1.11.10 and 1.11.12, this filter does not currently show closed or invisible courses, at the moment you can change the value from true to false in main/inc/lib/auth.lib .php for line 36

$visibilityCondition = CourseManager::getCourseVisibilitySQLCondition('course', **true**, $hidePrivate);

remaining as follows
$visibilityCondition = CourseManager::getCourseVisibilitySQLCondition('course', **false**, $hidePrivate);

You can see the change that was made in the following commit 

https://github.com/chamilo/chamilo-lms/commit/90811a329ba840dec96124ef813b53331ecd5bc2#diff-13ce7fc612a88918fcfe83e59fa96555R35

for the moment, we consider this for the next version of chamilo and we will take it into account for that version.

**Comment by tanchon** [comment]
Thanks @carlangas159 for your help.

But, sadly, the "visibility condition" doesn't change the fact that private courses are impossible to sort with 1.11.12

My teachers will be very sad not be be able to sort private courses, because, this functionality was popular (when users are enrolled in a lot of courses, it is very useful).

I think i will erase the "Sort my courses" link on the user portal because it's too much confusing for users : they can sort public or open courses, but not private courses :-) ! 

**To visualize this situation, i made this short video on a 1.11.12 platform i use to make tests : in this video user is enrolled in 4 courses... but can sort only 2 of them (the public courses)

 [video of the "sort my courses bug for private or closed course.](https://youtu.be/nOtfVH1MckI)**

Thank you.

Tanchon.

**Comment by tanchon** [comment]
Hi @carlangas159, @aelalfey 

I found a way to continue to use the "Sort my courses" in 1.11.12... And may be, it can help you @carlangas159  to find a solution.

In 1.11.12, if the platform admin set "HIDE PRIVATE COURSES FROM CATALOGUE" to "NO", then everything is with the "sort my courses" menu (it is possible to see all courses in which user is enrolled, even the privates one).
![Capture](https://user-images.githubusercontent.com/24507698/94053635-e0891700-fdda-11ea-9f94-e5bdc762eed6.JPG)



I was confused because in 1.11.10 the "hide private courses from catalogue" parameter had no effect on the sort my course link (it is more logical). 
In a 1.11.10 platform i defined it to YES and it was possible to see private courses in which users are enrolled in the sort my course menu.

Thanks.

**Comment by tanchon** [comment]
Hi,
This commit from jmontoyaa solves the problem : https://github.com/chamilo/chamilo-lms/commit/93290ce7fa72166d7f78c80886d9c71cf34a9d3a#diff-1012269cb682c478adcc406145664a97

**Comment by tanchon** [comment]
In fact, this commit solves just a part of the problem : the private courses are displayed in the "sort my courses" menu... but **it is not possible to sort them** (it is possible to create categories and to put a course into a category... but not to move a course, up or down into a category).

**Comment by MAMEK70** [comment]
Hi,
What is the current default sorting criteria for courses (in my courses page)? I can't figure it out!! 
Isn't it simpler to have it sorted alphabetically by default?

**Comment by carlangas159** [comment]
hi @tanchon and @MAMEK70 

I have checked that the courses can be moved, as you can see I have a course in a category in a position
![imagen](https://user-images.githubusercontent.com/18097392/100256894-51e86180-2f13-11eb-8f30-4e702f7e1505.png)
This is seen in the position that I have placed it.
![imagen](https://user-images.githubusercontent.com/18097392/100256936-5ad93300-2f13-11eb-9e93-508cf91ebff6.png)

Then I move the course by pressing the yellow arrow up
![imagen](https://user-images.githubusercontent.com/18097392/100256983-662c5e80-2f13-11eb-9d81-d18476751a9f.png)
displayed in the order specified in the courses
![imagen](https://user-images.githubusercontent.com/18097392/100257055-7f350f80-2f13-11eb-988c-63e1e4e3fd1e.png)

@MAMEK70  There is no alphabetical order, they are sorted by order of entry in the first instance when clicking on the pencil inside sort_my_courses
![imagen](https://user-images.githubusercontent.com/18097392/100257447-eb177800-2f13-11eb-8a80-e58a44bc2aa9.png)
then we put it in
![imagen](https://user-images.githubusercontent.com/18097392/100257485-f7033a00-2f13-11eb-9d79-cfca7e35f526.png) 
and this is placed last
![imagen](https://user-images.githubusercontent.com/18097392/100257558-08e4dd00-2f14-11eb-82a3-a2f18cacb63b.png)
That is why there is no alphabetical order, they are adjusted by the income order and then the course can be raised and lowered.

otherwise @tanchon I can't find the problem you describe 

 
> In fact, this commit solves just a part of the problem : the private courses are displayed in the "sort my courses" menu... but **it is not possible to sort them** (it is possible to create categories and to put a course into a category... but not to move a course, up or down into a category).


at the moment I can go up and down the courses within a category. Can you give me more information about what may be happening?

**Comment by tanchon** [comment]
Hi @carlangas159 ,

I cannot reproduce the problem i described  :  I don't know why i had this problem... Now it is ok :-)

From my point of view, this issue can be closed because the "sort my course" is fully functionnal : private courses appears in the list and they can be sorted, even into a category.

Thanks.

Tanchon.
