### ISSUE TITLE
Accesses by user overview (Beta) on clicking page 2 going blank

### ISSUE THREAD

**Issue by kemoche** [chamilo/chamilo-lms#3529]
**Describe**
Upon accessing the link "Accesses by user overview (Beta)" and after generating the report, on either clicking page 2 or change the number of row to see from 20 to 100/All, the page goes blank. The generated report vanishes.

**To Reproduce**
1. Login as Administrator ->Reporting ->Admin View ->Accesses by user overview (Beta)
2. Fill in the fields and Click on generate report
3. Change the number of rows to view ie from 20 to 500 or go to page 2
4. See error - blank page

**Expected behavior**
To see the full generated report

**Screenshots**
See attached screenshot.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome, waterfox latest version

**Server
 - OS CentOS 7.8
 - Version of Chamilo: 1.11.12
 - Version of PHP: 7.2
![Access by user](https://user-images.githubusercontent.com/69464866/93632226-a93ef280-f9f5-11ea-99a2-25b8d2787cbd.jpg)

**Additional context**
It would be nice if I can also be able to download the data

**Comment by carlangas159** [comment]
hi @kemoche 

I have reviewed the problem of why it is not displayed, I have already made an adjustment so that the table is displayed correctly, could you verify it? the related commit is at https://github.com/chamilo/chamilo-lms/pull/3661/commits/37ba6b62b3805d6063e9011ed528c11e19882419

However at the moment we could not attend to the extra functionality that you tell us

**Comment by ywarnier** [comment]
The download should be registered as a feature request in another issue.
