### ISSUE TITLE
"My files" under Social network - Supported Files Upload formats

### ISSUE THREAD

**Issue by aelalfey** [chamilo/chamilo-lms#3545]
Dears @ywarnier @AngelFQC 

"My files" under "Social network" doesn't allow me to upload different types of files. 

![error 1](https://user-images.githubusercontent.com/33488577/94704570-54c63c00-0340-11eb-86aa-aa57f45defc0.jpg)

I tried to edit File types to enable with "new file" but i get this error message.

![error 2](https://user-images.githubusercontent.com/33488577/94704579-5859c300-0340-11eb-84d6-ee73749c1233.jpg)

Any idea what shall i do.

**Comment by carlangas159** [comment]
Hi @aelalfey 

In fact, some types of files are blocked by the mime type, in this case 'application' files are not allowed to be uploaded, which includes pdf because it is of the mime type application / pdf. 
https://github.com/chamilo/chamilo-lms/blob/1.11.x/src/Chamilo/CoreBundle/Component/Editor/Driver/PersonalDriver.php#L46-L53

If you want to enable it, it would be enough to comment on the 'application' line, however, this would allow uploading malicious files, since it would also accept executable files and it is not recommended and therefore, the upload in social for this type of files is currently denied

**Comment by carlangas159** [comment]
I have made an adjustment to allow pdf loading in this element https://github.com/chamilo/chamilo-lms/pull/3551/commits/20c75e4c4af6bab843363d8619d94ac8568ff82c

**Comment by aelalfey** [comment]
Hi @carlangas159,

It works great. Really appreciate your input. Thank you.
