### ISSUE TITLE
Document : bug with cloud links (when trying to move it)

### ISSUE THREAD

**Issue by tanchon** [chamilo/chamilo-lms#3596]
Hi,

In the configuration.php file, I enabled cloud links in document tool : $_configuration['enable_add_file_link'] = true;

In my document tool i created some folders : fold1 fold2...
... and i created some cloud  links : link1 link2 link3...

Everything is ok except when i want to move one of the link to another folder (from "document/" to "document/fold1/" for example.

I select link1 and try to move this file to "fold1/"  : this link is correctly moved but ... the link2 link is moved to !

When i make the opposite and I try to transfer the links1 from document/fold1 to document/,  it is the same issue : the link2 is moved to !

After these manipulations, another issue appear : the fold1 folder diasppears from my list of documents ! And when i try to create it, it is impossible : a warning message appears (the folder already exists).

**Expected behavior**
It should be possible to move the cloud links one by one, without any issue with folders.

**Server
Chamilo 1.11.12
PHP 7.3

This issue occurs with the "general" document tool and the "document" tool of the groups.
It occurs with every folder selected as a destination.
**Even when the domain names are different the issue can occur.**

Sometime, there is no problem : i couldn't determine any explanation.

Some screenshots
![Capture10](https://user-images.githubusercontent.com/24507698/97807208-d7a02680-1c5f-11eb-80c2-22f96e33ecfc.JPG)
![Capture11](https://user-images.githubusercontent.com/24507698/97807213-df5fcb00-1c5f-11eb-80a1-7ca5e3db3250.JPG)
![Capture12](https://user-images.githubusercontent.com/24507698/97807219-e686d900-1c5f-11eb-8189-4182710ba15a.JPG)

Thanks.

Tanchon.

**Comment by carlangas159** [comment]
Hi @tanchon 

I have observed the problem, I have made a slight change that you can see in the pr https://github.com/chamilo/chamilo-lms/pull/3660, I comment that for the current links you must verify that the path field in c_document is correct, because the fault consists of

If the link is in folder 2 and you want to move it to folder 1, the path field would be folder-2 / folder-1 which is wrong, therefore in the path fields the folder-1 text must be eliminated so that reestablish.

![imagen](https://user-images.githubusercontent.com/18097392/100000433-9519c780-2d8f-11eb-8a5d-1915e18369ff.png)
I put an image to show you that you should delete in your database if it is the case.

**Comment by tanchon** [comment]
Hi @carlangas159,

I've made the adjustment into the document.php file and then i made a test with new links : it seems that there is still a problem.

1 :  my new links into their new folders :
![Capture0](https://user-images.githubusercontent.com/24507698/100012541-bf8d7400-2dd3-11eb-9c06-9a841da4dc1c.JPG)

2 : the DB :
![Capture](https://user-images.githubusercontent.com/24507698/100012566-ca480900-2dd3-11eb-853b-cacedc485962.JPG)


After that, i move one of the link to another folder : test rép visio2... and the same bug occurs (the two links are moved) :

![Capture3](https://user-images.githubusercontent.com/24507698/100012846-388ccb80-2dd4-11eb-9e61-0c2481d276ac.JPG)

in the DB :
![Capture2](https://user-images.githubusercontent.com/24507698/100012870-42aeca00-2dd4-11eb-90b3-1132b6a5401c.JPG)

In the DB the link names seem to be ok... but the bug remains when moving links...

Thanks.

Tanchon

**Comment by carlangas159** [comment]
hi @tanchon 

I have verified and indeed all the contents of the source folder are copied to the destination, when it should not be like that.

Could you verify this change? here I adjust the update of the link so that it is only the link, and not all the links, that will move
https://github.com/chamilo/chamilo-lms/pull/3660/commits/69ac604ae15cc2c998c1362e9601af40ce45358a

**Comment by tanchon** [comment]
Hi @carlangas159 

Great ! It works perfectly now !

I made some tests , moving  many times some links, in different level of folders. I modified some link names and folders.... and evrything is still working !
I verified into the DB : it also seems to be ok !
 
Thanks a lot for this work, because my students often use cloud links and the issue was annoying.

Tanchon.
