### ISSUE TITLE
Course group: Settings page generates access error

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#3613]
**Describe**
In a course, in the groups tool, after creating a group (main/group/group.php), when I click on the second icon (settings.png) in the action bar I am sent to main/group/group_category.php?...id=x. As an admin or a teacher, I get a "Not allowed" error and cannot configure the course groups settings.

**Expected behavior**
This should give me access to the group tool configuration.

There's probably a recent change there that uses a different check before calling api_not_allowed() or api_protect_course_script().

**Comment by carlangas159** [comment]
Hello @ywarnier 

I have reviewed and it is not a current change, the edition of the categories would only apply to the courses and not the sessions

> ![imagen](https://user-images.githubusercontent.com/18097392/98853649-76c6da00-2427-11eb-9736-2d175fd2e2a9.png)

First enable "allow_group_categories" in the chamilo parameters, enter the groups of a course and I can edit the categories.

> ![imagen](https://user-images.githubusercontent.com/18097392/98853587-58f97500-2427-11eb-81d9-ddadefbff492.png)

Whereas when I try to access the same section as a session, it is not allowed since 2017.
> ![imagen](https://user-images.githubusercontent.com/18097392/98853605-60b91980-2427-11eb-89c2-d88a62265583.png)


When do you mean that it cannot be accessed from a session or from a course?
  I must also ask you, should sessions have access to editing group categories?

**Comment by ywarnier** [comment]
I missed a step in the description of the procedure:
* with allow_group_categories *disabled*
* create a group
* go back to the "Groups" page (group/group.php)
* click on the last icon of the action bar ("Groups overview") -> group/group_overview.php
* click on "Edit settings" (the second icon) which sends you to group/group_category.php
* the error appears there

I am not in a session.
I am platform admin.

I found the issue. It is a bug introduced in this commit (trying to improve security, probably) https://github.com/chamilo/chamilo-lms/commit/3bd3216d0018ff60a8f1afb68770065bac6663b7.
Fixed in be68fe6366
