### ISSUE TITLE
Excessive HTML filtering in site settings

### ISSUE THREAD

**Issue by roelvisje** [chamilo/chamilo-lms#3656]
at the chamilo platform page when you have a & in the name of the organisation, chamilo adds "amp;" behind the &. 
So you e.g.: we set T&A as name -> save settings. Then you see "amp;" added behind the &. so next time when you change settings you have to adjust the name again, else it will save it as T&amp;A  as name and ofcourse adds another amp; behind the & :).

So to me low prio bug, since it isn't being updated/used very frequently

**Comment by ywarnier** [comment]
@roelvisje 
@lcubas sent a code change (see "3656" link above) which essentially fixes the issue. However, due to the very short time left before the release and the potential to break other things, I will not be applying this patch to the 1.11.14 release. Please follow the link and the "Files changed" tab to check the change and apply it to your portal. We will include it post-1.11.14 to be sure to have enough time to verify that it doesn't break any other part of the application (in particular, I am suspecting there might be side effects when including text in textarea inputs).

**Comment by roelvisje** [comment]
Ah no worries, for me it is a very low priority bug, so better to have it tested thoroughly indeed before applying it.

**Comment by BorjaSanchezBeezNest** [comment]
This little bug doesn't happen in Chamilo 2.
