### ISSUE TITLE
Installing Chamilo fails with fatal error require_once

### ISSUE THREAD

**Issue by Maverickgts** [chamilo/chamilo-lms#3776]
Hi,

first a bit background.  
I am currently working on a remote learning solution for a local school and this is my very first web hosting project on an own server. I have already set up a big blue button server using NGINX as browser and installed PHP7.2-fpm as well as MariaDB.
So the basics are done from what i can see.
I then did download the current version 1.11.14 and moved it to the corresponding folder for the subdomain chamilo.mydomain.
Currently i do not have all the redirects in the chamilo-file under /etc/nginx/sites_available, but have tried this as well before writing here..

To the issue:
When i go to chamilo.mydomain and hit the "Install Chamilo" button i get the following error:
Warning: require_once(//main/inc/lib/database.constants.inc.php): failed to open stream: No such file or directory in /var/www/html/chamilo/main/install/index.php on line 44

Fatal error: require_once(): Failed opening required '//main/inc/lib/database.constants.inc.php' (include_path='.:/usr/share/php') in /var/www/html/chamilo/main/install/index.php on line 44

I did check if the files are available and can confirm
root@srv10438:~# ls -lh /var/www/html/chamilo/main/inc/lib/ |grep databas
-rwxr-xr-x  1 www-data www-data  15K Nov 30 22:59 database.constants.inc.php

I then had a look at the /main/install/index.php and figured out it looks to us a variable named "LIBRARY_PATH".
At a first step i did remove it and set it fix by changing:
require_once api_get_path(LIBRARY_PATH).'database.constants.inc.php'; to
require_once '../inc/lib/database.constants.inc.php'
That worked and sure i did get the next fatal error for the other files that need to be loaded.
I then did revert this change and tried to define the "LIBRARY_PATH" on my own within this index.php, but that resulted in an error reporting that it is already defined.
I did try to figure out where this comes from, but was not able to find out when and with which file this gets loaded.
Also it is hard to believe, that the code has an issue, i think i made a mistake at some stage with the configuration and would like to ask if someone has a hint for me.
if you need more details, just let me know please.

**Comment by lonesomewalker** [comment]
Better NOT install BBB and Chamilo on the same server.
Read docs for BBB about this.

**Comment by ywarnier** [comment]
@Maverickgts Could you post your nginx vhost here?
There seems to be something wrong with the definition of your "root" path or something like this.
Either way, I agree with lonesomewalker: BBB has very specific config settings and you should really either try to run one of them (chamilo or BBB) in a virtual machine on the same server, or have two servers. Chamilo is relativey light (depending on the number of users you want to have) and you should be able to run it "reasonnably" well on one of those latest Raspberry Pi out there (I mean: no need for a big server).
BBB, to the contrary, is rather resources hungry due to the live use of video and audio (and other stuff).

**Comment by Maverickgts** [comment]
I have a dedicated server running Ubuntu 16.04 and have already thought about using a VM for Chamilo, but this would need another IP, which i believe brings new costs for the scool, hence i hope(d) to be able to run it on the same server.

Here you are with the nginx - vhost:

root@srv10438:~# cat /etc/nginx/sites-available/chamilo 
server {
    listen 80;
    listen [::]:80;
    root /var/www/html/chamilo;
    index index.php index.html index.htm;
    server_name  chamilo.MYDOMAIN;

    client_max_body_size 100M;

    location / {
          try_files $uri /index.php$is_args$args;
    }
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass       unix:/var/run/php/php7.2-fpm.sock;
        fastcgi_param      SCRIPT_FILENAME $document_root$fastcgi_script_name;
     }
  charset utf-8;

}

**Comment by ywarnier** [comment]
This is what I use for the .php block:
```
  location ~ \.php$ {
    client_max_body_size 200M;
    try_files $uri @rewrite;
    fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
    fastcgi_split_path_info ^(.+\.php)(/.*)$;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  }
```
Could you try that and see if it helps? I'm guessing the try_files statement might help in this block, but I'm no expert in nginx.

Also, a few notes:
- avoid modifying Chamilo's code. The install should work as is once the web server is well configured.
- Ubuntu 16.04 is good for BigBlueButton, but it's also quite old. Hopefully this is not the issue here
- do you know if nginx-full is installed? It comes with several nginx modules that might be necessary (just a guess, I haven't made a list of the plugins that are required, nor tested Chamilo on a barebone Ubuntu 16.04 install with nginx)
- can you load any other PHP script there? Like `<?php echo "hello";` in a simple "test.php" file at the Chamilo root should show "hello" when you load it in your browser.

**Comment by Maverickgts** [comment]
Many thanks, that helped with the path issue.
Now i get another error:
Fatal error: Cannot redeclare normalizer_normalize() (previously declared in /var/www/html/chamilo/vendor/symfony/polyfill-intl-normalizer/bootstrap.php:18) in /var/www/html/chamilo/vendor/patchwork/utf8/src/Patchwork/Utf8/Bootup/intl.php on line 21

I did try a phpinfo.php and get all the details that it should show.

**Comment by Maverickgts** [comment]
Found it, it was missing php7.2-intl.. looking good now.

once again. Many thanks also to advise not using it on the same server.. i will discuss the options with the school.

**Comment by lonesomewalker** [comment]
You will save A LOT of trouble, especially when installing updates / upgrades from BBB.

**Comment by ywarnier** [comment]
I agree with lonesomewalker... *particularly* when updating BBB
