### ISSUE TITLE
Template image file location in v2

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#3804]
Templates:

https://11.chamilo.org/main/admin/settings.php?category=Templates

Require to save an image here:

`api_get_path(WEB_HOME_PATH).'default_platform_document/template_thumb/'.$template->getImage()`

This needs to be migrate as an Illustration or Asset or something else.

**Comment by ywarnier** [comment]
The *default* template thumbnails should go as assets in assets/doc_templates/[template_name]/thumbnail.[svg|png]
The *added* template thumbnails should go as ... (illustrations, I guess) in var/doc_templates/[template_name]/thumbnail.[svg|png]

The HTML code of those templates themselves will be stored in the database (as it is now).

There are new templates we want to add in Chamilo 2.0. Talk to me when you get to adding the first one (when the structure is ready).

**Comment by christianbeeznest** [comment]
The request is done with this PR https://github.com/chamilo/chamilo-lms/pull/4645

Thanks for confirmation.

**Comment by christianbeeznest** [comment]
It is added in this PR  https://github.com/chamilo/chamilo-lms/pull/5113

**Comment by ywarnier** [comment]
@christianbeeznest The path to save the custom template images is incorrect. Currently, an added custom template will have the image saved in /assets/system_template/[image-name].[extension]. As mentioned "The added template thumbnails should go [...] in var/doc_templates/[template_name]/thumbnail.[svg|png]"

Seeing what is present now, you can simplify to `var/system_templates/[template-name-slug/thumbnail.[extension]` but it should *not* be added to `assets/` as `assets/` is a folder that is only modified through Git, not locally.

For the templates defined at the course-level, the thumbnails should be located in `var/` as well, but `var/doc_templates/[template-name-slug/thumbnail.[extension]` instead of `var/system_templates/`.

All the rest is fine, but the thumbnails should be stored in `var/` (except the ones created during the installation, but at this point there are none, I think). Those should go in `assets/system_templates/[template_name]/thumbnail.[svg|png]`.

Please make sure the migrations are corrected too.

**Comment by christianbeeznest** [comment]
To address the requirements, it is created specific naming strategies for storing assets with VichUploader. We tailored this approach to organize images for custom templates and thumbnails in more suitable directories, using a mix of asset ID and a simplified template name. This approach was chosen due to the difficulty of accessing the related template ID at the asset handling point, ensuring a more organized and manageable file system.

/var/upload/assets/system_template/[image-name].[extension]/[image-name].[extension] is changed by 

/var/upload/assets/system_templates/[id]-[template-name-slug].[extension]  where [id] is the ID of the asset related with the template

the same way for document templates :

var/upload/assets/doc_templates/[id]-[template-name-slug].[extension]

**Comment by ywarnier** [comment]
16309d661f65 and b97bdf4b66 are also linked to this one.

This all works for me. Closing. Thanks!
