### ISSUE TITLE
v1.9.10.4 Exercises wrong random number of questions

### ISSUE THREAD

**Issue by motorcyclist2** [chamilo/chamilo-lms#3822]
Hello,
I need the version v1.9.10.4. I know that there are newer version which solved that issue but I wonder if anyone can help because I need the specific version due to quota and php5.6.
First of all i'm not a programmer so I don't know a lot of stuff about code.
The issuse is the follwoing.
I want to add that in v1.8.8.6 i don't have this problem (it has other sort of issues though) but in v1.9.10.4 in "Exercise" (Tests) when i choose e.g. 5 random questions doesnt chose 5 random questions from the bank but displays them all. For example I have 108 questions in the bank and I want only 10 random ones to be on the Test/Exercise. It displays all the 108 no matter what numbers I select 5,10,25!
Can anyone fix in this version? https://github.com/chamilo/chamilo-lms/releases/tag/v1.9.10.4
Thanks in advance!!!

**Comment by lonesomewalker** [comment]
How about upgrading to a supported version of PHP?
If your hoster doesn't support that -> time to leave.

**Comment by ywarnier** [comment]
Hi @motorcyclist2 

Changes between Chamilo 1.8 and 1.9 were *massive* (a lot of changes in structure in the database) and v1.9.10 has been deprecated since a very long time (1.10 was released May 2016 - almost 5 years ago, see https://beeznest.com/blog/2011/09/27/history-of-chamilo-releases/), so finding this would be very time-consuming for us (i.e. we won't do it because we already have our plate full with current issues and developments).

The fact that you are not a programmer makes this particular issue more complicated even, because you will struggle finding a solution by yourself, and for that I am sorry. However, Github provides a number of tools that could help you out:
 - in this "Issues" tab, you can search (and remove the "status: open" criteria) for any issue using the word "random". After all, there are not a lot of stuff in Chamilo that are supposed to be random, so chances are you will get a nice reduced set of issues about the problem of randomness. Each issue usually has links to changes that were applied to the code to fix those issues
 - if the above doesn't work, you could also get to the tag for the next version, scan the files for the "main/exercises" directory and click on the "history" button to check all the recent changes to that tool
 - if the above doesn't work, you could try and identify (more difficult because you're not a programmer) which file and code snippet this is likely coming from, go to the file and use the "Blame" button to try and find the right change in the right portion of the code

Failing to do any of these, @lonesomewalker 's remark on using a more recent version is really the right answer if you can afford to, as it will fix the issue you have. PHP 5.6 is deprecated and it is not even supported in terms of security patches since the 1/1/2019, so *really* not a good idea.

Finally, let me remind you that we *only* removed support for PHP 5.6 in version 1.11.14 of Chamilo. Version 1.11.12 still had support for PHP 5.6 and you can download a package that supports it here: https://github.com/chamilo/chamilo-lms/releases/tag/v1.11.12
