### ISSUE TITLE
Deprecated warning in installer

### ISSUE THREAD

**Issue by lonesomewalker** [chamilo/chamilo-lms#3842]
**Describe**
```PHP Deprecated:  Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /var/www/chamilo/main/install/index.php on line 462', referer: https://fqdn.server.tld/main/install/index.php?```

Chamilo latest release.

Should i send pull request? :-)

**Comment by ywarnier** [comment]
What version of PHP are you using?
Because of this issue, I checked the installation guide and saw that, although we updated dependencies.html correctly, I did miss a reference to PHP 5.6 and 7.0 still being supported. This is not the case anymore (since version 1.11.14 we only support PHP 7.2, 7.3 and 7.4).

**Comment by lonesomewalker** [comment]
Hi, this server is currently running PHP7.4 with several extensions (so the installer flags all green).
