### ISSUE TITLE
Error: No hay suficiente espacio para enviar este fichero

### ISSUE THREAD

**Issue by jolufe** [chamilo/chamilo-lms#3942]
**Describe el problema**
Cuando intento finalizar un ejercicio de expresión oral la plataforma devuelve el mensaje de error **¡No hay suficiente espacio para enviar este fichero!**. Al mismo tiempo aparece el mensaje **Guardado**, pero el archivo no se guarda. Adjunto captura de pantalla. Algunos alumnos lograron guardar el archivo, pero la mayoría reporta el mismo problema.

Es una instalación de Chamilo reciente y el curso ocupa nada más que 1 MB de espacio. La grabación de audio dura unos 15 s, por lo que no creo que el problema esté relacionado con el espacio en disco ni con el tamaño del archivo.

El único error que aparece en la consola es **[Violation] Forced reflow while executing JavaScript took 81ms.**

Gracias.

**Cómo reproducir**

1. Crear un ejercicio del tipo "Expresión oral".
2. Realizar el ejercicio. 

**Comportamiento esperado**
Que el archivo se guarde correctamente.

**Capturas de pantalla**
![2021-08-11 13 20 35 campusvirtual uttamayoga com 59d088e8b939](https://user-images.githubusercontent.com/40075497/129071657-327bf6eb-e3af-4b10-ae9a-8c0fea925f13.jpg)

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo:  Windows 10 OS Version 2009 (Build 19043.1110)
 - Navegador: Vivaldi 4.1.2369.16 (Stable channel) (64 bits)

**Servidor
 - Sistema operativo: Linux
 - Versión de Chamilo:  1.11.14
 - Versión de PHP: 7.4.21

**Contexto adicional**
Añade cualquier elemento adicional de contexto aquí.

**Comment by NicoDucou** [comment]
Hi @jolufe 

I just tested it on 11.chamilo.org in a test course : https://11.chamilo.org/main/exercise/overview.php?exerciseId=830&cidReq=ORALEXPRESSIONTESTGH3942AND3841&id_session=0&gidReq=0&gradebook=0&origin=&

The audio record got saved correctly as we can see it on the screenshot and the audio record can be listen to in the exercise correction here : https://11.chamilo.org/main/exercise/exercise_show.php?cidReq=ORALEXPRESSIONTESTGH3942AND3841&gidReq=0&gradebook=0&origin=&id_session=0&action=qualify&id=850

![image](https://user-images.githubusercontent.com/6579268/129369337-baba36e6-16a4-4a99-b775-ef00a3d33569.png)

Then I've uploaded a file in the document tool to have 14.36Mo in this course
Then I changed the quota of this course to 10Mo : https://11.chamilo.org/main/admin/course_edit.php?id=276
Now in the document tool we can see that we are using 143.6% of the available space.

I'm going back to the Exercise and do a new attempt. I can record myself but the file is not uploaded to the server and I get the error message once finishing the test : 
![image](https://user-images.githubusercontent.com/6579268/129372450-f98b717a-769c-4ab2-8d84-c9e5f7f596ff.png)

So I can not reproduced the error unless there is no more space in the course.

May be you did not put more than 1Mo of document when creating the course, but there is many way a course can be filled : 
* All the documents in the sessions including this course will be summed up in the course quota, so check the sessions as well
* All the student publications in the assignments tool are summed up in the course quota
* All the exchange document between user in the Dropbox tool are considered as well
* All the audio recording of the users in the oral expression test are also considered so May be the firsts users could record themselves and filled the course with their recording.

So it seems that the problem is more likely to be for a course limit quota exceeded.

If not can you try to reproduce the problem on 11.chamilo.org so we can have a look at it.

Best regards

**Comment by jolufe** [comment]
Hi @NicoDucou

thank you very much for the information. 

I increased the disk space from 95 MB to 150 MB and apparently it works fine now. 

I understand about the sum of resource usage, but the platform report says that I am using only 1 MB of the 95 (now 150) MB allocated, so I didn't look there. 

Is there another place that indicates the space occupied by the course?

![image](https://user-images.githubusercontent.com/40075497/129386076-956565ba-e57b-4ce9-8455-dab289a7efec.png)

**Comment by NicoDucou** [comment]
Hi @jolufe 
The space occupied by a course is something that we want to make better because it is not really clear for the moment. There is nothing more than the course document tool or the course space report on main/admin/system_status.php?section=courses_space accessible from the administration page in the "system" following the link System status.
In chamilo 2 we will have a revision of this and a better way to follow the space usage.

**Comment by jolufe** [comment]
Hi @NicoDucou 
Understood. I close the thread because I think there is no more to add.
Thank you very much.
Regards.
