### ISSUE TITLE
Script fix_quiz_id_to_iid.php ne prend pas en compte track_e_exercises.data_tracking

### ISSUE THREAD

**Issue by meuhland** [chamilo/chamilo-lms#3993]
Si on a un portail affecté par le changement de quiz.id => quiz.iid toute les anciens quiz qui n'affichent plus les bonnes questions/réponse dans les résultats car track_e_exercise.data_tracking n'est pas mis à jour dans le script.

Le id qui affiche les questions est "fetch" dans exercise_show.php comme ça :
```
// Fixing #2073 Fixing order of questions
if (!empty($track_exercise_info['data_tracking'])) {
    $temp_question_list = explode(',', $track_exercise_info['data_tracking']);

    // Getting question list from data_tracking
    if (!empty($temp_question_list)) {
        $questionList = $temp_question_list;
    }
    // If for some reason data_tracking is empty we select the question list from db
    if (empty($questionList)) {
        $questionList = $question_list_from_database;
    }
} else {
    $questionList = $question_list_from_database;
}
```
Sauf que le champ data_tracking n'est pas mis à jour par le script.

Semble aussi que les réponses "matching" ne sont pas pris en compte par le script ce qui cause un mot de tête assez violent lors du passage à 1.11.16, car le champ "correct" pointe sur le auto_id(?) dans c_quiz_answer et non pas le iid n'est pas mis à jour.

**Serveur
 - Système d'exploitation : Ubuntu 20.04
 - Version de Chamilo:  Latest 1.11.x
 - Version de PHP: 7.4

**Comment by Royer17** [comment]
tengo el mismo problema al actualizar la version , no me aparece las preguntas de las evaluaciones del curso , 
nota :ya ingrese el script fix quiz id to iid.php . main/inc ... y el problema persiste

**Comment by ywarnier** [comment]
Nota: @Royer17 reportó en otra tarea que ya pudo arreglar su problema.

**Comment by ywarnier** [comment]
@meuhland (nous sommes fort occupés sur Chamilo 2.0 en ce moment mais dans le courant de la semaine nous devrions reprendre ceci et l'intégrer dans le script, merci! et désolé pour les inconvénients)

**Comment by ywarnier** [comment]
@meuhland Question: est-ce que les résultats affectés sont uniquement des résultats pour des exercices qui ont été passés avant l'installation sur ce serveur de la version 1.11.0, ou est-ce que même des exercices passés sur une version 1.11.x sont affectés? Je ne connais pas l'historique de ton portail, mais j'ai besoin de le savoir pour savoir si le script doit repasser dans tous les  `track_e_exercise.data_tracking` ou juste dans ceux plus récents qu'une certaine date.

**Comment by ywarnier** [comment]
@meuhland juste (pour le portail)! J'avais oublié l'association individu-portail :smile: 
J'ai vu le problème, je suis occupé à le corriger.

**Comment by ecasasnallam** [comment]
I am updating a Chamilo 1.9.x platform to 1.11.16, I launched this script and seeing the results, I think there is an error since the exercises are never displayed.
I think the query of the answers should be as follows since the id column is not unique and in the track_e_attemp table the answer column is related to id_auto.

`$answers = [];`
`$sql = "SELECT id_auto, iid, c_id, question_id FROM $tblCQuizAnswer WHERE id != iid ORDER BY iid";`
`$result = Database::query($sql);`
`while ($row = Database::fetch_assoc($result)) {`
&nbsp;&nbsp;&nbsp;&nbsp;` $answers[$row['c_id'].'-'.$row['id_auto']] = [`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; `'id' => $row['id_auto'],`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; `'iid' => $row['iid'],`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; `'c_id' => $row['c_id'],`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`'q_id' => $row['question_id'],`
&nbsp;&nbsp;&nbsp;&nbsp;];`
`}`

**Comment by ywarnier** [comment]
@ecasasnallam 
Did this query work for you ?
The "id" field is unique *in combination with c_id*. This is due to very old and surprising choices made in our oldest ancestor software. id_auto itself was only supposed to be a sequential (automatically filled) number but was never really thoroughly used globally, so not *that* reliable, but maybe in your case it can be reliable (that's why I'm asking if it worked for you).

**Comment by ywarnier** [comment]
I'm closing the issue based on @meuhland feedback, but feel free to continue the conversation
