### ISSUE TITLE
Video quality selector in chamilo 1.11.x

### ISSUE THREAD

**Issue by Bavarianspirit** [chamilo/chamilo-lms#4126]
Chamilo 1.11.16

Videos in Learning path. There are some options to use.
Link to a video file
new document and use the player button

is it possible to use the chamilo video player with quality selector?
HD = Stream1
SD = Stream2
and so on...

or is there any preferred streaming server (html5) that can give me this option?

Thanks

**Comment by ywarnier** [comment]
Hi @Bavarianspirit 
No preferred streaming server (we usually recommend customers to go with Vimeo if they want to avoid having to manage their own streaming server).
We don't offer streaming quality selectors in Chamilo 1.* because it would mean managing different video qualities on the Chamilo server, which would take more space and encourage people to upload high quality videos ;-)
We expect to be introducing quality selectors in some minor version after 2.0, as we use a better files management layer that should allow us to develop this more easily.
