### ISSUE TITLE
Missing index.php after creating a course

### ISSUE THREAD

**Issue by gemertp** [chamilo/chamilo-lms#4156]
**Describe**
After a course is created, the index.php file is missing in the course directory
Action: Go to https://MyDomain.nl/chamilo/courses/CRS1/
Result: Browser shows Not Found, The requested URL was not found on this server.

**To Reproduce**
Everytime I go to the course. 

**Expected behavior**
Information about the course. I'm learning the chamilo lms, this is the first course I created so I'm not sure what I should expect. But I assume the error is not correct.

**Screenshots**

**Desktop (please complete the following information):**
Linux Fedora 35
Firefox

**Server
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
Chamilo 1.11.16

**Additional context**
Server access.log: "GET /chamilo/courses/CRS1/ HTTP/1.1" 404 511 "https://MyDomain.nl/chamilo/" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0"

**Comment by ywarnier** [comment]
Hi @gemertp 
No index.php should be created. The directory is only used to store files, but loading the /courses/CRS1/ will actually get redirected through the rules in .htaccess in your Chamilo root directory.
Because you are using a subdirectory to store Chamilo, I assume the issue might be that your Apache configuration doesn't allow for the interpretation of .htaccess files (`AllowOverride all`, typically).
Please check the installation guide (search for "AllowOverride") in your documentation/installation_guide.html document.

**Comment by ywarnier** [comment]
Closing (no user feedback in a month).
