### ISSUE TITLE
ERROR message when trying to import file in document or learning path - Message d'erreur à l'import de document 

### ISSUE THREAD

**Issue by GFaucher** [chamilo/chamilo-lms#4175]
Hi, I've first checked in Chamilo user guide, ans then on this forum, but didn' find how to solve it.
Bonjour, j'ai d'abord cherché dans le guide d'utilisation puis sur ce forum, mais je ne trouve pas de solution.

### Current behavior / Résultat actuel
I'm trying to upload files in the document or in the leraning path, but it doesn't work. The transfer bar goes on but at the end, the statut is "error". Whatever the course or the file format (odt, png, pdf, zip). It worked fine until beginning of this week.
J'essaye de télécharger un document dans l'onglet fichier ou dans le parcours pédagogique, mais cela ne marche  pas. La barre de transfert progresse bien jusqu'à la fin, mais le statut final est "erreur". Quelque soit le cours ou le type de document (pdf, odt, png, zip)
Cela fonctionnait correctement jusqu'au début de la semaine.

### Expected behavior / Résultat attendu
When it was working, the final statut was sometinh like "succeed" and I could accessw the files.
Quand cela fonctionnait, le statut final était quelque chose comme "transfert réussi" et je pouvais utiliser le fichier.

### Steps to reproduce / Étapes pour reproduire
Open a course, open a document or a learning path screen, click on "import document", select a document to upload ...
Ouvrir un cours, ouvrir une fenêtre document ou parcours, cliquer sur import fichier, sélectionner le document...

+++ Other / autres
Since it doesn't work, I have a red barappearing sometimes on some screens saying :"access denied".
Depuis que cela ne amrche pas, j'ai de temps en temps une ou plueisurs barres rouges qui me disent "accès non autorisé"

On some courses it works, on others it doesn't, with same access parameter "open" et the same file uploaded (.pdf)
Sur certains cours cela fonctionne, sur d'autres non, avec les mêmes paramètres d'accès "ouvert" et le même fichier téléchargé (.pdf)

+++ What I did / Ce que j'ai fait
I checked the parameters I thought could be different et made them the same.
J'ai vérifié que les paramètres auxquels j'ai pensé étaient identiques sur les deux cours.
I tried to create a new course, but it didn't work
J'ai essayé de refaire un nouveau cours, mais cela ne marchait pas

+++ What I think / Ce que je pense
It doesn't seems to depend on parameters of adminuser, regarding it works sometimes
Courses parameters are the same (course list/edit)
In both cases teacher is admin.
Je ne pense pas que ce soit lié aux paramètre du profil de l'administrateur puisque dans un cas ça marche et dans d'autres non.
Cela devrait être lié au cours, mais pourquoi dans un cas j'ai accès et je peux uploader, et pas dans l'autre. Quel est le paramètre qui n'est pas le même ? J'ai vérifié sur "liste des cours/éditer" et tout est rgélé de la même façon.
Dans les deux cas l'enseignant est admin

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.16

Merci d'avance

**Comment by lonesomewalker** [comment]
What does the errorlog of your webserver say?

**Comment by Coursenligne** [comment]
Could it be related to the size of the document?
It's worth having a look to .htaccess, as this also could be related to provider side that changed the server and/or PHP and SQL version (seen in "another life").

**Comment by GFaucher** [comment]
Thanks for your prompt answers,

I don't think it is related to document size, because 1/file are much 
smaller than th 95 Mo I can use 2/the same file has been upload on 
another learning path.

I'm in a hurry on urgent files beside, I'll  work back on Chamilo from 
middle of the week.

I may spare a lot of time if you can precise me wich files will be 
usefull and how I can get them.
On my list, I noticed .htaccess. and errorlog.

Wishing you a nice Monday,

Gwenaël

Gwenaël FAUCHER,
Gérant, consultant, formateur
tel. : +33 6 20 54 03 87

"Savoir comprendre pour mieux agir"
Publication : "L'art délicat de la relation sociale", 408 pages - 2019
A.G.C. Formation Conseil - 79 avenue de la Cour de France, 91260, Juvisy sur Orge
SIRET : 49168544200023 RCS Evry (91) - Agrément OF :11910605091 - Agréé DATADOCK

www.agc-fc.com

Le 21/02/2022 à 10:25, Coursenligne a écrit :

**Comment by ywarnier** [comment]
Hi @GFaucher 

I took the liberty to delete your personal details from your previous message. When you answer directly by e-mail, make sure you don't include your signature, otherwise it appears publicly here.

To your question...
Chamilo is not "context safe" in all cases. Meaning that, if you have two browser tabs opened in two different courses, the upload in one course could be sent to the other course (it requires a very specific sequence of actions, but it can happen).

My intuition is that something like that is happening, because you mention it was working fine previously, and we didn't make any big change that I know of in this part of the code.

**Comment by GFaucher** [comment]
Bonjour, Hi @the one who answered,

Thank you Yannick for deleting personal details, I'm not used to ways of 
writing on forum, usually I can solve my problems by my own.

_To Yannick_ :
I just tried with only one browser tab opened, but things are remaining 
the same.

_To Coursenligne_ :
I have no problem of size with the documents.
.htaccess file is attached as a document.I can see something like "

# Deny direct access to user my files
RewriteRule ^app/upload/users/([^/]+)/([^/]+)/my_files/(.*)$ main/social/download_my_files.php?user_id=$2&file=$3 [QSA,L]

# Deny access
RewriteRule ^(tests|.git) - [F,L,NC]

But I can't understand what it means.

_To Lonesomewalker_ :
errorlog of the webserver : sorry, I can't find the file.

I'll ask my webservice providerfor further information.
Thank you for your help.

Wishing you a nice day.

Gwen





Here are the elements i can find :

State of Chamilo requirement :

State of PHP settings on the server is attached as document

Maybe a problem on "upload_tmp_dir 
<https://php.net/manual/en/ini.core.php#ini.upload_tmp_dir>", on line 4



Le 23/02/2022 à 12:25, Yannick Warnier a écrit :

**Comment by ywarnier** [comment]
This rule:
`RewriteRule ^app/upload/users/([^/]+)/([^/]+)/my_files/(.*)$ main/social/download_my_files.php?user_id=$2&file=$3 [QSA,L]` 
only applies to the social network, and I think we're getting on the wrong path there. I see nothing particular in `.htaccess` that could affect your situation if you didn't modify it.

One way to get more data without accessing the web server logs is to set your server in test mode.

![chamilo-test-mode](https://user-images.githubusercontent.com/609839/155515229-646d4a43-9962-4953-a7fa-240f792e0fd8.png)

and then trigger the error again (repeat the procedure that leads to the error). That should show you, on screen, the real error. Don't leave it in test mode (just generate the error, copy the error message and move back to production mode), because it's in that mode for everybody, and this can be considered a security issue.

**Comment by GFaucher** [comment]
Hi Yannick,

I tried what you told me to do : switching to test, trigger and générate 
error report.
But it has'nt generate anaything I could find.

My povider gave me ways to access report files.
I'll chek this this week-end.

I confirme that on same tab, some courses work and others dont.

Have a nice week-end.

Gwen



Le 24/02/2022 à 12:25, Yannick Warnier a écrit :
