### ISSUE TITLE
Create Tag, Tag question with created Tags, filter question using Tag

### ISSUE THREAD

**Issue by mygovernance** [chamilo/chamilo-lms#4185]
Hi,
Some times I need to Tag questions , So that It can useful for me to filter all questions of specific Tag.
So Feature is as follow-
1. Admin/Teacher should able to create Tags.
2. Admin/Teacher should able to Tag any question with edit and update.
3. Admin/Teacher should able to filter question of specific Tag while using reuse question feature.

 I am also a developer with more than 7 years of experience, I can also contribute or deliver this feature if some one can help me in ramping up this project.
 Thank you.

**Comment by ywarnier** [comment]
Hi @mygovernance 

This already exist, but let's set you up so you can contribute in similar things in the future.

Creating a tag field to associate to a question is already possible, as admin, through the "Extra fields" link in the "Portal" block of the admin page. I assume you already know that part ("User tag" type)

If the field is marked as "Visible to self" and "Can change", it will appear in the question edition, in advanced params. This is true for admins and teachers, so points 1 and 2 are already there.

What you are missing now is a filter in the possibility to filter on that tag in the main/exercise/question_pool.php page. This is (probably) because the tag field is not marked as "Filter" at this point.

Once you do that, you will be able to filter your questions on tags... easy as that.

Regarding how it works and how to contribute:

Please make sure you check our wiki for coding conventions and, when you send a PR, that you check the feedback sent by the automated validation scripts.

Chamilo is partly procedural, so you can edit question_pool.php directly and find the corresponding filters code.

You can see below that we sanitize a series of params, which do not include extra fields:

https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/exercise/question_pool.php#L41

This is because extra fields are managed separately. They're a dynamic group.

The `$isAllowedToEdit` variable check on line 67 is usually used to check a POST request sent to the script (through the form in the same script), so this will probably not change (this part is meant for the questions *already selected* to be re-used in your exercise)

https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/exercise/question_pool.php#L67

Then you have an AJAX request build-up

https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/exercise/question_pool.php#L213

which, if it was managed as a normal field, you would need to add a "tag" into. It's a bit more complex than that, though, because as you don't know in advance what type of extra field is attached to questions, you would want to show *all* extra fields that are enabled as "filter" as parameter to this AJAX request. We do that differently, though.

Then you have a long section of preparation of the arrays that will be available in the search form. Adding extra fields would probably be done at this stage.

https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/exercise/question_pool.php#L449

Then you have the form building, and that's where you can see that extra fields are already managed there:

https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/exercise/question_pool.php#L512-L513

I'll let you find the rest by yourself, but as you can see it's "relatively" easy to find and we're glad to help, here or on our slack development channel. If you're interested to join, let me know.

**Comment by mygovernance** [comment]
Hi @ywarnier ,
In which version I can use this feature.
Can you please put some screenshot here that would be really helpfull.

**Comment by mygovernance** [comment]
Thank You @ywarnier , I am able to use this feature now.

**Comment by ywarnier** [comment]
Great news!
