### ISSUE TITLE
Fatal error in uploading profile photos

### ISSUE THREAD

**Issue by KiLiMaToS** [chamilo/chamilo-lms#4228]
**Describe**
When I try to update a user's profile by adding a photo, as soon as I try to save I get this fatal error and the photo is not uploaded.
`Fatal error: Uncaught Error: Call to undefined function mime_content_type() in /home/{mydir}/{mydomain}/main/inc/lib/usermanager.lib.php:2605 Stack trace: #0 /home/{mydir}/{mydomain}/main/auth/profile.php(484): UserManager::update_user_picture(3, 'IMG_0762.JPG', '/tmp/php8OxxQh', '0,0,368,368') #1 {main} thrown in /home/{mydir}/{mydomain}/main/inc/lib/usermanager.lib.php on line 2605`

**To Reproduce**
1. Open user profile.
2. Click on edit profile
3. In add image click on "Choose file"
4. Select the PNG-JPG-GIF file
5. Cut image
6. Click on Save Configuration

Same thing if an administrator tries to change the profile from Administration.

**Expected behavior**
Find the uploaded and saved photo in your user profile

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Server**
 - OS: Linux
 - Version of Chamilo:  1.11.16
 - Version of PHP: 7.4

**Additional context**
I tested on a different hosting with the same result.

**Comment by ywarnier** [comment]
This seems to be due to the missing "fileinfo" extension of PHP.
What Linux distribution are you using? On Ubuntu/Debian, this is part of the default PHP extensions (probably inside php-common, because it is not installed as a package).
You might want to add a phpinfo.php file to your Chamilo root folder and load it through your browser:
```
<?php phpinfo();
```
This should show all the extensions that you have enabled, and it will probably *not* include `fileinfo` in your case. It should show something like this:
![fileinfo](https://user-images.githubusercontent.com/609839/160250586-1690e9cb-9740-418e-aaec-3e3654bbf614.png)

This is documented in /documentation/dependencies.html, and also in the installation guide: /documentation/installation_guide.html. Finally, it is also checked for in the installation process, so I'm not sure how you even got there... Maybe you installed Chamilo and then some process removed the fileinfo extension later on?

Anyway, I hope you can install it and tell us this fixed it, or give us more info on what else is failing then, but please check the requirements in the installation guide before you report. We are spending time on this, as you can see.

**Comment by KiLiMaToS** [comment]
I installed Chamilo via Softaculus.  

During installation, if a PHP component is missing, it stops and waits for you to activate the missing PHP component.

So I activated it during installation… but I don't know how it was turned off!

Thank you

**Comment by ywarnier** [comment]
@KiLiMaToS 
OK, no problem. Could you please confirm (so others might find this useful):
1) that the extension was disabled
2) that you could re-enable it
3) that re-enabling it solved this issue of profile photo upload
?

**Comment by KiLiMaToS** [comment]
Of course!

I confirm the issue was caused by the fileinfo() extension being disabled and by enabling this feature, as you suggested, the issue is solved.

Thank you very much
