### ISSUE TITLE
[C2] migration : Add document_id in track_e_download

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#4861]
En Master de momento (1.11.x) tenemos la tabla table track_e_downloads que tiene el campo down_doc_path que permite saber cual es el documento. Seria mejora tener un campo document_id que hace referencia a c_document.iid en vez del campo down_doc_path.
Entonces se necesita : 
* Agregar el campo en la migracion
* asignar los valores de document_id por los registros existente basandose en la correspondencia entre down_doc_path y c_document.path 
* Modificar en Chamilo cuando se registra algo en la tabla track_e_download para que registre el document_id y no el path
* Modificar en Chamilo cuando se recupera algo de la tabla track_e_download para que se use el document_id y si se necesita al path que se busque en la tabla c_document

**Comment by ywarnier** [comment]
So this change has been transformed to add a resource_link_id to track_e_download, because we realized that track_e_download was not only about documents, but other resources as well. Given the fact that the resource_link table contains the context data for any resource (course, session, group, user), we consider this to be the best way to track downloads (well, accesses, really) to a specific resource in a specific context.
This has now been implemented through the PR above.

However, there is still (at least) one issue. When I load /main/tracking/course_log_tools.php?cid=1&sid=0&gradebook=0&origin=, I get "An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c_id' in 'where clause'" for line 4504 of tracking.lib.php. This function needs to be updated to understand the new link with resource_link.

**Comment by ywarnier** [comment]
The commit above fixed the course_log_tools.php issue, but nothing seems to be registering anything in track_e_downloads now. This should be implemented through a listener of some kind @christianbeeznest

**Comment by christianbeeznest** [comment]
It is added in this https://github.com/chamilo/chamilo-lms/pull/5107 to count as a view when you clic on the document's name

**Comment by NicoDucou** [comment]
@christianbeeznest 
There is a problem with the function count_student_downloaded_documents (public/main/inc/lib/tracking.lib.php l4294) that is still using c_id and generates an error because there no more c_id on this table.

**Comment by christianbeeznest** [comment]
Thank you @NicoDucou , it is fixed in this commit https://github.com/chamilo/chamilo-lms/pull/5122/commits/b639fac1e5781bd1d5bc5eb57e6f841c908cfc5a

**Comment by ywarnier** [comment]
I found a series of issues leading to the myStudents.php page, fixed them, and now I cannot find any more issue with the completion of this task here.
