### ISSUE TITLE
Rest with extldap activated doesn’t work

### ISSUE THREAD

**Issue by Apfeldenker** [chamilo/chamilo-lms#4899]
Hello,
this time I’m trying to build a SwiftUI app for Chamilo, which uses Rest web service. The problem is it always tells that the user is invalid, but he isn’t. Has this something to do with using extldap on the website to authenticate.

**Comment by ywarnier** [comment]
Hi @Apfeldenker 
When authenticating for the REST WS, do you use a user that is managed by LDAP? (just trying to figure out how to reproduce)

You could create a user that is not LDAP-managed by ensuring that the "auth_source" column for that user is set to "platform" instead of "ext_ldap" (like... having one additional admin user just for that). If the issue is LDAP, then that should allow you to go around it, at least.

**Comment by Apfeldenker** [comment]
Hi @ywarnier,
I’m using a user which is LDAP managed. I’ll try adding another which is not LDAP tomorrow.
Thanks for the help
