### ISSUE TITLE
Where do I find the flowcharts?

### ISSUE THREAD

**Issue by Edwardb11** [chamilo/chamilo-lms#5239]

**Comment by Edwardb11** [comment]
@ywarnier ?

**Comment by ywarnier** [comment]
Hi. Thanks for asking. You don't (find them). We don't maintain flowcharts for the application because they are (very) time-expensive to maintain as our flows vary very often and we don't have a lot of contributors to justify the additional time spent on these.

If you are doing them anyway, don't hesitate to contribute them back here so others benefit. Thanks in advance for your thoughtful contribution.
