### ISSUE TITLE
Can't add question options to the test.  Am I missing something?

### ISSUE THREAD

**Issue by nathandloper** [chamilo/chamilo-lms#5729]
No matter what question type I use, I cannot find a way to add the answer choices to a question on a test.  The fields to add anything simply aren't there to add any possibilities.  I've tried it with multiple question types and in 3 different browsers.  Am I missing something?

Running Version 1.11.26 via Softaculous install on BlueHost.

![Chamilo](https://github.com/user-attachments/assets/d32e1255-3e39-4501-9243-cada637c54a0)

**Comment by Coursenligne** [comment]
Hi, I'm not sure I understand your issue.
Enter a title, even advanced parameters (such as images or whatever), then just select the correctanswer you want.
In the 2 boxes the first one is the question and the comment can be a tip or a help, or even the answer.
The decide a score for each questions...
If the image you show is the one you get, then check that you are using PHP7.4 and not 8.x, as Chamilo 11 is 7.x PHP version based.
This can be your problem here.

**Comment by nathandloper** [comment]
Yes, after investigation, it seems the PHP version is the problem.  Many hosts require PHP 8 and above for hosted sites and don’t even support lower versions at all, making the software impossible to use and obsolete. I suggest updating Chamilo to be compatible with PHP 8.+ as soon as possible. On Aug 16, 2024, at 8:51 AM, Coursenligne ***@***.***> wrote:﻿
Hi, I'm not sure I understand your issue.
Enter a title, even advanced parameters (such as images or whatever), then just select the correctanswer you want.
In the 2 boxes the first one is the question and the comment can be a tip or a help, or even the answer.
The decide a score for each questions...
If the image you show is the one you get, then check that you are using PHP7.4 and not 8.x, as Chamilo 11 is 7.x PHP version based.
This can be your problem here.

**Comment by Coursenligne** [comment]
I don't want to be rude, but, as you can imagine, Chamilo's devloppers are far away from dummies!
Reading your messages let me think that you are at your first steps in Chamilo.
1.11 barnch was designed while PHP 7.x was the latest release.
As a rule, Chamilo's devloppers NEVER change the database structure (and therefore the database compatibility) for minors release, so here 26, and waiting for 28.
This is to say that, because Chamilo1.11.2 was under PHP 7 version, Chamilo 1.11.258 would be PHP 7 compliant regardless the date of publication.
Thanks to the dev. Team, .258 would never happen and .28 is quite a high number for release.
This means that Chamilo is a long-term support (LTS) LMS by default and this is not like some competitors that publish 2 releases monthly.

I hope this helps.

**Comment by ywarnier** [comment]
We do try to improve the compatibility with PHP8 for lower-level security, even in the 1.11 branch, but so far a series of Chamilo dependencies have been blocking us. There is some hope 1.11.28 will be 99% compatible with PHP 8.3. Time will tell.
Chamilo 2 (currently in development - hopefully available in a few months) will require PHP 8.3 as a minimum.
