### ISSUE TITLE
long load-time on Admin-page when no internet connection

### ISSUE THREAD

**Issue by Dave-1337** [chamilo/chamilo-lms#5743]
I noticed that if you go to the administrator site (main/admin) and then switch to another site, Chamilo hangs for about 125 seconds and does not respond to any input. This is only the case if the server does not have an internet connection. This apparently has something to do with the version check, but I can't find the option to deactivate this anywhere. Or with the Stats Collection, which has been permanently integrated since v1.9.0: " System: The stats collection of Chamilo.org is now automatic. If you want to disable this feature, edit admin/index.php and look for fsockopen() " - however, there is no such entry in said index.php.

How can you deactivate these checks and transmissions if you only want to use the server locally without an internet connection?

I've currently managed this by setting an entry in /etc/hosts 127.0.0.1 version.chamilo.org
But it would of course be nicer to be able to simply switch off this automatic version check

**Comment by NicoDucou** [comment]
Hi @Dave-1337 
Now the call is in a template file, so you need to change the template.
The best way to do it is to copy the template from main/template/default/admin/settings_index.tpl to main/template/overrides/admin/settings_index.tpl 
And then edit this copy to modify this block :
```
        setTimeout(function(){
            $.ajax({
                url: '{{ web_admin_ajax_url }}?a=version',
                success: function (version) {
                    $(".admin-block-version").html(version);
                }
            });
        }, 3000);
```
The easiest way is to change the 3000 to a 1 so that the timeout will be direct and you will not have to wait for the 3000 indicated.

Best regards

**Comment by ywarnier** [comment]
No feedback provided by user. Closing.
